### ISSUE TITLE
How do you bind nulls using the BindArrayOfXX?

### ISSUE THREAD

**Issue by bangusi** [vrogier/ocilib#100]
There is not a single example in the demo of how to bind nulls even though this question comes up quite a lot.
I think an example would be helpful. My problem is I can't figure out how to bind nulls with the BindArrayXX functions .

Here is my attempt ( which is incomplete obviously)

```
	const int arr_size = 2000;
	const int col_size = 200;
	std::vector<wchar_t> val;
	val.reserve(arr_size * sizeof(wchar_t)*col_size);
	int cnt = 0;
	while (OCI_FetchNext(rs))
	{
		if (!OCI_IsNull(rs, 1))
		{
			std::wstring temp = OCI_GetString(rs, 1);
			val.insert(val.end(), temp.begin(), temp.end());
			val.insert(val.end(), (col_size + 1) - temp.size(), L'\0');
		}
		else
		{
			// not sure what to do here when OCI_IsNull returns true
		}

		if (cnt == arr_size)
		{
			OCI_BindArraySetSize(st, arr_size);
			OCI_BindArrayOfStrings(st, (otext*)L":1", (otext*)val.data(), col_size, 0);
			OCI_Execute(st);
			cnt = 0;
			val.clear();
		}
		++cnt;
	}
```

@vrogier I need an example of how to send nulls when binding arrays. Thanks

**Comment by stevemqeen** [comment]
You should look at OCI_BindSetNullAtPos() function, you can retrieve the bind object by OCI_GetBind function.
