### ISSUE TITLE
Binding of Array of Timestamps fails with error '0 Argument 'Timestamp type' : Invalid value 9`

### ISSUE THREAD

**Issue by bangusi** [vrogier/ocilib#103]
Binding a scalar timestamp value works as expected:
```
OCI_Timestamp* tp = OCI_TimestampCreate(cn.hdbc, OCI_TIMESTAMP);
OCI_TimestampFromText(tp, L"2010-03-14 03:00:00.000000000", L"YYYY-MM-DD HH24:MI:SS.FF");
OCI_BindTimestamp(stmt, L":1", tp);
```
Binding Array of timestamps as follows I get a runtime error:
`0 Argument 'Timestamp type' : Invalid value 9`

```
OCI_Timestamp** tp = OCI_TimestampArrayCreate(cn.hdbc, OCI_TIMESTAMP, 6);
	
OCI_TimestampFromText(tp[0], L"2010-03-14 03:00:00.000000000", L"YYYY-MM-DD HH24:MI:SS.FF");
OCI_TimestampFromText(tp[1], L"2010-03-14 03:00:00.000000000", L"YYYY-MM-DD HH24:MI:SS.FF");
OCI_TimestampFromText(tp[2], L"2010-03-14 03:00:00.000000000", L"YYYY-MM-DD HH24:MI:SS.FF");
OCI_TimestampFromText(tp[3], L"2010-03-14 03:00:00.000000000", L"YYYY-MM-DD HH24:MI:SS.FF");
OCI_TimestampFromText(tp[4], L"2010-03-14 03:00:00.000000000", L"YYYY-MM-DD HH24:MI:SS.FF");
OCI_TimestampFromText(tp[5], L"2010-03-14 03:00:00.000000000", L"YYYY-MM-DD HH24:MI:SS.FF");
	
OCI_BindArrayOfTimestamps(stmt, L":1", tp, OCI_CDT_TIMESTAMP, 0);
```

**Comment by vrogier** [comment]
Hi,

The is some issues in your code:

1. When binding array, you need to call OCI_BindArraySetSize() after OCI_Prepare() and before any OCI_BindArrayOfXXXX() calls as mentioned in the [documentation here](http://vrogier.github.io/ocilib/doc/html/group___ocilib_c_api_binding.html)
2. In your call to OCI_BindArrayOfTimestamps(), you have to pass OCI_TIMESTAMP instead of OCI_CDT_TIMESTAMP as mentioned in the function documentation.

The following give expected results:

```
        st = OCI_StatementCreate(cn);

        OCI_Timestamp* tp = OCI_TimestampCreate(cn, OCI_TIMESTAMP);
        OCI_TimestampFromText(tp, OTEXT("2010-03-14 03:00:00.000000000"), OTEXT("YYYY-MM-DD HH24:MI:SS.FF"));
       
        OCI_Prepare(st, OTEXT("insert into test_tp values (:1)"));
        OCI_BindTimestamp(st, OTEXT(":1"), tp);
        OCI_Execute(st);

        OCI_Timestamp** tps = OCI_TimestampArrayCreate(cn, OCI_TIMESTAMP, 6);
        
        OCI_TimestampFromText(tps[0], OTEXT("2010-03-14 03:00:00.000000000"), OTEXT("YYYY-MM-DD HH24:MI:SS.FF"));
        OCI_TimestampFromText(tps[1], OTEXT("2010-03-15 03:00:00.000000000"), OTEXT("YYYY-MM-DD HH24:MI:SS.FF"));
        OCI_TimestampFromText(tps[2], OTEXT("2010-03-16 03:00:00.000000000"), OTEXT("YYYY-MM-DD HH24:MI:SS.FF"));
        OCI_TimestampFromText(tps[3], OTEXT("2010-03-17 03:00:00.000000000"), OTEXT("YYYY-MM-DD HH24:MI:SS.FF"));
        OCI_TimestampFromText(tps[4], OTEXT("2010-03-18 03:00:00.000000000"), OTEXT("YYYY-MM-DD HH24:MI:SS.FF"));
        OCI_TimestampFromText(tps[5], OTEXT("2010-03-19 03:00:00.000000000"), OTEXT("YYYY-MM-DD HH24:MI:SS.FF"));

        OCI_Prepare(st, OTEXT("insert into test_tp values (:1)"));
        OCI_BindArraySetSize(st, 6);
        OCI_BindArrayOfTimestamps(st, OTEXT(":1"), tps, OCI_TIMESTAMP, 0);
        OCI_Execute(st);
```

Best regards,

Vincent

**Comment by bangusi** [comment]
Thank you.  OCI_TIMESTAMP was my problem.
BTW. Do I have to call `OCI_AllowRebinding` if I want to send repeat the binding and is that before the first call to `OCI_BindArraySetSize` ?

**Comment by vrogier** [comment]
Everytime you call OCI_Prepare() all previous binds are cleared.
If you really want to prepare, bind, execute, then re bind different host
variables for same prepared statement, you must allow rebinding prior
rebinding different host variable for same bind identifier.
But that sounds weird.
Why do you want to do that?

**Comment by bangusi** [comment]
Say I am reading millions of rows from one database and copying the data to another.
So I call `OCI_Prepare` once then  in a loop I read 1000 rows then call  set `OCI_BindArraySetSize`, call OCI_BindArrayOfXX,then call  execute then repeat until all rows are finished 
The final batch may even have less then 1000 rows so I need to resize the array size, bind and do final execute. My array of host variable is still the same throughout. I am simply re-using them. I am not sure if this is the scenario that calls for `OCI_AllowRebinding`

**Comment by vrogier** [comment]
In this case, you don't have to rebind!

Follow the sequence:

- prepare
- set the array size to your batch size
- bind your host variable array
- execute in loops
- for final iteration set again the array size to a smaller value
- execute last batch
