### ISSUE TITLE
OCI_BAM_INTERNAL example for wchar_t ?

### ISSUE THREAD

**Issue by Zeks** [vrogier/ocilib#105]
I seem to be unable to make it work and it's not documented anywhere.  I get crashes on free() with code like below. All "Get" calls work with success codes. Could you please provide an example of internall allocation for strings?

```
   auto bamResult = OCI_SetBindAllocation(Statement, OCI_BAM_INTERNAL);
   if(!Statement)
        return falseDiag(QString("failed to bind value because Statement is null") );
    auto wstrValue = bind.wstr_value();
    int sz = wstrValue.size() + 1;
    if(sz == 0)
        sz = OCI_BIND_STRING_MAX_LEN; // 16000
    std::wstring placeholder = bind.wstr_placeholder();
    auto bindResult = OCI_BindString(Statement, placeholder.c_str(), nullptr, sz);
    if(!bindResult)
    {
        OCI_Error *err = OCI_GetLastError();
        LastError = ShowError(err);
        QLOG_ERROR() << "Error: " + LastError.text();
        return falseDiag(QString("failed to bind string for: ") +  bind.qstr_placeholder());
    }
    auto bindHandle = OCI_GetBind2(Statement, placeholder.c_str());
    if(!bindHandle)
    {
        OCI_Error *err = OCI_GetLastError();
        LastError = ShowError(err);
        QLOG_ERROR() << "Error: " + LastError.text();
        return falseDiag(QString("failed to get bind handle for ") + bind.qstr_placeholder());
    }
    auto realSize = OCI_BindGetDataSize(bindHandle);
    wchar_t* allocated = static_cast<wchar_t*>(OCI_BindGetData(bindHandle));
    if(!allocated)
        return falseDiag(QString("failed to get allocated array for ") + bind.qstr_placeholder());

    wmemset(allocated, L'\0', sz);
    wmemcpy(allocated, wstrValue.c_str(), sz);
```

**Comment by vrogier** [comment]
Hi,

Why don't use use  OCILIB C++ API ?

Otherwise, could you provide more information about when it is crashes ? You say on "free" but when ?

Here is a small example adapted from you code that works as expected:

```

        OCI_Statement *st = OCI_StatementCreate(con);
        auto bamResult = OCI_SetBindAllocation(st, OCI_BAM_INTERNAL);
        OCI_Prepare(st, L"insert into test_table values (:1)");

        std::wstring wstrValue = L"123456789";
        int sz = wstrValue.size() + 1;
        auto bindResult = OCI_BindString(st, L":1", nullptr, sz);

        auto bindHandle = OCI_GetBind2(st, L":1");
        auto realSize = OCI_BindGetDataSize(bindHandle);
        wchar_t* allocated = static_cast<wchar_t*>(OCI_BindGetData(bindHandle));

        wmemset(allocated, L'\0', sz);
        wmemcpy(allocated, wstrValue.c_str(), sz);

        OCI_Execute(st);
        OCI_Commit(cn);
        OCI_StatementFree(st);
```

Best regards,

Vincent

**Comment by Zeks** [comment]
We've started using ocilib way before C++ API became a thing and as a result we have our own C++ API over it  :)

I am 100% sure this crash is my mistake as I am in the process of major refactor of said C++ API , but I had to be sure I understand INTERNAL usage with strings correctly. Up to this point we've always created memory externally and there was no eample in C API. (Array examlple doesnt strictly apply as it leaves toom for error)

P.S. What happeds if a sinle query also needs to pass a BIGINT? Do I still instantiate string with nullptr and pass big inti externally?

**Comment by vrogier** [comment]
Currently, all binds must conform to the same mode, thus you cannot mix the behavior among different binds for a given statement.

**Comment by Zeks** [comment]
So, essentially, if I want to pass big int I have to force extranl allocation for everyting? That's kinda a problem >_< Quite possibly means I will have to scrap iternal allocation altogetehr because there is literally no benefit internally, I will still have to jeep extrenal arrays in the memo structure which is what I wanted to get rid of...

**Comment by vrogier** [comment]
In fact, when I've added the ability for OCILIB to allocate bind buffers, i couldn't change all OCI_BindXXXX() prototypes for adding a new parameter indicating if the bind buffer had to be internally allocated without breaking existing code.

When we extend an API, we sometimes cannot do what we want and also somtimes make mistakes.

But, If you look at the source code, OCI_Statement structure holds the information set by OCI_SetBindAllocation() but does not really use it on its own.
Instead it is just  providing it to OCI_Bind structure that stores it.

Thus, you may call OCI_SetBindAllocation(OCI_BAM_INTERNAL) and then perform few binds calls.
Then you can call OCI_SetBindAllocation(OCI_BAM_EXTERNAL) and perform other bind calls.

It will work but it means that the value of OCI_GetBindAllocation() is not really meaningful as you would have binds with different values while the OCI_Statement, at a given moment, will return its own value.

What I can do is to add a OCI_BindGetAllocationMode(OCI_Bind*) to return the value stored in a Bind object.
And update the documentation of OCI_SetBindAllocation() and OCI_GetBindAllocation() to mention that the value is transient and only used when performing new bind calls.

**Comment by Zeks** [comment]
Oh, so juggling allocation modes will work, huh. i will have to try it. I assumed it detects internally if the tpyes need external allocation, but juggling will totally be okay... I think. Thx.

**Comment by vrogier** [comment]
Thus, i am going to commit a new call OCI_BindGetAllocationMode() and an update of the OCI_GetBindAllocation() and OCI_SetBindAllocation() documentation

Example of what you want to do:

```c
       int i = 42;

        OCI_Statement *st = OCI_StatementCreate(cn);
        OCI_Prepare(st, "select :i, :s from dual");

        OCI_SetBindAllocation(st, OCI_BAM_EXTERNAL);
        OCI_BindInt(st, ":i", &i);

        OCI_SetBindAllocation(st, OCI_BAM_INTERNAL);
        OCI_BindString(st, ":s", NULL, 20);

        otext* s = OCI_BindGetData(OCI_GetBind(st, 2));
        ostrcpy(s, "42");

        OCI_SetBindAllocation(st, OCI_BAM_EXTERNAL);

        printf("allocation mode for :i  = %d\n", OCI_BindGetAllocationMode(OCI_GetBind(st, 1)));
        printf("allocation mode for :s  = %d\n", OCI_BindGetAllocationMode(OCI_GetBind(st, 2)));
        printf("allocation mode current = %d\n", OCI_GetBindAllocation(st));


        OCI_Execute(st);       
        OCI_Resultset *rs = OCI_GetResultset(st);
        if (OCI_FetchNext(rs))
        {
            printf("fetching i=%d, s=%s\n", OCI_GetInt(rs, 1), OCI_GetString(rs, 2));
        }
```

which gives the following result:

```
allocation mode for :i  = 1
allocation mode for :s  = 2
allocation mode current = 1
fetching i=42, s=42
```

**Comment by vrogier** [comment]
Update committed!
