### ISSUE TITLE
How to initialize OCI_Number from C types

### ISSUE THREAD

**Issue by bangusi** [vrogier/ocilib#107]
Is there a way to initialize `OCI_Number` from C types such as `int`, `float `and `double `without having to convert the value to text and calling `OCI_NumberFromText`?

**Comment by vrogier** [comment]
Hi,

Yes you can assign and retrieve C typed value to/from OCI_Number using OCI_NumberSetValue() / and OCI_NumberGetValue().

Example:

```c
        OCI_Number *num = OCI_NumberCreate(NULL);
        double dbl_value1 = 3.14, dbl_value2 = 0.0;
        OCI_NumberSetValue(num, OCI_NUM_DOUBLE, &dbl_value1);
        OCI_NumberGetValue(num, OCI_NUM_DOUBLE, &dbl_value2);
```


Regards,

Vincent

**Comment by bangusi** [comment]
Thank you.

**Comment by bangusi** [comment]
@vrogier Does OCI_Number own the memory of the assigned value? i.e. In your example if db1_value1 goes out of scope does OCI_Number still have a valid pointer to the declared double?

**Comment by vrogier** [comment]
Values are assigned to OCI_Number objects.
Thus there is no scoping issues

**Comment by bangusi** [comment]
Thank you.
