### ISSUE TITLE
How to suppress exceptions from OCI_ExecuteStm

### ISSUE THREAD

**Issue by bangusi** [vrogier/ocilib#108]
Sometimes I need to ignore errors like dropping a table that does not exist.
If I have  provided an error handler to` OCI_Initialize() `I find it hard to optionally suppress some errors.
This is not an ocilib issue per se but would be useful for me  to know what the ocilib idiomatic would be.
What I have tried which does not succeed suppressing the error

> if (!OCI_ExecuteStmt(hstmt, sql)
> {
>   //ignore	;
> }

**Comment by vrogier** [comment]
I do not know if providing a way to not fail on some errors would be the right thing.
Could be a nice feature but would make troubleshooting more complex especially when I have to investigate on user's issues.
You could have your own function that examine the last error code (from global handler or OCI_GetLastError()) in case of failure.

What would you suggest ?

**Comment by bangusi** [comment]
I was thinking some sort of boolean flag to the error handler with a default behaviour of throwing exception always but suppressing them when specifically requested.
As I said this is more like a programming issue than ocilib but I have learned not to try re-invent the wheel with ocilib because the library is so feature rich that I may be implementing something which already exists.

**Comment by vrogier** [comment]
thus, how you would see it?

**Comment by bangusi** [comment]
Here is one way this guy did it
http://otl.sourceforge.net/home.htm
`otl_cursor::direct_exec( connection, "drop table test_tab", otl_exception::disabled  );`

**Comment by cjbj** [comment]
Or handle it all in the DB like this:
`execute immediate 'drop table mytable; exception when others then if sqlcode <> -942 then raise; end if;`

**Comment by bangusi** [comment]
@cjbj  db level solution is an acceptable workaround for my needs. Thanks.
