### ISSUE TITLE
Can I set a NULL value to a bind variable using C++ interface?

### ISSUE THREAD

**Issue by kornefalk** [vrogier/ocilib#11]
I have not found any way to tell the Oracle database that I want to insert a record consists of some values and some NULL values using C++ interface.

Shouldn't there we a function in Statement that sets a column to NULL ?
i,e, BindToNull(ostring name);

**Comment by vrogier** [comment]
Hi, 

you can use BindInfo::SetDataNull()

	st.GetBind(":name").SetDataNull(true, 1);

or 

	st.GetBind(position).SetDataNull(true, 1);

For single bind, the second parameter must be 1.
For array bind, the second parameter is the index in the array

I haven't added an overloaded method for single binds...

**Comment by vrogier** [comment]
Little update, the second parameter is defaulted to 1 in its prototype.
Thus, for single bind, use:

	st.GetBind(":name").SetDataNull(true);

or 

	st.GetBind(pos).SetDataNull(true);
