### ISSUE TITLE
OCI_GetString behaves badly with empty LOBs

### ISSUE THREAD

**Issue by alicemaz** [vrogier/ocilib#112]
oracle allows you to create non-null, zero-length CLOB/LOB columns, which several functions do not expect to see. my actual use case is somewhat esoteric (I'm selecting data from triggers that run on a logical standby, and oracle streams propagate LOBs to the standby by first inserting a row with an empty LOB, then subsequently updating it to its actual value) but a trivial case is easy to reproduce:

create test data:
```
create table maztest (id number(38) primary key, c clob not null, b blob not null);
insert into maztest values (1, empty_clob(), empty_blob());
insert into maztest values (2, '0123', '4567');
insert into maztest values (3, empty_clob(), empty_blob());
commit;
```

and when you select, using `OCI_GetString` for c and b:
```
id: 1, c: (null), b: (null)
id: 2, c: 0123, b: 4567
id: 3, c: 0123, b: 4567
```

so what happens is because the first row's LOBs are defined but empty, `OCI_DefineIsDataNotNull` returns true and `OCI_STATUS` is set to true in `OCI_GetString`. we call `OCI_StringGetFromType` which hits the `OCI_CDT_LOB` case of the switch. `OCI_LobRead2` doesn't fetch any bytes because there aren't any, and `OCI_StringGetFromType` returns zero as bufsize, causing `OCI_RETVAL` to not be set and `OCI_GetString` returns null pointer

second row works normally

third row, the same thing happens as the first where we flow through the definedness check with true status to the bottom of the if statement. `OCI_StringRequestBuffer` gives us the same internal buffers as used for the second row, because they are more than large enough. `OCI_StringGetFromType` does the same as the first row where `OCI_LobRead2` does nothing, except it gets to the bottom and reads the size of the data that's already in the buffer passed in. so it returns a nonzero number and the caller of `OCI_GetString` sees the same data as before

**Comment by alicemaz** [comment]
I have a small patch for this, but I remember from last time you might not be able to take it because copyright. also I'm not sure if this issue is present in other places, this is the only way I ever fetch LOBs. but basically the buffer needs to be reinitialized as empty every round, and `OCI_GetString` needs to be able to return a pointer to an empty string in this particular case

**Comment by vrogier** [comment]
Hello,

Thanks for finding that issue ;)
You're right indeed, the temporary buffer may content previous rows non string to string conversion buffer. Good catch!

I've committed a fix for it. I could have simply added a

` if (ptr) *ptr = 0; `

at the beginning of OCI_StringGetFromType(). This would have fixed your issue.

In the fix, I've added more checks about the buffer size passed to OCI_StringGetFromType() and avoided systematic usage of ostrlen() as for some types, the type specific conversion function already computed the information.
Committed fix does the job but is not perfect as, to be honest, to be completely resilient, I should spend to time to refactor this internal conversion stuff to check buffer size everywhere to make buffer overrun impossible. Maybe later. Current usage is safe as internally, buffer are always allocated with sufficient size.

Regards,

Vincent

**Comment by alicemaz** [comment]
thank you, your fix already was much more extensive than mine was :) I tried out the latest version and it properly clears the buffer for reuse, but still returns null pointer rather than pointer to empty string for empty CLOB/BLOB, was wondering if you intended to address this at a later time or leave as is?

**Comment by vrogier** [comment]
Done :) Made another commit for it for handling empty CLOB/BLOB/RAW

**Comment by alicemaz** [comment]
ah, perfect! thank you again
