### ISSUE TITLE
How to disable signal handler for interrupt

### ISSUE THREAD

**Issue by brano543** [vrogier/ocilib#115]
Hello,

I am running a simple web server, but anytime i try to store Connection object inside a class to save it for all SELECT sql's, I am unable to stop my server (ctrl+c). Could you please help me? It is really annoying to kill the server every time manually with kill when doing testing.

**Comment by vrogier** [comment]
Hi,

Can you give more details about the issue ?

regards,

Vincent

**Comment by brano543** [comment]
Hello,

if the Connection is defined as member 
```
class Oracle
{
  Connection conn; //use ths connection for read-only transactions
public:
  Oracle(string &dest);
  ~Oracle();
  vector<OracleAPI::TableInfo> find_tables(string &table_name_prefix); //find tables for prefix
  OracleAPI::TableInfo find_table(string &table_name);
  vector<OracleAPI::Relationship> get_relationships(string &table_name);
  //returns vector for each result found, 
  //spaces in column value are replaced by # if replace_spaces is ture
  vector<string> execute_query(string &sql, bool replace_spaces = false);
};
```
and I am using it during the lifetime of the Oracle object, I am unable to send signals to the server. This is the problem of Ocilib, i have tried two different libraries for server - facebook Wangle and Haywire.

I have tried to look for this sqlnet.ora file , but there is only example file and it doesn't make any difference if i add the option - https://stackoverflow.com/questions/17124881/oracle-proc-oci-install-handlers-for-sigsegv-sigabrt-and-friends-why-and-how. Unfortunately Oracle doesn't provide source for Oracle client so I can't compile it without the signal handlers.

**Comment by vrogier** [comment]
Hello,

Are you sure your sqlnet.ora file is used?
Are you using instant client?
Have you tried this?

DIAG_ADR_ENABLED=OFF
DIAG_SIGHANDLER_ENABLED=FALSE
DIAG_DDE_ENABLED=FALSE

**Comment by brano543** [comment]
Hello,

I am using Ubuntu and I have installed Instant client Basic and SDK from rpm - oracle-instantclient12.2-basic-12.2.0.1.0-1.x86_64.rpm and oracle-instantclient12.2-devel-12.2.0.1.0-1.x86_64.rpm .

> Are you sure your sqlnet.ora file is used?
Where should I exactly put it? There is only one sqlnet.ora located in $HOME/Oracle/Middleware/Oracle_Home/network/admin/samples/sqlnet.ora.

**Comment by vrogier** [comment]
If using instant client, you need to set the environment variable TNS_ADMIN
with the folder containing sqlnet.ora in order to have it taken into
account by instant client.

**Comment by vrogier** [comment]
Hi,

Any news ? Did you manage to make it work as expected?

**Comment by brano543** [comment]
Sorry, I was so busy at work that I couldn't even try that simple solution from all the stress I have. I will check it by the end of this week.

**Comment by brano543** [comment]
I don't know when these magical variables are activated,but your advice did the trick. 
Things I did for anyone who might have the same problem.
Add to ~/.bashrc
```
#Oracle
export ORACLE_HOME=/usr/lib/oracle/12.2/client64
export PATH="$PATH:$ORACLE_HOME/bin"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$ORACLE_HOME/lib"
export TNS_ADMIN="$ORACLE_HOME/network/admin"
```
We also need to set up TNS_ADMIN environment variable pointing to sqlnet.ora file to be able to interrupt server.
```
sudo mkdir -p /usr/lib/oracle/12.2/client64/network/admin/
sudo sh -c "echo 'DIAG_SIGHANDLER_ENABLED=FALSE' >> /usr/lib/oracle/12.2/client64/network/admin/sqlnet.ora"
```
Strange thing is even after i deleted sqlnet.ora later it still worked, so I don't quite understand how it works under the hood.

**Comment by brano543** [comment]
Unfortunately this only works for interruption of simple multitihreaded program. The problem with ignoring ctrl+c for server(I am using Haywire which uses event loop and I am 100% sure the library is OK) still remains :(

**Comment by brano543** [comment]
Hello,

I was able to resolve by adding all of the options you mentioned:
DIAG_ADR_ENABLED=OFF
DIAG_SIGHANDLER_ENABLED=FALSE
DIAG_DDE_ENABLED=FALSE
and recompiling my application. Seems like it is determined on compilation time based on environmental variables how the library will behave. This should be added somewhere in documentation for this library so it is less confusing.
