### ISSUE TITLE
test_describe() no "SCHEMA NAME" for UDT type

### ISSUE THREAD

**Issue by andygeng** [vrogier/ocilib#116]
Hi, here is sqlplus output:
SQL> desc sys.t_udt
 Name                                      Null?    Type
 ID                                                 NUMBER
 UDT                                                ANDY.MY_UDT

Here is test_describe() output:
Column Name         NULL ?  Type
ID                  Y       NUMBER
UDT                 Y       MY_UDT
It is better to include schema name in OCI_ColumnGetFullSQLType() function. 
:)
Thanks.

**Comment by vrogier** [comment]
Hi,

Sqlplus seems to show schema name in desc command when the UDT owner is different from either current schema or parent UDT schema.

I can systematically add the schema as requested (thus being not conformant to sqlplus behavior) or find out what is sqlplus rule for displaying or not the schema name.

I may go for option 1. Any insights are welcome :)

**Comment by vrogier** [comment]
Requested code modification committed
