### ISSUE TITLE
Bug in OCI_NumberCompare

### ISSUE THREAD

**Issue by DerWeiseScheuch** [vrogier/ocilib#118]
Always returns 0, since number1 is compared to istself instead to number2:

`OCI_EXEC(OCINumberCmp(number1->err, number1->handle, number1->handle, &value))`

**Comment by vrogier** [comment]
Hi,

Thanks for reporting issues :)
Resovled by commit 5662c8a.

Regards,

Vincent

**Comment by DerWeiseScheuch** [comment]
You are welcome. Nice library - use it for the 1st time since a couple of days :-)
What's the procedure - how does this fix find its way to a new downloadable version of dll/lib etc?

Regards,
Thomas.

**Comment by vrogier** [comment]
Hi,

A new release of OCILIB 4.4.1 will be scheduled soon wrapping up latest fixes (probably this week)
In the meanwhile, you can recompile OCILIB DLLs using projects  located in ocilib\proj\dll\.

Best regards,

Vincent
