### ISSUE TITLE
MagicNumber[1] in OCI_NumberToString is not handled properly

### ISSUE THREAD

**Issue by dbpm** [vrogier/ocilib#121]
file src/number.c, line #457 is defined as

            if (memcmp(number, mag_num->number, sizeof(mag_num->number)) == 0)

while it should compare 3 bytes for magic number #0 and two bytes for magic number #1, 
it will be better to fix next way:

            if (memcmp(number, mag_num->number,  mag_num->number[0] + 1) == 0)

**Comment by vrogier** [comment]
Hi,

Why ? Oracle number (OCINumber) is a struct containing an array of 22 byte.
The comparison function assume the input number is a valid initialized OCINumber.
Thus comparing 3 bytes still does the job in any case (regarding current checked values)

Regards,

Vincent

**Comment by dbpm** [comment]
Tailing bytes in the 22 byte array (bytes after the first two 0x01,0x00) are undefined and can be any, not zeroes only.
External libraries can pass you practically any value in non-valuable "tail" part and it still be valid Oracle number, OCI handles it properly.

**Comment by vrogier** [comment]
OK, if using external OCINumber (from OCILIB point of view) is a use case, then I will update the implementation for next release.

**Comment by vrogier** [comment]
Issue addressed
