### ISSUE TITLE
TIMESTAMP WITH TIMEZONE is not fully supported when using default formats

### ISSUE THREAD

**Issue by dbpm** [vrogier/ocilib#122]
ocilib.h

1) in addition to 
#define OCI_STRING_FORMAT_TIMESTAMP         OTEXT("YYYY-MM-DD HH24:MI:SS.FF")

we need

#define OCI_STRING_FORMAT_TIMESTAMP_WITH_TIMEZONE         OTEXT("YYYY-MM-DD HH24:MI:SS.FF TZR")

2)  library.c
next list should be extended to support TIMESTAMP WITH TIMEZONE

static otext * FormatDefaultValues[OCI_FMT_COUNT] =

3) OCI_TimestampFromText() OCI_TimestampToText()  should support timezones, if those are defined

**Comment by vrogier** [comment]
Hi,

Timezone information string formatting is independant from the timestamp type.
You can use the "TZR" token with any type of timestamp.
And you may have a timezone with timestamp and not want to print its timezone information.
But to_char() is by default adding the timezone info is the timestamp type is with time zone.
Thus for coherence and conformance reasons with SQL methods, I  make the requested change that will be included in next release

Regards,

Vincent

**Comment by vrogier** [comment]
Issue addressed
