### ISSUE TITLE
bug in OCI_DirPathSetColumn

### ISSUE THREAD

**Issue by dbpm** [vrogier/ocilib#124]
Please consider next lines (last one)

            case OCI_CDT_DATETIME:
            case OCI_CDT_TIMESTAMP:
            case OCI_CDT_INTERVAL:
            {
                dpcol->type = OCI_DDT_OTHERS;

                if (OCI_STRING_VALID(format))
                {
                    dpcol->format      = ostrdup(format);
                    dpcol->format_size = (ub4) ostrlen(format);
                    dpcol->maxsize     = (ub2) dpcol->format_size;

that way user specified maxsize value is ignored, as it is not possible to specify 
format YYYY-MM-DD HH24:MI:SS.FF and value 2014-12-31 01:23:45.000678 
because last 4 chars (0679) will be truncated because maxsize is will be calculated as length of string YYYY-MM-DD HH24:MI:SS.FF, while value is longer

affected line should be defined next way:

                    dpcol->maxsize     = (ub2) maxsize > dpcol->format_size ? maxsize : dpcol->format_size;

**Comment by vrogier** [comment]
Hi,

will be fixed for next release.

Regards,

Vincent

**Comment by vrogier** [comment]
Issue addressed
