### ISSUE TITLE
Question about cross-compiling

### ISSUE THREAD

**Issue by brano543** [vrogier/ocilib#125]
Hello,

how did you manage to compile ocilib for Windows? I have tried to provide --host=x86_64-w64-mingw32 to the configure script, but it is still searching for libclntsh.dll which doesn't exist for Windows. Are you using a separate project and if not, can you share your wisdom so I can make my project more portable by avoiding manually copying files?

**Comment by vrogier** [comment]
OCILIB Windows shared libraries are already provided in OCILIB packages under lib32 and lib4 folders.

When targeting non Windows platforms, I use autotools for compiling OCILIB.
When targeting windows platforms, I use Microsoft compiler to produce OCILIB binaries.
Currently the configure script does not on Windows (for the reason you've mentioned)
The archive also provide a code::blocks project file to built OCILIB as static library.
I could see to make configure works on Windows (requires Cygwin or MSYS tu run autotools).
Or provide a cmake project file...
But so far visual studio/prebuilt binaries for windows and autotools for other platforms always did the job up to now.

regards,

vincent

**Comment by brano543** [comment]
Yes, now I understand,it was easier to integrate the way you are doing it now by providing the compiled DLLs for MinGW. The thing is Oracle is missing official mirrors where to download it from,so the first stage always has to be done manually - downloading the Instant Client.
