### ISSUE TITLE
OCI_NumberToText(), OCI_NumberFromText() and TM format

### ISSUE THREAD

**Issue by dbpm** [vrogier/ocilib#126]
At the moment TM format is not supported by OCI client library functions, it's known issue.

But that way is not possible to pass neither arbitrary large values nor arbitrary small values, nor scientific values in E-notation by default. Current default format is suitable for financial applications only.

From first sight we need to implement own TO_CHAR(num, 'TM') and TO_NUMBER(str, 'TM')

The issue has origin from generic task: export practically any number into text file and import it back to server, but I can't dictate users which numbers they can or can't use, they expect default TM9 like behavior of TO_CHAR(num) without any format - which can convert any values.

**Comment by dbpm** [comment]
as reference/sample implementation please take a look into dpiUtils__parseNumberString() - 
google knows about this function

though I can't guarantee that the implementation is complete/bugfree/etc

**Comment by vrogier** [comment]
By the way, no other issues to open soon  ?
I am thinking about releasing v4.4.1 soon. 
I've addressed 3 of your issues.
Just to know if I have to include more stuff :)

Thanks

**Comment by dbpm** [comment]
No other issues/feature requests at the moment, excepting #42  one - I have got implementation which allows to send NUMBER, DATE and TIMESTAMPs into direct path API in native (non-text) format, but it's still in "unstable" branch and testing is in progress.

All those requests which I opened last week is result of ocilib 4.4 adopting, I'm merging own enhancements which were implemented in 3.x version years ago, so please take your time, all that is not urgent.

**Comment by vrogier** [comment]
About, #42, I will take time to think about it before Christmas.

Regards,

Vincent

**Comment by vrogier** [comment]
Release v4.4.1 is drafted on github and will be published tomorrow.

Regards,

Vincent

**Comment by vrogier** [comment]
closing the issue as TM format will not be implemented in OCILIB unless supported by OCI
