### ISSUE TITLE
Should OCI_Cleanup() close open threads ?

### ISSUE THREAD

**Issue by Zeks** [vrogier/ocilib#131]
I am debugging a resource leak in my application (most likely not related to OCILIB) and I noticed something strange: if you call OCI_ConnectionFree  &  OCI_Cleanup immediately after you OCI_Initialize & OCI_ConnectionCreate the 3 threads that were created automatically during the first calls do not go away. Is it normal behaviour? 
#

**Comment by vrogier** [comment]
Hi,

Sorry for late response.  
Thread creation/deletion is OCI client job. 
OCI client is known for  keeping stuff (memory and thread) after OCI cleanup.
google "valgrind+oracle+oci" and you will find lots of content.

Best regards,

Vincent
