### ISSUE TITLE
Binding objects of inherited types causes data loss.

### ISSUE THREAD

**Issue by y-maltsev** [vrogier/ocilib#132]
Hi,
I'm trying to work with inherited object types. 
In Oracle I've defined a simple ADT and a subtype for it:
```
create type ym_base as object(id number, name varchar2(200), trailer number ) not final; 
create type ym_derived under ym_base (sid number ); 
```
Then when binding the object with the subtype everything seems OK until i try to access the data from the subtype. In this case, the sid.

  ```
    Statement stO(con);
    Object objIO(TypeInfo(con, "ym_derived", TypeInfo::Type));

    stO.Prepare("begin :objIO:=ym_derived(1,'Maltsev',123,1666); end;");
    stO.Bind(":objIO",objIO,BindInfo::Out);
    stO.ExecutePrepared();
    std::cerr<<objIO<<std::endl; 

//YM_DERIVED(1, 'Maltsev', 123, )
```
This data loss happens regardless if the bind variable is input or output one.
I can't confirm if this happens only when the subtype has a number member while the last member of the supertype is also a number, as its the only case I've found so far.

**Comment by vrogier** [comment]
Hi,

What version of ocilib are you using?

Regards,

Vincent

**Comment by vrogier** [comment]
Hi,

This is bug, indeed related to super type / sub types.
Thanks for reporting that :)

In the case of  sub types deriving from super types, OCILIB is computing wrong offsets for sub object types members properties within the opaque oracle buffer holding objects data.

I've been working on a fix and will commit it this evening.
I will include a sample in the demo based on your example.

Regards,

Vincent

**Comment by vrogier** [comment]
Fix committed :)
Enjoy!

Thanks again for reporting issues :)

Vincent
