### ISSUE TITLE
Inherited objects member access issues

### ISSUE THREAD

**Issue by y-maltsev** [vrogier/ocilib#135]
<This is a continuation to issues #132, #133 and #134>

Hello Vrogier,

I'm sorry for opening yet another issue connected to the inherited objects, but there are still some active problems. 

Here are the test cases:
 
### CASE 1 (crash, no exception)

```
CREATE TYPE TYPEA AS OBJECT( OID NUMBER ) NOT FINAL;
CREATE TYPE TYPEB UNDER TYPEA( DESCR VARCHAR(24) ); 
```
      Statement st1(con);
      Object objIO1(TypeInfo(con, "dmc.typeb", TypeInfo::Type));
      ostring DESCR;

      st1.Prepare("begin :objIO:=dmc.typeb (79,'xxx'); end;");
      st1.Bind(":objIO",objIO1,BindInfo::Out);
      st1.ExecutePrepared();
      DESCR = objIO1.Get<ostring>("DESCR"); // error, no exception
      std::cerr<<objIO1<<std::endl; // error, no exception

### CASE 2 (with exception)
```
create type ym_base as object(id number, name varchar2(200), trailer number ) not final; 
create type ym_derived under ym_base (sid number ); 

create type base_t as object (id number, name varchar(12)) not final;
create type derived_t under base_t (pid number ) not final; 
create type derived2_t under derived_t (sid2 number ); 
```

  ```
    Statement st1(con);
    Statement st2(con);
    Statement st3(con);
    Object objIO1(TypeInfo(con, "ym_derived", TypeInfo::Type));
    Object objIO2(TypeInfo(con, "derived_t", TypeInfo::Type));
    Object objIO3(TypeInfo(con, "derived2_t", TypeInfo::Type));

    st1.Prepare("begin :objIO:=ym_derived (1,'Maltsev',123,1666); end;");
    st1.Bind(":objIO",objIO1,BindInfo::Out);
    st1.ExecutePrepared();
    std::cerr<<objIO1<<std::endl; // OK: YM_DERIVED(1, 'Maltsev', 123, 1666)

    st2.Prepare("begin :objIO:=derived_t (1,'Maltsev',123); end;");
    st2.Bind(":objIO",objIO2,BindInfo::Out);
    st2.ExecutePrepared();
    std::cerr<<objIO2<<std::endl; // OK: DERIVED_T(1, 'Maltsev', 123)

    st3.Prepare("begin :objIO:=derived2_t (1,'Maltsev',123,1666); end;");
    st3.Bind(":objIO",objIO3,BindInfo::Out);
    st3.ExecutePrepared(); //OK
    std::cerr<<objIO3<<std::endl; // ERROR, exception: OCI-22060: argument [2] is an invalid or uninitialized number
```
I hope I'm not bothering you too much with this.

Best regards,
Yani

**Comment by vrogier** [comment]
Hi,

Regarding case1, It runs fine on my box with C API (I hadn't tested yet with C++ API, but if C one is fine, C++ shall be ok).

Regarding case2, there is still an offset issue when the object is derived from an object derived itself from  another one.
I will fix the case 2 issue this evening and will combine all of your tests cases in the super_type.c and super_types.cpp samples.

Regards,

Vincent

**Comment by vrogier** [comment]
It should be fine now :)

**Comment by y-maltsev** [comment]
Hello,

Thank you for the fix on case 2. As usual, you have great response time.

However case 1 still persists with me, even though i tested it on two different machines. The problem is still an offeset one - Get is trying to access offset 22 while string data is located at 24, resulting in a segmentation fault when trying to convert the result to ostring. 
Are you sure you're unable to reproduce it on your side? If not, is there anything that could suggest why the problem persists with me? 

Best regards.

**Comment by vrogier** [comment]
regarding the following definition

```sql
CREATE TYPE TYPEA AS OBJECT( OID NUMBER ) NOT FINAL;
CREATE TYPE TYPEB UNDER TYPEA( DESCR VARCHAR(24) ); 
```

the C structures corresponding to object is something similar to

```C
struct OCINumber
{
    ub1 OCINumberPart[22];
};

struct TYPEA
{
    OCINumber OID;
};

struct TYPEB
{
    TYPEA Parent;
    OCIString *Descr;
};
```

thus, sizeof(TYPEA) shall be 24 bytes on a 32bit box as is must be aligned.
And it seems logical that the Descr member of TYPEB is at the offset 24 as it is the aligned size of TYPEA.

I will check asap what values it on my box (which by the way uses a 64 bits version of Oracle). 
Offset 22 is not normal whatever 32 or 64bit.

I will let you know this evening.

Regards,

Vincent

**Comment by vrogier** [comment]
Hi,

object.c, line 247, replace the following block

```c
            if (i < typinf->nb_cols)
            {
                size_t dummy_align = 0;

                /* get next member size and discard its alignment computation */

                OCI_ObjectGetAttrInfo(typinf, i, &size2, &dummy_align);

                /* use parent structure alignment instead */

                typinf->align = align;
            }
```

with 

```c
            if (i < typinf->nb_cols)
            {
                 size_t next_align = 0;

                /* get next member size and discard its alignment computation */

                OCI_ObjectGetAttrInfo(typinf, i, &size2, &next_align);

                /* set parent structure alignment as it is the first field */

                typinf->align = align;

                /* make sure that parent is aligned */

                size = ROUNDUP(size, next_align);
            }
```

**Comment by vrogier** [comment]
Hi,

I've committed a new fix. And re-tested all of your samples with success.
Let me know if it is ok for you.

Regards,

Vincent

**Comment by y-maltsev** [comment]
Hello Vrogier,
This time all test cases ended successfully.
Thank you so much for all the support during this last week. You are truly dedicated to this project.
Аll the best.
Yani

**Comment by vrogier** [comment]
You're welcome:)
