### ISSUE TITLE
Can't handle empty string in objects

### ISSUE THREAD

**Issue by y-maltsev** [vrogier/ocilib#138]
Hello,

Trying to set an empty("") string to a object's variable causes a malfunction in the object class.
Easiest way to detect is ToString(), which stops to function or causes an error outright. However Get still seems to work.

```
CREATE OR REPLACE TYPE RESPONSE_T
  AS OBJECT(
    err_code        NUMBER,
    err_descr       VARCHAR2(200)
) NOT FINAL;
/
CREATE OR REPLACE TYPE CARD_RESPONSE_T 
  UNDER IH_RESPONSE_T(
    pin_enc         VARCHAR2(16),
    cvc1            VARCHAR2(4),
    cvc2            VARCHAR2(4),
    pvv             VARCHAR2(4),
    prod_data       VARCHAR2(4000)
  ) ;
/
```

```
    Object card2;
    card2 = Object(TypeInfo(con, "typeb_t", TypeInfo::Type));
    card2.Set<ostring>("PIN_ENC", (ostring)""); --empty string
    card2.Set<ostring>("PVV", "223");
    card2.Set<ostring>("CVC1", "334");
    card2.Set<ostring>("CVC2", "445");
    card2.Set<ostring>("PROD_DATA","556");
    std::cout<<"PIN : "<<card2.Get<string>("PIN_ENC")<<std::endl;
    std::cout<<"PVV : "<<card2.Get<string>("PVV")<<std::endl;
    std::cout<<"CVC1: "<<card2.Get<string>("CVC1")<<std::endl;
    std::cout<<"CVC2: "<<card2.Get<string>("CVC2")<<std::endl;
    std::cout<<"PROD: "<<card2.Get<string>("PROD_DATA")<<std::endl;
    std::cout<<"TS: "<<card2.ToString()<<std::endl;
```
In this object setup i get the following output and error: [PasteBin](https://pastebin.com/93qpG47P)

In all other cases, instead of this error, ToString simply returns nothing:
`TS:`

Note. I'm unsure under what circumstances the error occurs as the very same oracle objects renamed to 'typea_t' and 'typeb_t' at my side don't cause an error. ToString still does nothing. 

The test on my side has been made with the latest version of ocilib.

Best regards.

**Comment by vrogier** [comment]
Hi,

With the previous fixes for inherited objects, OCI_ObjectToText() and OCI_CollToText() had been modified to fail if a member/element string value was NULL while the member/element itself was not NULL :(

I've committed a fix for it and the following code returns the output below.

Code:

```C
        OCI_Object *card2 = OCI_ObjectCreate(cn, OCI_TypeInfoGet(cn, "CARD_RESPONSE_T", OCI_TIF_TYPE));
        OCI_ObjectSetString(card2, "PIN_ENC", "");
        OCI_ObjectSetString(card2, "PVV", "223");
        OCI_ObjectSetString(card2, "CVC1", "334");
        OCI_ObjectSetString(card2, "CVC2", "445");
        OCI_ObjectSetString(card2, "PROD_DATA", "556");

        printf("PIN_ENC   : %s\n", OCI_ObjectGetString(card2, "PIN_ENC"));
        printf("PVV       : %s\n", OCI_ObjectGetString(card2, "PVV"));
        printf("CVC1      : %s\n", OCI_ObjectGetString(card2, "CVC1"));
        printf("CVC2      : %s\n", OCI_ObjectGetString(card2, "CVC2"));
        printf("PROD_DATA : %s\n", OCI_ObjectGetString(card2, "PROD_DATA"));
   
        char buffer[512] = "";
        unsigned int size = sizeof(buffer);
        OCI_ObjectToText(card2, &size, buffer);
        printf("CARD2 : %s\n", buffer);

        OCI_ObjectFree(card2);
```



Output:

```bash
PIN_ENC   :
PVV       : 223
CVC1      : 334
CVC2      : 445
PROD_DATA : 556
CARD2 : CARD_RESPONSE_T(NULL, NULL, '', '334', '445', '223', '556')
```

**Comment by vrogier** [comment]
I've just noticed that SQL*Plus is behaving differently 

```sql
create table test_card(value card_response_t);
insert into test_card values ( CARD_RESPONSE_T(NULL, NULL, '', '334', '445', '223', '556'));
select * from test_card;
```

output is

```
VALUE(ERR_CODE, ERR_DESCR, PIN_ENC, CVC1, CVC2, PVV, PROD_DATA)
--------------------------------------------------------------------------------
CARD_RESPONSE_T(NULL, NULL, NULL, '334', '445', '223', '556')
```

thus it does not report an empty string but NULL.
I might stick to SQL*Plus behavior and modify my fix....

**Comment by vrogier** [comment]
With latest commit, the output is 

```bash
PIN_ENC   : (null)
PVV       : 223
CVC1      : 334
CVC2      : 445
PROD_DATA : 556
CARD2 : CARD_RESPONSE_T(NULL, NULL, NULL, '334', '445', '223', '556')
```

**Comment by vrogier** [comment]
By the way, I have drafted the v4.5.0 release.
Have you noticed any other issues ?
If so, which ones ? 
If not, let me know as I could then publish the release.

Thanks :)

Regards,

Vincent

**Comment by y-maltsev** [comment]
Hello Vrogier,
I've executed all tests that we had from our previous issues in addition to all new ones.
Everything ended successful.

So, no, i haven't noticed anything else as a problem.

Once again you don't fail to amaze me how fast you react to issues for ocilib.

I'm sorry that i keep posting new and new issues over the same thing. Even though by now I have dozens of tests, they are far from covering all possible test cases. :(

Again, thank you so much for your support.

Best regards,
Yani

**Comment by vrogier** [comment]
You're welcome :)

Regards,

Vincent
