### ISSUE TITLE
Version 4.5.0 is on its way!

### ISSUE THREAD

**Issue by vrogier** [vrogier/ocilib#140]
Hi all,

Version 4.5.0 is drafted and should be released soon (a couple of days max).

Once it will be released, I will start to apply git good practices and use git flow :)
Thus, master branch will always be clean and will reflect last known production stable releases.
No more development commits on master!
Any new development will be done in develop-vX.Y branches.
Patches (if required) for version 4.X will be done in hotfix-v4.Y branches.
I will start with a develop-v5.0 that will be a major internal refactoring of the library + minor API breaking changes in order to correct mistakes from the past.

Regards,

Vincent

**Comment by mwitczak69** [comment]
Go Vincent Go!!!!!!

**Comment by vrogier** [comment]
V4.5.0 had been released on Feb 7th.

**Comment by vrogier** [comment]
Dear all,

I have drafted a v4.5.1 release from develop-v4.5.1 branch.

I will publish it asap unless someone reports an issue in the meantime.

Vincent

**Comment by vrogier** [comment]
Version 4.5.1 has been released

**Comment by vrogier** [comment]
Version 4.5.1 is released :)
