### ISSUE TITLE
When to use the ocilib vs. ocilibw

### ISSUE THREAD

**Issue by bangusi** [vrogier/ocilib#149]
My Oracle database ( 12c ) is running on Linux (CentoOS 7).  The characterset is **AL32UTF8**.  My client most often runs on Windows but would like it to run in Linux as well.  It is linked against **ocilibw**. My question is it necessary to compile my client against **ocilibw** or **ocilib** would work just as well?  Also would the decision be different if my Oracle server was running on Windows with the same characterset?

**Comment by vrogier** [comment]
Hi,

The platform where your Oracle database runs is transparent, even its server side charset (most of the time), as Oracle performs charset conversions between client and server.

if you're dealing only with UTF8 based charsets, you can use the ANSI version of OCILIB on all platforms.
You can also use the wide character version of OCILIB on all platforms (OCILIB dealing internally with the differences of wchar_t across platforms).

OCILIB let you decide to use either:
- char* strings  (ANSI/UTF8, OCI_CHARSET_ANSI)
- wchar_t* strings (UTF16 on windows, UTF32 on Linux that are converted internally in OCILIB to UTF16)

Regards,

Vincent

**Comment by bangusi** [comment]
@vrogier What would your recommendation be if one wants to minimize characterset conversions between the client and the server? I am assuming the conversion has some non-negligible cost.
