### ISSUE TITLE
Test with korean character set in windows environment .

### ISSUE THREAD

**Issue by tommybee** [vrogier/ocilib#150]
I've tested C and C++ test source with the latest ocilib.

My C version is working while C++ version is not in one case.

The case i met program crash while i set the database character as a UTF-8 and the console character set as a korean. 
My database's character set is a 'KOREAN_KOREA.KO16MSWIN949'.

So, i don't know what i am missing.

Here is what i did for this testing.

1. Installation process.
Here is my configure command when built the latest version of ocilib with mingw32-gcc.

`./configure --prefix=/home/tsms_file_search \
--with-oracle-headers-path=C:/DEV/COMP/instantclient-basic-nt-12.1.0.2.0/instantclient_12_1/sdk/include \
--with-oracle-lib-path=C:/DEV/COMP/instantclient-basic-nt-12.1.0.2.0/instantclient_12_1 \
--with-oracle-home=C:/DEV/COMP/instantclient-basic-nt-12.1.0.2.0/instantclient_12_1 \
 --with-oracle-import=linkage
`
I've installed the instant client from oracle site too, where the path of installation is C:/DEV/COMP/instantclient-basic-nt-12.1.0.2.0/instantclient_12_1.

2. Souce code
I made two version of sources, testocilib.c and testocilib.cpp from the ocilib_demo source code in the demo folder. These are console applications as you know.

My query statement is as follows,
const char *query = 
		"SELECT "
		"	CMP_COD,"
		"	ATCH_FLE_TP_COD,"
		"	ATCH_FLE_TP_NM,"
		"	ATCH_FLE_STRG_PATH_NM"
		" FROM CMM_ATCH_FLE_PATH";

The 'ATCH_FLE_TP_NM' column contains string with korean characters.
I have the same function, test_fetch which is borrowed from the demo source.
CPP version>
`void test_fetch(void)
{
	const char *query = 
		"SELECT "
		"	CMP_COD,"
		"	ATCH_FLE_TP_COD,"
		"	ATCH_FLE_TP_NM,"
		"	ATCH_FLE_STRG_PATH_NM"
		" FROM CMM_ATCH_FLE_PATH";
			
    ocout << otext("\n>>>>> SIMPLE TEST FETCH WITH META DATA\n\n");
	
    Statement st(con);
    st.Execute(otext(query));

    Resultset rs = st.GetResultset();
    for (int i = 1, n = rs.GetColumnCount(); i <= n; i++)
    {
        ocout << otext("> Field : #") << i << otext(" - Name : ") << rs.GetColumn(i).GetName() << oendl;
    }

    ocout << oendl;

    while (rs++)
    {
    	ocout << otext(", FILE_NAME[한글]  : ") << rs.Get<ostring>(3)<< oendl;
    }

    ocout << oendl << rs.GetCount() << otext(" row(s) fetched") << oendl;
}`

C version>
`void test_fetch(void)
{
    int i, n;
	
	const char *query = 
 			"SELECT "
    		"	CMP_COD,"
    		"	ATCH_FLE_TP_COD,"
    		"	ATCH_FLE_TP_NM,"
    		"	ATCH_FLE_STRG_PATH_NM"
			" FROM GISIT.CMM_ATCH_FLE_PATH";
	
    print_text("\n>>>>> SIMPLE TEST FETCH WITH META DATA\n\n");

    /* execute query in one go */
    OCI_ExecuteStmt(st, OTEXT(query));

    rs = OCI_GetResultset(st);
    n  = OCI_GetColumnCount(rs);

    /* print resultset columns info */
    for(i = 1; i <= n; i++)
    {
        OCI_Column *col = OCI_GetColumn(rs, i);

        print_frmt("> Field : #%i ", i);
        print_text("- Name  : "); print_ostr(OCI_ColumnGetName(col));
        print_text("\n");
    }

    print_text("\n");

    /* print resultset content */
    while (OCI_FetchNext(rs))
    {
        print_frmt(", FILE_NAME[한글]  : %s", OCI_GetString(rs,3));
        print_text("\n");
    }

    print_frmt("\n%u row(s) fetched\n", OCI_GetRowCount(rs));
}`

3. Test
I set the character set of my console to UTF-8 as following command
`chcp 65001`  
I also set the NLS_LANG variable to korean below
`SET NLS_LANG=KOREAN_KOREA.KO16MSWIN949`

The output of this c++ version was one line:
, FILE_NAME[�ѱ�]  :

The expected result must be 500 rows.
Here is C version output:
.....skip
, FILE_NAME[�ѱ�]  : ��Ȳ��������
, FILE_NAME[�ѱ�]  : �μ�����
, FILE_NAME[�ѱ�]  : ���Ͼ�������

500 row(s) fetched
Oracle connection success!

Here are testing results for the two console applications:

C version: All working
Console(chcp 949): Korean, database(NLS_LANG): KOREAN_KOREA.KO16MSWIN949
Console(chcp 949): Korean, database(NLS_LANG): KOREAN_KOREA.AL32UTF8
Console(chcp 65001): Korean, database(NLS_LANG): KOREAN_KOREA.KO16MSWIN949
Console(chcp 65001): Korean, database(NLS_LANG): KOREAN_KOREA.AL32UTF8

CPP version: 
Console(chcp 949): Korean, database(NLS_LANG): KOREAN_KOREA.KO16MSWIN949 - working
Console(chcp 949): Korean, database(NLS_LANG): KOREAN_KOREA.AL32UTF8 - working
Console(chcp 65001): Korean, database(NLS_LANG): KOREAN_KOREA.KO16MSWIN949 - not working
Console(chcp 65001): Korean, database(NLS_LANG): KOREAN_KOREA.AL32UTF8 - not working

Thanks in advance,

**Comment by vrogier** [comment]
Hi,

As C++ API is built on top on C API, I think it is more a console output issue.
 
In C++ version, have you tried to replace std::cout by printf() ?


Regards,

Vincent

**Comment by tommybee** [comment]
Hi,

I appreciated on your comment.

I changed the line of source code at which you pointed,

printf(", ATCH_FLE_TP_NM  : %s", rs.Get<ostring>(3));

then it is working..

Here are my test cases...
>>>>>>>>>>>>>>>>>>>>>>>>>>>>
case 1:
SET NLS_LANG=KOREAN_KOREA.AL32UTF8
chcp 949

output:
ATCH_FLE_TP_NM  : p?,
500 row(s) fetched

case 2:
SET NLS_LANG=KOREAN_KOREA.AL32UTF8
chcp 65001

output:
ATCH_FLE_TP_NM  : p?,
500 row(s) fetched

case 3:
SET NLS_LANG=KOREAN_KOREA.KO16MSWIN949
chcp 949

output:
ATCH_FLE_TP_NM  : 入(,
500 row(s) fetched

case 4:
SET NLS_LANG=KOREAN_KOREA.KO16MSWIN949
chcp 65001

output:
ATCH_FLE_TP_NM  : ��(,
500 row(s) fetched
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

But, i wasn't able to get a proper korean string at any cases i'd tested in C++ version.

It's very interesting...^^;

I think that must be definitely one of console issue as you've commented.

What next action i should  do about this problem for my curiosity reason ?

Have a good day ~~

Thanks,

**Comment by vrogier** [comment]
You may dig into forums related to C++ iostreams.
I'm afraid I will not be a valuable help on that point!

Regards, 

Vincent

**Comment by tommybee** [comment]
Thanks for your kind response. I am actually using mingw with gcc. I will
try to dig the problem some other time in the future.

Best regards,

2018년 3월 21일 (수) 오전 5:35, Vincent Rogier <notifications@github.com>님이 작성:
