### ISSUE TITLE
Connection with ORACLE_SID

### ISSUE THREAD

**Issue by lnxbil** [vrogier/ocilib#151]
Hi everyone,

is there a way to connect only with `ORACLE_SID` and `sys/ as sysdba`?
Connection with password works fine, yet I want to use the same mechanism I'm using for years with `sqlplus`.

Best,
Andreas

**Comment by vrogier** [comment]
Hi,

Have you tried to pass 'sys' as user, null as pwd and OCI_SESSION_SYSDBA as mode?
Or even with null user if you want to use your windows account as authentication.

Regards,

Vincent

**Comment by lnxbil** [comment]
I only tried host and password `NULL` - user was `SYS`, I just tried with all three `NULL` and then it works :-D

Thanks.

**Comment by lnxbil** [comment]
Maybe this should be written somewhere besides the issue tracker.

**Comment by vrogier** [comment]
It is already mentioned in the documentation of OCI_ConnectionCreate() :

"Note
External credentials are supported by supplying a null value for the 'user' and 'pwd' parameters. If the param 'db' is NULL then a connection to the default local DB is done
For parameter 'mode', the possible values are exclusive and cannot be combined"

**Comment by lnxbil** [comment]
Damn, I read that and misunderstood it. Sorry, my fault!
