### ISSUE TITLE
linux ctrl +c can't kill the program at after call Connection

### ISSUE THREAD

**Issue by zhxq59** [vrogier/ocilib#157]
15  int main(void)
 16 {
 17         io_service ioService;
 18  
 19         boost::asio::strand            strand_(ioService);
 20         boost::asio::io_service::work  workOracle(ioService);
 21  
 22         Environment::Initialize();
 23         Connection con("192.168.1.103:1521/orcl", "system", "zhxq");
 24  
 25        /* Statement st(con);
 26 
 27         string  strSql ="SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') FR    OM DUAL";
 28         
 29      st.Execute(strSql);
 30         
 31         Resultset rs = st.GetResultset();
 32         while (rs.Next())
 33         {
 34                 std::cout <<"time: " << rs.Get<ostring>(1) << std::endl;
 35         }*/
 36 
 37 
 38         ioService.run();
 39 
 40         Environment::Cleanup();
 41         return EXIT_SUCCESS; 
 42 }
this code, after Compiled and run, can't kill by ctrl +c; but do away with Connection ,ctrl +c kill the program ok ??

**Comment by vrogier** [comment]
Closing the isssue as no news from OP
