### ISSUE TITLE
How to bind a char[N] buffer using the C++ API

### ISSUE THREAD

**Issue by caduel** [vrogier/ocilib#166]
Is it possible to bind a C struct character array using the C++ API of Statement::Bind?
I did not find a suitable overload.

**Comment by vrogier** [comment]
Hi, 

Can you provide an example of data type ?

Regards,

Vincent

**Comment by caduel** [comment]
Sure, given a struct like
`struct AnOldCStruct
{
    int id;
    char name[31];
};
`

I would like to bind a column to the struct's member name.

```
// create table TableForOldStruct ( id NUMBER, name VARCHAR2(30) );

AnOldStruct old;
strcpy(old.name, "Miller");

Statement st(...);
st.Prepare("select id, name from TableForOldStruct where name=:name");
st.Bind(":name", old.name, sizeof(old.name), BindInfo::In); // does not compile

```

I can bind a std::string to the column, but would prefer to avoid that and directly fill my target buffer.

**Comment by vrogier** [comment]
Hi,

Sorry for late response.

The C++ API that not provide statement:: bind<> specialization for C arrays in order to use C++ types instead.
You can add your own specialization if needed.

Best regards,

Vincent

**Comment by caduel** [comment]
Ok, thank you. I am working around the problem.
(Even in C++ code you need to work with legacy code / types that uses char[] instead of std::string; so such bindings would make sense there too.)
