### ISSUE TITLE
How to seek/write/append a null clob column ( not empty_clob() value )?

### ISSUE THREAD

**Issue by gmxyb** [vrogier/ocilib#167]
OCIException : [OCI_LobSeek] A null Lob handle has been provided

**Comment by vrogier** [comment]
Hi, 

Can you provide more information?

Thanks

Regards,

Vincent

**Comment by gmxyb** [comment]
Thanks.  My table:   TabA ( id number,  bigtext clob );

id      bigtext
----   ----------
1       null
2       null

OCI_Execute(" select id, bigtext from TabA")....
rs = OCI_GetResultset....
rs.OCI_FetchNext...
lob = OCI_GetLob(rs, 2);
OCI_LobTruncate(lob, 0); 

// OCIException : [OCI_LobSeek] A null Lob handle has been provided
// Because TabA.bigtext is null

**Comment by vrogier** [comment]
Hi,

I'm afraid that you cannot do that. 
First, if the select is not a "select ... for update", there is no way update a long column from a resultset.
Second, if the data is null, it is null. You cannot appendi data to a null lob.  Like for strings, strcat()will not work on a null pointer. Same here for lobs.

Regards,

Vincent

**Comment by gmxyb** [comment]
Thanks.

I can only execute "update TabA set bigtext=empty_clob() where bigtext is null" before "select ... for update"...
