### ISSUE TITLE
How to enumerate all variable names of a prepared statement?

### ISSUE THREAD

**Issue by gmxyb** [vrogier/ocilib#168]
OCI_Prepare(stmt, "select * from tabx where id=:id and name=:name")

// get ":id" and ":name" ... ???

**Comment by vrogier** [comment]
Hi, 

oci_getbindcount()
oci_getbind()
oci_bindgetname()

Regards,

Vincent

**Comment by gmxyb** [comment]
thanks!

**Comment by gmxyb** [comment]
@vrogier 

oh... 
OCI_Prepare(stmt, "select * from tabx where id=:id and name=:name"); // OK
OCI_GetBindCount(stmt) // **RETURN 0**!!

**Comment by vrogier** [comment]
You need to call oci_bindXXX() first.

**Comment by gmxyb** [comment]
This is a common function, like ExecSQL(sql, map<string, value> varval).
I can not call oci_bindXXX()  because I unknown the variable names.
I want to find variable names from STMT, and get the variable value from "varval" by name, 
if found , call oci_bindXXX()

**Comment by vrogier** [comment]
Ocilib is not parsing sql statement.
Thus, you have to do it yourself if you want to do it prior calling any oci_bindxxx() calls.

**Comment by FladoToo** [comment]
I've had that problem (with OCCI) and ended up binding by position. It's ugly and somewhat dangerous, when a bind variable occurs many times in the SQL statement, but I couldn't find a way around it - no Oracle APIs (OCI, OCCI, DBMS_SQL) supplied that information (not even the number of variables in the statement!) at the time.

**Comment by gmxyb** [comment]
Now, I test variable name is ok or not :
If call oci_bindxxx() return FALSE and OCI_ErrorGetOCICode is 1036 (ORA-01036 illegal variable name/number).

**Comment by vrogier** [comment]
What is the question?

**Comment by gmxyb** [comment]
No question... I mean I can only do that.

Thanks you for answering patiently.
