### ISSUE TITLE
Can't bind a Raw value

### ISSUE THREAD

**Issue by LukasWoodtli** [vrogier/ocilib#169]
I try to bind a raw vriable to a statement. Like this:
```
void executeStmt(Raw &rawId, Connection &con) {
	Statement st(con);

	st.Prepare("select * from my_table where id = values(:id)");

	st.Bind(ostring(":id"), rawId, BindInfo::In);
	st.ExecutePrepared();

	// ...
}
```

But then I get a linker error:
`undefined symbol: void ocilib::Statement::Bind<unsigned char>(std::string const&, std::vector<unsigned char, std::allocator<unsigned char> >&, ocilib::Enum<ocilib::BindInfo::BindDirectionValues>)`

What's the right way to bind a single variable (without creating a db type)?

Thanks!

**Comment by vrogier** [comment]
Hi,

The ocili::statement::bind() overload for ocilib::raw type is:

,```c++
template<>
inline void Statement::Bind<Raw, unsigned int>(const ostring& name, Raw &value, unsigned int maxSize, BindInfo::BindDirection mode);
```

You need to provide 'maxSize' argument (for limiting the size of the internal buffer passed to oracle client)

Best regards,

Vincent
