### ISSUE TITLE
Binding a std::string is not working correctly

### ISSUE THREAD

**Issue by maxsenft** [vrogier/ocilib#171]
I am trying to execute a SELECT statement with one single string parameter. Here's a code snippet:

    std::string tmpSQLCommandString = "SELECT * FROM table1 WHERE col1=:par1";
    
    ocilib::Statement stmt(conn);
    stmt.Prepare(tmpSQLCommandString);
    stmt.SetBindMode(ocilib::Statement::BindByName);

    for (CommandValueList::CommandValueListKeys::iterator tmpParameterNamesIt = tmpParameterNames.begin(); tmpParameterNamesIt != tmpParameterNames.end(); ++tmpParameterNamesIt)
    {
        std::string tmpParameterName = *tmpParameterNamesIt;
        
        switch (command.GetParameterType(tmpParameterName)) {
            case ValueTypeString:
            {
                std::string tmpValue = command.GetParameterAsString(tmpParameterName);
                stmt.Bind(tmpParameterName, tmpValue, 0u, ocilib::BindInfo::In);
                
                break;
            }
            ...
        }
    }
    
    stmt.ExecutePrepared();

When I trace through `ExecutePrepared()` I noticed unexpected behaviour in function

    template<class T>
    void BindObjectAdaptor<T>::SetInData()
    {
        if (GetMode() & OCI_BDM_IN)
        {
            size_t size = _object.size();

            if (size > _size)
            {
                size = _size;
            }

            if (size > 0)
            {
                memcpy(_data, &_object[0], size * sizeof(NativeType));
            }

            _data[size] = 0;
        }
    }

in ocilib_impl.hpp (line 4704): `GetMode() & OCI_BDM_IN` returns true, but `_object.size()` returns 0 although `_object` is "myvalue" and identifies as `std::string` by the debugger. FYI: `_size` is 5.

If I manually set `size` to 5, the code runs through, the Oracle statement gets executed and returns the resultset that is expected. If I do not manually set `size`, I do not get any results...

What am I doing wrong?

Edit 1: I'm using ocilib-4.5.1
Edit 2: Correct code snippet - found out it's a problem with local variables ...

**Comment by vrogier** [comment]
Hi,

Sorry for late response!
I was away on vacations and then back to work extremely busy.
I will check your case this evening and let you know about my investigations.

Best regards,

Vincent

**Comment by maxsenft** [comment]
Well, as I've written in my second edit, I found out that using local (temporary) strings caused the problem. I now added a vector in which I will store the strings that are used by ocilib. In my opinion it is a workaround but well, it works for now. It would be way more convenient if ocilib would take care of that by itself...

**Comment by vrogier** [comment]
Hi,

Sorry I didn't see the edit. Yes, the issue was caused by using temporary variables.

When you think about the binding workflow (which is passing a host variable to provide or receive data from Oracle Client), binded hosted variable scope must at least be the one between bending and executing time.  Doing otherwise would be like allocating a pointer, deallocating it and using it dangling value.

About your last comment, how can you have a lib "taking care of that by itself" when the scope and life cycle of the variable holding the value is not under the lib control. The only way to do so is to only use values and performs copys all the times. Which is the worse thing a library like ocilib could do !
The C API does not performs any copies (unless conversion is needed) :)

Regards,

Vincent

**Comment by maxsenft** [comment]
Hi,

fair enough saying that a library like ocilib should not make any copies. But I would at least be greatful for an remark in the documentation. ;-)
The argument "value" being a reference of type T might - of course - light up some doubts but it's not 100% clear what actually happens with the data inside the library (or did I miss some remark about that?).

Does every variable have to be existing throughout the statement execution? Or does this only apply to non-primitive types?

Regards
Max
