### ISSUE TITLE
OCI_BindStatement + OCI_BAM_INTERNAL = crash

### ISSUE THREAD

**Issue by DerWeiseScheuch** [vrogier/ocilib#172]
Given a slightly modified example from the ocilib example code:
```
    OCI_Prepare(st, "begin open :c for select 42 from dual; end;");
    OCI_SetBindAllocation(st, OCI_BAM_INTERNAL);  // ***problem***
    OCI_Statement* st2 = OCI_StatementCreate(cn);
    OCI_BindStatement(st, ":c", st2); // returns true
    OCI_Execute(st); // crash
```
Without  OCI_SetBindAllocation OCI_Execute works fine.
Documentation of OCI_BindStatement says
> parameter 'data' CANNOT be NULL whatever the statement bind allocation mode

Sounds to me that OCI_BindStatement should also work in conjunction with OCI_BAM_INTERNAL?
That would be highly desirable in case I need additional parameters like so:

`OCI_Prepare(st, "begin open :c for select :a_param from dual; end;");`

**Comment by vrogier** [comment]
Hi,

from documentation section ["Binding variables and arrays"](http://vrogier.github.io/ocilib/doc/html/group___ocilib_c_api_binding.html), 


> **Internal Bind allocation mode**
> Bind variables or arrays can be internally allocated by OCILIB. That means that instead of allocating variables or arrays on the stack/heap in the user program, bind contents can be allocated internally and thus :
> 
> minimize the amount of program variables
> optimize internal memory management for arrays
> To do so :
> 
> Call OCI_SetBindAllocation() with the mode OCI_BAM_INTERNAL
> pass a NULL variable or array to OCI_BindXXX() calls
> Retrieve the bind content allocated by OCILIB with OCI_BindGetData()
> Internal Bind allocation mode IS compatible with ALL array binding OCI_BindArrayOfxxx() methods.
> 
> Internal Bind allocation mode IS NOT compatible with some single variable bind calls :
> 
> OCI_BindTimestamp()
> OCI_BindInterval()
> OCI_BindLob()
> OCI_BindFile()
> OCI_BindObject()
> OCI_BindColl()
> OCI_BindRef()
> **OCI_BindStatement()**
> OCI_BindLong()
> These methods need to know the data sub type (like OCI_CLOB/OCI_BLOB for lobs) in order to internally create variables. As these methods prototypes are not passing the sub type, calling them with the statement bind mode set to OCI_BAM_INTERNAL will raise an OCILIB error of type OCI_ERR_NULL_POINTER


Thus binding OCI_Statement when bind allocation is OCI_BAM_INTERNAL is not supported.
You're not supposed to pass a non null pointer when OCI_BAL_INTERNAL is used.
it is like passing a null pointer to strlen().

What you are trying to do is not supported  and thus, in the library spirit, shall be fordidden.
In next OCIIB release, I will:
* udpate the documentation to make it clearer and remove any ambiguity
* make sure that when OCI_BAM_INTERNAL is set , passing a valid pointer will result in a error and not a crash.

Best regards,

Vincent

**Comment by DerWeiseScheuch** [comment]
Vincent,
thanks for clarification - I have to use OCI_BAM_EXTERNAL in case I need do bind to a SYS_REFCURSOR.

Regards,
Thomas.

**Comment by vrogier** [comment]
Hi,

I've added for v4.5.2  a new exception OCI_ERR_BIND_EXTERNAL_NOT_ALLOWED in bind calls preventing from passing a non null host variable pointer when bind allocation mode is OCI_BAM_INTERNAL.

Documentation will also bee updated.

Best regards,
