### ISSUE TITLE
OCI_SubscriptionAddStatement hangs on IOT

### ISSUE THREAD

**Issue by DerWeiseScheuch** [vrogier/ocilib#173]
I register for database change notifications like so:

```
OCI_Initialize(err_handler, NULL, OCI_ENV_THREADED | OCI_ENV_EVENTS);
auto sub = OCI_SubscriptionRegister(con, "mydb", OCI_CNT_OBJECTS, event_handler, 0, 0);
OCI_Prepare(stmt, "select * from mytable");
OCI_SubscriptionAddStatement(sub, stmt);
```

Everything works fine - unless mytable is an IOT (index organized table).
In that case OCI_SubscriptionAddStatement seems to hang.
If a recreate "mytable" as an "ordinary" table, it works.

I wonder if this problem is an ocilib issue or caused by Oracle itself.
I didn't find hints in Oracle's documentation ( [https://docs.oracle.com/cd/B19306_01/B14251_01/adfns_dcn.htm](url))
that IOTs aren't allowed for notifications?

**Comment by vrogier** [comment]
Hi,

I have never tried subscriptions with IOT table.
Can you send me sample code that I can test and debug?
I will try to reproduce the issue this evening.

Thanks

Vincent

**Comment by DerWeiseScheuch** [comment]
Essentially the main aspects of the example is in the original post. Initialize, connect (not shown), register for notifications.

If mytable is created as an IOT:

```
CREATE TABLE mytable
(
  SEQ_ID  INTEGER, 
  NNW_ID  INTEGER,
  PRIMARY KEY (SEQ_ID)
) ORGANIZATION INDEX;
```

OCI_SubscriptionAddStatement call doesn't return.

In case of 

```
CREATE TABLE mytable
(
  SEQ_ID  INTEGER, 
  NNW_ID  INTEGER,
  PRIMARY KEY (SEQ_ID)
);
```

(without ORGANIZATION INDEX ) it works.
Luckily I could switch mytable to non-IOT - so I haven't problems with that table any more.
Anyway, it would be interesting to know why this happens.
My database version is "Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production"

**Comment by vrogier** [comment]
I've just tested with a 12.1.0.2.0 server and client and it works like a charm.

**Comment by DerWeiseScheuch** [comment]
Good and bad to know;-) Unfortunately I couldn't post all intermediate steps (connect, statement creation ...) since that code is embedded in further C++ classes. Could you send your test code? Then I would verify it against my local instance and a couple of production database(s) tomorrow. Maybe something is wrong with my local Windows instance! Who knows. 
If it works we can close that issue as an isolated problem of a single user :-)

**Comment by vrogier** [comment]
my test code is just a main() with the code you have provided and the event_handler() from ocilib demo file notification.c

**Comment by DerWeiseScheuch** [comment]
I tried to extract the production scenario (multiple connection pools, notification subscriptions occur in different threads etc.) into a simpler test case as close as I could get, but failed. In that "stripped" environment it works like a charme too. Nevertheless I still can reproduce the IOT difference in the full blown live application. Anyway - it's more than uncertain if ocilib causes that behaviour.
Thats why I suggest to close the issue. In case I'll be able to reproduce and show it one day, I'll open a new ticket. Thanks.

**Comment by vrogier** [comment]
Closing as suggested by OP. probably not an ocilib related issue.
