### ISSUE TITLE
Help with Oracle sessions

### ISSUE THREAD

**Issue by J-Gaeta** [vrogier/ocilib#177]
Hi, I trying to replace some existing code written using OO4O
The code creates an osession instance and starts a transaction and commits the transaction at the end.
Would this be similar to using the Transaction object in OCILIB? How would I commit the session?

Thank you

John Gaeta

	OSession session = GetSession();
	oresult res = session.BeginTransaction();

	if (res != OSUCCESS)
	{
		CString errStr = session.GetServerErrorText();
		ThrowWpException(1102, _T("WpNFMDatabase"), errStr);	//1102=error starting transaction 
	}
	
	//run a stored proc...
	
	OSession session = GetSession();
	oresult res = session.Commit();

	if (res != OSUCCESS)
	{
		CString errStr = session.GetServerErrorText();
		ThrowWpException(1103, _T("WpNFMDatabase"), errStr);	//1103=error during commit 
	}

**Comment by vrogier** [comment]
Hi,

If you do not want to create OCI_Transaction objects explicitly, you can just use OCI_Commit() whenever you need to commit. Otherwise if you want to discard stuff, call OCI_Rollback().

Regards,

Vincent

**Comment by J-Gaeta** [comment]
Thanks Vincent

I was doing that but wasn't sure of the use of sessions. I will continue as you suggested

Cheers

John
