### ISSUE TITLE
Help with using Collections in a stored proc

### ISSUE THREAD

**Issue by J-Gaeta** [vrogier/ocilib#178]
Hi I have a number of stored procs which contain arrays in the parameters. To make things easier I would like to use a Collection as the parameter.

I'm a little confused with the structure / use of Collection and I'm getting the following error

 ORA-00931: Missing Identifier

This is how I'm declaring it

Collection<ostring> attribIdArray(TypeInfo(con, "VARCHAR2", TypeInfo::Type));

The error occurs after I step over this.

The collection is for the p_Attrib_Id parameter in the stored proc header below

Thank you for your assistance.

Cheers

John 

  PROCEDURE Modify (
    p_Slot_SUN               IN        wp_domain.TS_Slot_SUN,               --
    p_Slot_Type_Cd              OUT    wp_domain.TS_Slot_Type_Cd,           --
    p_Slot_No                IN OUT    wp_domain.TS_Slot_No,                --
    p_Compnt_Classn_Id       IN        wp_domain.TS_Compnt_Classn_Id,       --
    p_Slot_Status_Cd         IN OUT    wp_domain.TS_Slot_Status_Cd,         --
    p_Slot_Alias             IN OUT    wp_domain.TS_Slot_Alias,             --
    p_Dest_Label_Tx          IN        wp_domain.TS_Dest_Label_Tx,          --
    p_Slot_SysLock              OUT    wp_domain.TS_SysLock,                --
    p_Site_SUN               IN        wp_domain.TS_Site_SUN,               --
    p_Parent_Slot_SUN        IN        wp_domain.TS_Parent_Slot_SUN,        --
    p_Recursive              IN OUT    VARCHAR2,                            -- ?????
    p_row_status_cd          IN        wp_domain.TS_Row_status_cd,          -- Deprecated. Always set to constant value as specified in wp_constant
    p_Ntwrk_Point_SUN        IN        wp_domain.TS_Ntwrk_Point_SUN,        -- The reference to the spatial point for the slot
    p_Mapping_Symbol_Cd      IN        wp_domain.TS_Mapping_Symbol_Cd,      --
    p_Symbol_Rotn_Val        IN        wp_domain.TS_Symbol_Rotn_Val,        --
    p_Asmbly_Templt_SUN      IN        wp_domain.TS_Asmbly_Templt_SUN,      -- The reference to the template that was used to creat the slot
    p_Reason_Code_Val        IN        wp_domain.TEvent_Reason_Code_Val,    -- Deprecated by NFM 1.6 prop_change mechanism
    p_Event_Dt               IN OUT    wp_domain.TEvent_Event_Dt,           -- Deprecated by NFM 1.6 prop_change mechanism
    p_Event_Note_Tx          IN        wp_domain.TEvent_Event_Note_Tx,      -- Deprecated by NFM 1.6 prop_change mechanism
    p_Event_SUN                 OUT    wp_domain.TEvent_Event_SUN,          -- Deprecated by NFM 1.6 prop_change mechanism
    p_Event_Syslock             OUT    wp_domain.TEvent_Syslock,            -- Deprecated by NFM 1.6 prop_change mechanism
    p_Works_Order_Id         IN        wp_domain.TWOrder_works_order_id,    -- Deprecated by NFM 1.6 prop_change mechanism
    p_Plant_Item_Id          IN        wp_domain.TPl_Plant_Item_Id,         -- The plant item to be installed in the slot
    p_Spec_SUN               IN        wp_domain.TSP_Spec_SUN,              -- The spec to be installed in the slot
    p_Spec_Changed           IN        VARCHAR2,
    p_Slot_Normal_Swtchd_Sts IN        wp_domain.TS_Slot_Normal_Swtchd_Sts, --
    p_Display_Seq_No         IN        NUMBER,                              --
    p_Attrib_Ct              IN        NUMBER,                              -- The number of attributes in the array
    p_Attrib_Id              IN        NFM_Mntatts.Tbl_Attrib_Id,           --
    p_Attrib_Val             IN        NFM_Mntatts.Tbl_Attrib_Val,          --
    p_Compnt_Attrib_Sun      IN        NFM_Mntatts.Tbl_Compnt_Attrib_SUN,
    p_LCC_Code               IN        VARCHAR2,
    p_Install_Date           IN        DATE,
    p_Install_Date_Override  IN        VARCHAR2
  );

**Comment by vrogier** [comment]
Hi,

The issue has been investigating and we exchanged with the OP by email about it.

It appears that the stored proc as a parameter that is a package defined indexed by table.
such PL/SQL types are only supported for binding in OCI since Oracle 12c that allowed using PL/SQL records, types and boolean in OCI).
Prior to Oracle 12c, only nested tables and varrays can be binded to host variable using OCI.

Unfortunately, the OP has an 11g server accessed by a 12C client.

As Oracle 12c is required on both side (client and server) to bind a package defined type, tthe only options left are:
* change the procedure signature and use a different type (nested table OR varray) that are supported by OCI since Oracle 8i
* use a anonymous PL/SQL block that wrap the procedure call and map the index by table to a nested table or varray

Best regards,

Vincent

**Comment by vrogier** [comment]
Can you post your C++ code sample ?

**Comment by J-Gaeta** [comment]
Hi Vince,

Did you get a chance to check this?

Cheers

John Gaeta

From: GAETA John (SPARQ)
Sent: Thursday, 18 October 2018 4:26 PM
To: 'vrogier/ocilib'; vrogier/ocilib
Cc: Author
Subject: RE: [vrogier/ocilib] Help with using Collections in a stored proc (#178)

C++ code sample as requested

This worked using OCI_BindArrayOfStrings

                Statement st(con);
                ostring sql = ostring("Begin wp_slot.Modify_Associative  (:p01, :p02); End;");
                st.Prepare(sql);

                otext tab_str[4][254];

                int arrayNum = 4;
                st.Bind(":p01", arrayNum, BindInfo::In);
                strcpy(tab_str[0], "POLE - SPECIES");
                strcpy(tab_str[1], "6 SIGMA");
                strcpy(tab_str[2], "POLE - OWNER");
                strcpy(tab_str[3], "POLE - FOUNDN");
                OCI_BindArrayOfStrings(st, OTEXT(":p02"), (otext*)tab_str, 254, 4);
                st.ExecutePrepared();

Using vector bind didn’t work

                Statement st(con);
                ostring sql = ostring("Begin wp_slot.Modify_Associative  (:p01, :p02); End;");
                st.Prepare(sql);

                int arrayNum = 4;
                std::vector<ostring> attribIdArray;
                attribIdArray.push_back("POLE - SPECIES");
                attribIdArray.push_back("6 SIGMA");
                attribIdArray.push_back("POLE - OWNER");
                attribIdArray.push_back("POLE - FOUNDN");

                st.Bind(":p01", arrayNum, BindInfo::In);
                st.Bind(":p02", attribIdArray, 254, BindInfo::In);
                st.ExecutePrepared();

"Oracle Error => ORA-06550: line 1, column 7:\nPLS-00306: wrong number or types of arguments in call to 'MODIFY_ASSOCIATIVE'\nORA-06550: line 1, column 7:\nPL/SQL: Statement ignored\n"

Stored proc parameter for the array was

TYPE Associative_Array IS TABLE OF VARCHAR2(255)
INDEX BY BINARY_INTEGER;

**Comment by vrogier** [comment]
Hi,

I've created issue #182 about it. 
C++ API was able to bind vectors for regular array DML operation but not for PL/SQL tables.
The fix is committed on branch v4.6.0 (should be released next week).
As C++ is header only, you can retrieve ocilib.hpp and ocilib_impl.hpp from branch 'develop-4.6.0'

Best regards,

Vincent

**Comment by J-Gaeta** [comment]
Thanks Vincent, I’m looking forward to the new version.

**Comment by J-Gaeta** [comment]
Hi Vincent,

Will 4.6.0 be available soon?

Cheers

John

From: GAETA John (SPARQ)
Sent: Friday, 26 October 2018 11:08 AM
To: 'vrogier/ocilib'
Subject: RE: [vrogier/ocilib] Help with using Collections in a stored proc (#178)

Thanks Vincent, I’m looking forward to the new version.

**Comment by vrogier** [comment]
Hi,

Unfortunately, I was unable to publish v4.6.0 as planned last week.

I am currently away for few days.

I have already modified v4.6 .0 milestone release date to November 22nd.

Sorry for the delay.

Regards,

Vincent

**Comment by J-Gaeta** [comment]
Hi Vincent,

Is this still scheduled for the 22nd Nov?

Cheers

John Gaeta

**Comment by vrogier** [comment]
Hi,

Yes it is :)
I expect to create the release this evening (France timezone).

Regards,

Vincent

**Comment by J-Gaeta** [comment]
Thanks Vincent,

I see it there now. I will update this and let you know how I go.

Cheers

John

**Comment by J-Gaeta** [comment]
Hi Vince,

Sadly I am getting the same error

I have updated to version 4.6.0 and am still getting the same error as before.

              Statement st(con);
              ostring sql = ostring("Begin wp_slot.Modify_Associative (:p01, :p02); End;");
              st.Prepare(sql); int arrayNum = 4;
              std::vector<ostring> attribIdArray;
              attribIdArray.push_back(ostring("POLE - SPECIES"));
              attribIdArray.push_back(ostring("6 SIGMA"));
              attribIdArray.push_back(ostring("POLE - OWNER"));
              attribIdArray.push_back(ostring("POLE - FOUNDN"));
              st.Bind(ostring(":p01"), arrayNum, BindInfo::In);
              st.Bind(ostring(":p02"), attribIdArray, 254, BindInfo::In);
              st.ExecutePrepared();


"Oracle Error => ORA-06550: line 1, column 7:\nPLS-00306: wrong number or types of arguments in call to 'MODIFY_ASSOCIATIVE'\nORA-06550: line 1, column 7:\nPL/SQL: Statement ignored\n"

As I mentioned before OCI_BindArrayOfStrings works with the same stored proc. Can you see anything I’m doing wrong?

Stored proc I am calling…


TYPE Associative_Array IS TABLE OF VARCHAR2(255) INDEX BY BINARY_INTEGER;


PROCEDURE Modify_Associative (                              --
    p_Attrib_Ct              IN        NUMBER,                              -- The number of attributes in the array
    p_Attrib_Id              IN        wp_slot.Associative_Array
  )
IS
ctr INTEGER;
BEGIN

  FOR ctr IN 1..p_Attrib_Ct LOOP
    LogMessage('p_Attrib_Id(' || ctr || '):' || p_Attrib_Id(ctr)) ;
  END LOOP;

  LogMessage('Associative_Array');

END;





From: GAETA John (SPARQ)
Sent: Friday, 23 November 2018 8:13 AM
To: 'vrogier/ocilib'; vrogier/ocilib; vincent rogier (vince.rogier@gmail.com)
Cc: Author
Subject: RE: [vrogier/ocilib] Help with using Collections in a stored proc (#178)

Thanks Vincent,

I see it there now. I will update this and let you know how I go.

Cheers

John

**Comment by J-Gaeta** [comment]
Hi Vincent,

Just check if you have had time to check this.

Cheers

John

From: GAETA John (SPARQ)
Sent: Friday, 23 November 2018 12:24 PM
To: 'vrogier/ocilib'; 'vrogier/ocilib'; vincent rogier (vince.rogier@gmail.com)
Cc: 'Author'
Subject: RE: [vrogier/ocilib] Help with using Collections in a stored proc (#178)

Hi Vincent,

Just a follow up

I tested using  vector<Number> this didn’t return an error but the stored proc did not run.

Cheers

John

From: GAETA John (SPARQ)
Sent: Friday, 23 November 2018 11:33 AM
To: 'vrogier/ocilib'; 'vrogier/ocilib'; vincent rogier (vince.rogier@gmail.com)
Cc: 'Author'
Subject: RE: [vrogier/ocilib] Help with using Collections in a stored proc (#178)

Hi Vince,

Sadly I am getting the same error

I have updated to version 4.6.0 and am still getting the same error as before.

              Statement st(con);
              ostring sql = ostring("Begin wp_slot.Modify_Associative (:p01, :p02); End;");
              st.Prepare(sql); int arrayNum = 4;
              std::vector<ostring> attribIdArray;
              attribIdArray.push_back(ostring("POLE - SPECIES"));
              attribIdArray.push_back(ostring("6 SIGMA"));
              attribIdArray.push_back(ostring("POLE - OWNER"));
              attribIdArray.push_back(ostring("POLE - FOUNDN"));
              st.Bind(ostring(":p01"), arrayNum, BindInfo::In);
              st.Bind(ostring(":p02"), attribIdArray, 254, BindInfo::In);
              st.ExecutePrepared();


"Oracle Error => ORA-06550: line 1, column 7:\nPLS-00306: wrong number or types of arguments in call to 'MODIFY_ASSOCIATIVE'\nORA-06550: line 1, column 7:\nPL/SQL: Statement ignored\n"

As I mentioned before OCI_BindArrayOfStrings works with the same stored proc. Can you see anything I’m doing wrong?

Stored proc I am calling…


TYPE Associative_Array IS TABLE OF VARCHAR2(255) INDEX BY BINARY_INTEGER;


PROCEDURE Modify_Associative (                              --
    p_Attrib_Ct              IN        NUMBER,                              -- The number of attributes in the array
    p_Attrib_Id              IN        wp_slot.Associative_Array
  )
IS
ctr INTEGER;
BEGIN

  FOR ctr IN 1..p_Attrib_Ct LOOP
    LogMessage('p_Attrib_Id(' || ctr || '):' || p_Attrib_Id(ctr)) ;
  END LOOP;

  LogMessage('Associative_Array');

END;





From: GAETA John (SPARQ)
Sent: Friday, 23 November 2018 8:13 AM
To: 'vrogier/ocilib'; vrogier/ocilib; vincent rogier (vince.rogier@gmail.com)
Cc: Author
Subject: RE: [vrogier/ocilib] Help with using Collections in a stored proc (#178)

Thanks Vincent,

I see it there now. I will update this and let you know how I go.

Cheers

John

**Comment by J-Gaeta** [comment]
Hi Vincent,

I was hoping to use the OCILIB vector fix in my current project. Do you see this as being looked at soon or will this be some time in future?

If not soon I will release using  OCI_BindArrayOfStrings and OCI_BindArrayOfNumbers.

Would you please confirm when this is scheduled to be checked?

Regards

John Gaeta

From: GAETA John (SPARQ)
Sent: Thursday, 29 November 2018 11:10 AM
To: 'vrogier/ocilib'; 'vrogier/ocilib'; vincent rogier (vince.rogier@gmail.com)
Cc: 'Author'
Subject: RE: [vrogier/ocilib] Help with using Collections in a stored proc (#178)

Hi Vincent,

Just check if you have had time to check this.

Cheers

John

From: GAETA John (SPARQ)
Sent: Friday, 23 November 2018 12:24 PM
To: 'vrogier/ocilib'; 'vrogier/ocilib'; vincent rogier (vince.rogier@gmail.com)
Cc: 'Author'
Subject: RE: [vrogier/ocilib] Help with using Collections in a stored proc (#178)

Hi Vincent,

Just a follow up

I tested using  vector<Number> this didn’t return an error but the stored proc did not run.

Cheers

John

From: GAETA John (SPARQ)
Sent: Friday, 23 November 2018 11:33 AM
To: 'vrogier/ocilib'; 'vrogier/ocilib'; vincent rogier (vince.rogier@gmail.com)
Cc: 'Author'
Subject: RE: [vrogier/ocilib] Help with using Collections in a stored proc (#178)

Hi Vince,

Sadly I am getting the same error

I have updated to version 4.6.0 and am still getting the same error as before.

              Statement st(con);
              ostring sql = ostring("Begin wp_slot.Modify_Associative (:p01, :p02); End;");
              st.Prepare(sql); int arrayNum = 4;
              std::vector<ostring> attribIdArray;
              attribIdArray.push_back(ostring("POLE - SPECIES"));
              attribIdArray.push_back(ostring("6 SIGMA"));
              attribIdArray.push_back(ostring("POLE - OWNER"));
              attribIdArray.push_back(ostring("POLE - FOUNDN"));
              st.Bind(ostring(":p01"), arrayNum, BindInfo::In);
              st.Bind(ostring(":p02"), attribIdArray, 254, BindInfo::In);
              st.ExecutePrepared();


"Oracle Error => ORA-06550: line 1, column 7:\nPLS-00306: wrong number or types of arguments in call to 'MODIFY_ASSOCIATIVE'\nORA-06550: line 1, column 7:\nPL/SQL: Statement ignored\n"

As I mentioned before OCI_BindArrayOfStrings works with the same stored proc. Can you see anything I’m doing wrong?

Stored proc I am calling…


TYPE Associative_Array IS TABLE OF VARCHAR2(255) INDEX BY BINARY_INTEGER;


PROCEDURE Modify_Associative (                              --
    p_Attrib_Ct              IN        NUMBER,                              -- The number of attributes in the array
    p_Attrib_Id              IN        wp_slot.Associative_Array
  )
IS
ctr INTEGER;
BEGIN

  FOR ctr IN 1..p_Attrib_Ct LOOP
    LogMessage('p_Attrib_Id(' || ctr || '):' || p_Attrib_Id(ctr)) ;
  END LOOP;

  LogMessage('Associative_Array');

END;





From: GAETA John (SPARQ)
Sent: Friday, 23 November 2018 8:13 AM
To: 'vrogier/ocilib'; vrogier/ocilib; vincent rogier (vince.rogier@gmail.com)
Cc: Author
Subject: RE: [vrogier/ocilib] Help with using Collections in a stored proc (#178)

Thanks Vincent,

I see it there now. I will update this and let you know how I go.

Cheers

John

**Comment by vrogier** [comment]
To make it work, you need to use the flag added in 4.6.0 !

     `       st.Bind(ostring(":p02"), attribIdArray, 254, BindInfo::In, BindInfo::AsPlSqlTable);`


Regards,

Vincent

**Comment by J-Gaeta** [comment]
Hi Vincent

This is still not working for me. It no longer returns any error message or throw any exceptions but it doesn’t run the stored proc see below. It doesn’t even hit the first line which sends a simple message to a log table. I have tried / tested for both vector<Number> and vector<ostring>.

As I mentioned before OCI_BindArrayOfStrings and OCI_BindArrayOfNumbers works.

Regards

John Gaeta

              ostring sql = ostring("Begin wp_slot.Modify_Associative (:p01, :p02); End;");
              st.Prepare(sql);

              Number arrayNum = 4;
              //std::vector<Number> attribIdArray;
              std::vector<ostring> attribIdArray;
              attribIdArray.push_back(ostring("1.3"));
              attribIdArray.push_back(ostring("3.6"));
              attribIdArray.push_back(ostring("100"));
              attribIdArray.push_back(ostring("200"));
              st.Bind(ostring(":p01"), arrayNum, BindInfo::In);
//            st.Bind(ostring(":p02"), attribIdArray, BindInfo::In, BindInfo::AsPlSqlTable);
              st.Bind(ostring(":p02"), attribIdArray, 254, BindInfo::In, BindInfo::AsPlSqlTable);
              st.ExecutePrepared();


--TYPE Associative_Array IS TABLE OF NUMBER(5,1)
--        INDEX BY BINARY_INTEGER;
TYPE Associative_Array IS TABLE OF VARCHAR2(255)
        INDEX BY BINARY_INTEGER;


PROCEDURE Modify_Associative (                              --
    p_Attrib_Ct              IN        NUMBER,                              -- The number of attributes in the array
    p_Attrib_Id              IN OUT       wp_slot.Associative_Array
  )
IS
ctr INTEGER;
BEGIN
  LogMessage('Associative_Array');

  FOR ctr IN 1..p_Attrib_Ct LOOP
    LogMessage('p_Attrib_Id(' || ctr || '):' || to_char(p_Attrib_Id(ctr))) ;
    p_Attrib_Id(ctr) := ctr;
  END LOOP;

  LogMessage('Associative_Array');

END;

**Comment by vrogier** [comment]
Hi,

In fact, the previous fix allowed the vector data being passed to Oracle Client.
But only the content of 1st element of the vector was passed to Oracle.
I've just committed a fix on a new branch develop-4.6.1.

using this PL/SQL:

```SQL
CREATE OR REPLACE PACKAGE WP_SLOT AS 

TYPE Associative_Array IS TABLE OF VARCHAR2(255) INDEX BY BINARY_INTEGER;

END WP_SLOT; 
/ 

CREATE OR REPLACE  PROCEDURE Modify_Associative 
(     
    p_Attrib_Ct              IN        NUMBER, 
    p_Attrib_Id              IN        WP_SLOT.Associative_Array
  )
 IS
ctr INTEGER;
BEGIN

  FOR ctr IN 1..p_Attrib_Ct LOOP
    DBMS_OUTPUT.PUT_LINE('p_Attrib_Id(' || ctr || '):' || p_Attrib_Id(ctr)) ;
  END LOOP;

  DBMS_OUTPUT.PUT_LINE('Associative_Array');

END;
/
```

And following code:

```C++
            con.EnableServerOutput(10000, 10, 200);
            ostring sql = ostring("Begin Modify_Associative (:p01, :p02); End;");
            st.Prepare(sql); int arrayNum = 4;
            std::vector<ostring> attribIdArray;
            attribIdArray.push_back(ostring("POLE - SPECIES"));
            attribIdArray.push_back(ostring("6 SIGMA"));
            attribIdArray.push_back(ostring("POLE - OWNER"));
            attribIdArray.push_back(ostring("POLE - FOUNDN"));
            st.Bind(ostring(":p01"), arrayNum, BindInfo::In);
            st.Bind(ostring(":p02"), attribIdArray, 254, BindInfo::In, BindInfo::AsPlSqlTable);
            st.ExecutePrepared();

            std::string line;
            while (con.GetServerOutput(line))
            {
                ocout << line << oendl;
            }
```

Gives the following expected output:

```
p_Attrib_Id(1):POLE - SPECIES
p_Attrib_Id(2):6 SIGMA
p_Attrib_Id(3):POLE - OWNER
p_Attrib_Id(4):POLE - FOUNDN
Associative_Array
```

you can  retrieve the 3  hpp files in ocilib/include from the 4.6.1 branch for testing.

I will make a release shortly.

Best regards,

Vincent.

**Comment by J-Gaeta** [comment]
Thanks Vincent,

I have retrieved the 3 hpp files in ocilib/include from the 4.6.1 branch. I now get the following compile / link error

error LNK2005: "public: unsigned int __cdecl ocilib::BindArray::GetSize(void)" (?GetSize@BindArray@ocilib@@QEAAIXZ) already defined in wpautocad.obj
error LNK2005: "public: unsigned int __cdecl ocilib::BindArray::GetSizeForBindCall(void)" (?GetSizeForBindCall@BindArray@ocilib@@QEAAIXZ) already defined in wpautocad.obj

I have a class that inherits from ocilib::Connection

Am I doing something wrong?

Regards

John

**Comment by vrogier** [comment]
Hi,

I've forgotten the keyword 'inline' on the 2 newly added methods in
previous commit.
I've just committed the change on the 4.6.1 branch.
Get again ocilib_impl.hpp file.

Regards


Vincent

**Comment by J-Gaeta** [comment]
Thanks, that makes sense.

I will try again

Regards

John

**Comment by J-Gaeta** [comment]
Compiled ok, I will test tomorrow morning.

Regards

john

From: GAETA John (SPARQ)
Sent: Wednesday, 12 December 2018 3:41 PM
To: 'vrogier/ocilib'; vrogier/ocilib
Cc: Author
Subject: RE: [vrogier/ocilib] Help with using Collections in a stored proc (#178)

Thanks, that makes sense.

I will try again

Regards

John

**Comment by J-Gaeta** [comment]
Hi Vincent,

The vector binding for BindInfo::In is working now but I am getting some peculiar results using out direction (BindInfo::InOut).

For “Number” the vector appears to retain the IN values

For “VARCHAR2” I only get 1 char returned.

Would you please test BindInfo::InOut / BindInfo::Out for Number and VARCHAR2 to see what you get.

Regards

John Gaeta

**Comment by vrogier** [comment]
Hi,

Regarding the vector<ostring>, I have created the issue #189  an committed a fix for it in v4.6.1 branch (3016761)

For vector of numbers, I get the content of the vector updated as expected.

Regards,

Vincent

**Comment by J-Gaeta** [comment]
Hi Vincent,

This is still not working for both “Out” vector<ostring> and  vector<Number> binds

“In” vector binds are working.

For bind “Out” vector<ostring> it appears to get the first element returned from the stored proc, but each char of the returned string is spread over the vector see example below

Expected returned strings from stored proc

‘First’, ‘Second’, ‘Third’,  ‘Forth’

std::vector<ostring> attribIdArray;

attribIdArray[0] is ‘F’
attribIdArray[1] is ‘i’
attribIdArray[2] is ‘r’
attribIdArray[3] is ‘s’


For bind “Out” vector<Number>

Expected returned numbers from stored proc 311, 312, 313, 314

std::vector<Number> attribIdArray;

I get “Access violation reading location” when using

attribIdArray[0].ToString();


As before it works ok for OCI_BindArrayOfStrings and OCI_BindArrayOfNumbers.

Regards

John Gaeta

**Comment by J-Gaeta** [comment]
After further testing I found that for bind std::vector<Number> with bind direction BindInfo::InOut I would get the “Access violation reading location” error after calling ToString();

For bind std::vector<Number> with bind direction BindInfo::Out I didn’t get the “Access violation reading location” error after calling ToString() but the return values were NULL. I expected the values to be valid, similar to what was returned using OCI_BindArrayOfNumbers.

Regards

John Gaeta


From: GAETA John (SPARQ)
Sent: Monday, 17 December 2018 1:29 PM
To: 'vrogier/ocilib'; 'vrogier/ocilib'
Cc: 'Author'
Subject: RE: [vrogier/ocilib] Help with using Collections in a stored proc (#178)

Sorry Vincent,

Please ignore my previous email. I was still using the earlier version of ocilib_impl.hpp

After initial tests it appears that bind “Out” vector<ostring> is working.

I am still having issues with using Number::ToString () this is causing an “Access violation reading location” error

For bind “Out” vector<Number>

Expected returned numbers from stored proc 311, 312, 313, 314

std::vector<Number> attribIdArray;

I get “Access violation reading location” when using

attribIdArray[0].ToString();

I get the same error if I use:

Number valNum;
ostring val;
valNum = attribIdArray[0];
val = valNum.ToString();

I will continue testing…

Regards

John Gaeta



From: GAETA John (SPARQ)
Sent: Monday, 17 December 2018 12:12 PM
To: 'vrogier/ocilib'; vrogier/ocilib
Cc: Author
Subject: RE: [vrogier/ocilib] Help with using Collections in a stored proc (#178)

Hi Vincent,

This is still not working for both “Out” vector<ostring> and  vector<Number> binds

“In” vector binds are working.

For bind “Out” vector<ostring> it appears to get the first element returned from the stored proc, but each char of the returned string is spread over the vector see example below

Expected returned strings from stored proc

‘First’, ‘Second’, ‘Third’,  ‘Forth’

std::vector<ostring> attribIdArray;

attribIdArray[0] is ‘F’
attribIdArray[1] is ‘i’
attribIdArray[2] is ‘r’
attribIdArray[3] is ‘s’


For bind “Out” vector<Number>

Expected returned numbers from stored proc 311, 312, 313, 314

std::vector<Number> attribIdArray;

I get “Access violation reading location” when using

attribIdArray[0].ToString();


As before it works ok for OCI_BindArrayOfStrings and OCI_BindArrayOfNumbers.

Regards

John Gaeta

**Comment by vrogier** [comment]
Hi,

Problem investigated => Created issue #191 
Problem fixed => commit d34074f

Regards,

Vincent

**Comment by J-Gaeta** [comment]
Hi Vincent,

We are getting closer.

For bind std::vector<Number> with bind direction BindInfo::InOut this is now working

For bind std::vector<Number> with bind direction BindInfo::Out this returns values as NULL after calling ToString()

Should I be adding SetBindArraySize? If I do, I get the following error after st.ExecutePrepared()

“Unhandled exception at 0x000007FEB7E0E752 (orageneric12.dll) in acad.exe: 0xC0000005: Access violation reading location 0x000000000005C102.”

Also, if I don’t add the dummy values for the array (which is strange for  BindInfo::Out) I get the following error.

"ORA-06550: line 1, column 7:\nPLS-00306: wrong number or types of arguments in call to 'MODIFY_ASSOCIATIVE'\nORA-06550: line 1, column 7:\nPL/SQL: Statement ignored\n"

              Statement st(con);

              ostring sql = ostring("Begin wp_slot.Modify_Associative (:p01, :p02); End;");
              st.Prepare(sql);

              Number arrayNum(ostring("4"));
              std::vector<Number> attribIdArray;
              //st.SetBindArraySize(4);

              attribIdArray.push_back(ostring("101.3"));
              attribIdArray.push_back(ostring("7777"));
              attribIdArray.push_back(ostring("1001"));
              attribIdArray.push_back(ostring("2001"));

              ostring val;
              st.Bind(ostring(":p01"), arrayNum, BindInfo::In);

              st.Bind(ostring(":p02"), attribIdArray, BindInfo::Out, BindInfo::AsPlSqlTable);
              st.ExecutePrepared();

              Number valNum;
              for (int i = 0; i < attribIdArray.size(); i++)
              {
                     valNum = attribIdArray[i];
                     val = valNum.ToString();

              }

TYPE Associative_Array IS TABLE OF NUMBER(5,1)
       INDEX BY BINARY_INTEGER;


PROCEDURE Modify_Associative (                              --
    p_Attrib_Ct              IN        NUMBER,                              -- The number of attributes in the array
    p_Attrib_Id                 OUT    wp_slot.Associative_Array
  )
IS
ctr INTEGER;
BEGIN
  p_Attrib_Id(1) := 100;
  p_Attrib_Id(2) := 99.9;
  p_Attrib_Id(3) := 200;
  p_Attrib_Id(4) := 1000.3;
END;

**Comment by vrogier** [comment]
Hi,

Problem investigated => Created issue #192
Problem fixed => commit 710285e

Regards,

Vincent

**Comment by J-Gaeta** [comment]
Hi Vincent,

I’m now getting a compile error

Error      122         error C2039: 'Value' : is not a member of 'ocilib::NumericTypeResolver<T>'                c:\user\projects\ocilib\include\ocilib_impl.hpp 1866
Error      123         error C2065: 'Value' : undeclared identifier           c:\user\projects\ocilib\include\ocilib_impl.hpp 1866

Regards

John

**Comment by vrogier** [comment]
What is your visual studio version?

**Comment by vrogier** [comment]
The error occurs if T is not a supported numeric type by operator = (signed/unsigned short, int, big_int, float, double, Number).
If you try to assign something else like a string, you will get the error. I suspect that is what happens to you.
The error thus would be expected.
Use FromString() to assign a string.

Regards,

Vincent

**Comment by J-Gaeta** [comment]
Ok thanks, are you working late?

**Comment by J-Gaeta** [comment]
Hi Vince,

All is going well now, I would like to thank you for your help.

Regards

John Gaeta
