### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by ppanos** [vrogier/ocilib#18]
Greetings i have configured the library with
>./configure --with-oracle_home=/opt/oracle/instantclient --with-oracle_headers_path=/opt/oracle/instantclient/include  --with-oracle_lib_path=/opt/oracle/instantclient

everything goes ok but when i invoke make the following is returned

>configure.ac:24: the top level
configure:10484: error: possibly undefined macro: LT_MAJOR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
make: *** [configure] Error 1

I tried 

>autoreconf -fi

but the following is returned

>../libtool: line 478: CDPATH: command not found
libtool: Version mismatch error.  This is libtool 2.4.2 Debian-2.4.2-1.7ubuntu1, but the
libtool: definition of this LT_INIT comes from an older release.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.2 Debian-2.4.2-1.7ubuntu1
libtool: and run autoconf again.
make[2]: *** [libocilib_la-array.lo] Error 63

Thank you in advance.

**Comment by vrogier** [comment]
Hi,

Thanks for reporting issues :)
I will check this issue for next release.

Regards,

Vincent

**Comment by ecraven** [comment]
I have the same problem. I've tried my (very shallow) knowledge of autotools, but haven't succeeded in getting things to build... It would be nice if autoconf && ./configure ... && make could be used :)

**Comment by vrogier** [comment]
Hi,

It shall be now okay with latest commits (autotools updates).

Let me know if it is not the case.

Regards,

Vincent
