### ISSUE TITLE
Problem with utf-8 in LobNationalCharacter.

### ISSUE THREAD

**Issue by stan-yu** [vrogier/ocilib#181]
Function Lob<ostring, LobNationalCharacter>::Read(unsigned int length)  does not work correctly for NClob containing text in utf-8 in Russian.
The problem seems to be that when we give it the size of an NClob containing the text utf-8, the size buffer is smaller than necessary here. 
For example, NClob contains text of length 260 (this size is returned by the Lob <T function, U> :: GetLength ()) characters, but the actual data size, for example, is 297 bytes. 
Further, in the OCI_LobRead2 () function, when reading into a buffer, the buffer size will be only 260 bytes, but you really need 297, since utf-8 may contain more than one byte per character. 
If there are several calls to the Read () function, the application crashes. In addition, in the Read () function, when MakeString () is called, the string is incorrectly initialized for the same reason. Note: the encoding in DB for NCHAR is set utf-8.  
On client is set the NS_LANG variable to RUSSIAN_CIS.AL32UTF8

**Comment by vrogier** [comment]
Hi,

In fact, you issues is not covered by  #170.
I will do further investigation.
Can you provide some sample code and data reproducing the issue ?

Thanks

**Comment by stan-yu** [comment]
// Suppose that the table in the database contains two columns: <int, NClob>
// Insert in the table, for example, one record: <1, "Hello world, Здравствуй мир, some data...">   
// In DB var set is NLS_NCHAR_CHARACTERSET = UTF8

// in client code init
setenv("NLS_LANG", "RUSSIAN_CIS.AL32UTF8", 0);
// ...............


void read(Resultset &rs) {
    while (rs++) {
        auto id = rs.Get<big_uint>(1);
        auto data_clob = rs.Get<ocilib::NClob>(2); 
        std::string text_data  =
            data_clob.Read(static_cast<uint32_t>(data_clob.GetLength()));
        // do something with the data.....

        // at some arbitrary iteration or when exiting the function, will crash.
    }
}

**Comment by vrogier** [comment]
Hi, 

a fix will be committed tomorrow for v4.6.0 release..

Regards,

Vincent
