### ISSUE TITLE
OCI_BindArrayOfNumbers - is it possible to add / pass an empty array

### ISSUE THREAD

**Issue by J-Gaeta** [vrogier/ocilib#184]
The code I am replacing OO4O allowed you to add a count of 1 for the table size but did not require any elements to be added

This was used when an empty table was passed to a stored proc

If I do this with OCI_BindArrayOfNumbers it errors with "The data area passed to a system call is too small"
or if I add size of 0  it returns an error "Array must have at least 1 item."

Cheers

John

**Comment by vrogier** [comment]
Hi,

Why setting the bind current value to null with OCI_BindSetNull() ?
Or if you know in advance it will be empty, pass an empty table in the pl/SQL statement?

Regards

Vincent

**Comment by vrogier** [comment]
No news from op. 
Closing the issue.

**Comment by J-Gaeta** [comment]
Thanks for your help Vincent
