### ISSUE TITLE
OCILIB 4.5.2 unable to read unicode data from database

### ISSUE THREAD

**Issue by h1257977** [vrogier/ocilib#187]
OS: Ubuntu 18.04 64 bit
OCILIB version: 4.5.2

configured as:
    ./configure --with-oracle-headers-path=/usr/include/oracle/12.2/client64/ --with-oracle-lib-path=/usr/lib/oracle/12.2/client64/lib  CFLAGS="-O2 -m64"

Code on test.c :
`
#include "ocilib.h"
int main(int argc, char *argv[])
{
    OCI_Connection* cn;
    OCI_Statement* st;
    OCI_Resultset* rs;

    OCI_Initialize(NULL, NULL, OCI_SESSION_DEFAULT);
 
    cn = OCI_ConnectionCreate("192.168.50.155/orcl", "testfororacle", "oracle", OCI_SESSION_DEFAULT);
    st = OCI_StatementCreate(cn);
 
    OCI_ExecuteStmt(st, "select user_id, user_name from users");
 
    rs = OCI_GetResultset(st);
 
    while (OCI_FetchNext(rs))
    {
        printf("%i - %s\n", OCI_GetInt(rs, 1), OCI_GetString(rs,2));
    }
 
    OCI_Cleanup();
 
    return EXIT_SUCCESS;
}
`

compiled using: gcc test.c -o test -L. -locilib 
user_id shows the number as intended, but username shows correctly for english character but shows ???? for unicodes (hindi) charecter. So what do i need to change so as to get the unicode characters too ?

**Comment by vrogier** [comment]
Hi,

OCILIB supports ANSI and Unicode. [Check the related section of the documentation](https://vrogier.github.io/ocilib/doc/html/group___ocilib_c_api_supported_charsets.html).

If you want to stick toOCI_CHARSET_ANSI and want to use then UTF8, then use NLS_LANG.
Otherwise use OCI_CHARSET_WIDE.

Best regards,

Vincent

**Comment by vrogier** [comment]
Closing issue as no news from OP after 3 months.
