### ISSUE TITLE
OCI_ExecuteStmt block the program for severy days without any error notification

### ISSUE THREAD

**Issue by sunnyinchina** [vrogier/ocilib#193]
When I develop program about writing data to Oracle 11g using ocilib 4.6.0,  a problem is met that the program is blocking at  OCI_ExecuteStmt after runing several hours and couldn't continue without any error notification until I close the program and restart it.
    I have tried several ways to solve it but it still couldn't work, such as disconnect the OCI_Connection every minute and then reconnect and write data. And I also tried the way of create connection,write one data, then disconnect and so on, and the result is program blocked at OCI_ConnectionCreate after runing about 30 minutes. Until I close the program and restart it, the program can run several hours and then is blocked.
    The program is listed here:
///////////////////////////////////////////////////////////////////////////////////
int _tmain(int argc, _TCHAR* argv[])
{
	SYSTEMTIME local = { 0 };
	int i = 0;
	wchar_t sql_str[520] = { 0 };
	clock_t start = 0;
	clock_t finish = 0;
	int testno = 0;
	OCI_Connection *oci_connect = NULL;
	OCI_Statement  *oci_statement = NULL;

	if (!OCI_Initialize(errorhandler, NULL, OCI_ENV_THREADED | OCI_ENV_CONTEXT))
	{
		return EXIT_FAILURE;
	}

	printf("plese input test no.：\n");
	scanf("%d", &testno);

	printf("\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\OCILIB %d#test\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n", testno);

	while (!_kbhit())
	{
		if (FALSE == OCI_IsConnected(oci_connect))
		{
			oci_connect = OCI_ConnectionCreate(L"192.168.1.10:1521/ORCL", L"SH", L"admin", OCI_SESSION_DEFAULT);
			oci_statement = OCI_StatementCreate(oci_connect);

			if (TRUE == OCI_IsConnected(oci_connect))
			{
				printf("ORA V%d connect successs,send timeout%dms,recvtimeout%dms\n", OCI_GetVersionConnection(oci_connect), OCI_GetTimeout(oci_connect, OCI_NTO_SEND), OCI_GetTimeout(oci_connect, OCI_NTO_RECEIVE));
			}
			else
			{
				Sleep(1000);
				continue;
			}
		}/*end of if (FALSE == OCI_IsConnected(oci_connect))*/

		GetLocalTime(&local);

		swprintf(sql_str, L"insert into DATA (time, machid) values( to_date('%d-%d-%d %d:%d:%d', 'YYYY-MM-DD hh24:mi:ss'),'%s')", local.wYear, local.wMonth, local.wDay, local.wHour, local.wMinute, local.wSecond,	L"100045");

		start = clock();

		OCI_ExecuteStmt(oci_statement, sql_str);

		if (OCI_Commit(oci_connect))
		{
			finish = clock();

			printf("--->time used %dms,insert no:%d\r", (finish - start) * 1000 / CLOCKS_PER_SEC, i + 1);

			i++;
		}
		else
		{
			printf("--->insert error,no:%d\r", i + 1);

			OCI_StatementFree(oci_statement);
			OCI_ConnectionFree(oci_connect);
		}

		Sleep(1000);
	}/*end of while (TRUE)*/

	OCI_StatementFree(oci_statement);
	OCI_ConnectionFree(oci_connect);

	OCI_Cleanup();

	system("pause");
	return 1;
}

**Comment by vrogier** [comment]
Hi,
Seems to be related to oracle timeouts.
If it blocks in OCIStmtExecute(), it is an Oracle / network issue.
You can use change values in sqlnet.ora file or using OCI_SetTimeout() if using at least Oracle 12c.

Regards,

Vincent
