### ISSUE TITLE
Compile Error with Oracle Client 12.2 and option OCI_ATTR_CALL_TIMEOUT

### ISSUE THREAD

**Issue by mohsenomidi** [vrogier/ocilib#198]
The OCI_ATTR_CALL_TIMEOUT is not defined in connection.c 

Environment : 
Ubuntu Linux 18.04 
Oracle Client :12.2

**Comment by vrogier** [comment]
Hi,

Thanks for reporting the issue !

I will fix it asap and include for 4.6.1 release!

Best regards,

Vincent
