### ISSUE TITLE
Compile warnings on Oracle Client 12.2

### ISSUE THREAD

**Issue by mohsenomidi** [vrogier/ocilib#199]
While compiling the app I got the compilation warnings, check below comments of make output:

file included from ocilib_internal.h:25:0,
                 from connection.c:21:
connection.c: In function ‘OCI_GetVersionServer’:
connection.c:1320:26: warning: implicit declaration of function ‘OCIServerRelease2’; did you mean ‘OCIServerRelease’? [-Wimplicit-function-declaration]
                 OCI_EXEC(OCIServerRelease2((dvoid *)con->cxt, con->err, (OraText *)dbstr, (ub4)dbsize, (ub1)OCI_HTYPE_SVCCTX, &version, OCI_DEFAULT))
                          ^
ocilib_checks.h:34:22: note: in definition of macro ‘OCI_EXEC’
         OCI_STATUS = fct;                                                      \
                      ^~~
connection.c:1342:27: warning: implicit declaration of function ‘OCI_SERVER_RELEASE_REL’; did you mean ‘OCI_SERVER_NORMAL’? [-Wimplicit-function-declaration]
                 ver_maj = OCI_SERVER_RELEASE_REL(version);
                           ^~~~~~~~~~~~~~~~~~~~~~
                           OCI_SERVER_NORMAL
connection.c:1343:27: warning: implicit declaration of function ‘OCI_SERVER_RELEASE_REL_UPD’; did you mean ‘OCI_PREP_RESERVED_1’? [-Wimplicit-function-declaration]
                 ver_min = OCI_SERVER_RELEASE_REL_UPD(version);
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~
                           OCI_PREP_RESERVED_1
connection.c:1344:27: warning: implicit declaration of function ‘OCI_SERVER_RELEASE_REL_UPD_REV’ [-Wimplicit-function-declaration]
                 ver_rev = OCI_SERVER_RELEASE_REL_UPD_REV(version);
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by vrogier** [comment]
Hi,

Thanks for reporting the issue !

I will fix it asap and include for 4.6.1 release!

Best regards,

Vincent

**Comment by mohsenomidi** [comment]
It Fixed, Thanks :)
