### ISSUE TITLE
OCI_ExecuteStmt freeze for explain plan with error

### ISSUE THREAD

**Issue by sidluke** [vrogier/ocilib#204]
OCI_ExecuteStmt with query:  "explain plan for select 1 from dual1" freeze application since version 4.5.2  
I believe it can be any explain plan query with error. Table dual1 is of course not existing. 
Lib used: ociliba.dll

Versions prior to 4.5.2 work fine and error is returned (with 0 position which was fixed in 4.5.2)

Thanks for checking and feedback.

**Comment by vrogier** [comment]
Hi,

I have just tried the following on a Windows 18c install  (ocilib 4.6.2 compiled as 64bits and ansi charset):

```c
        cn = OCI_ConnectionCreate(dbs, usr, pwd, OCI_SESSION_DEFAULT);
        st = OCI_StatementCreate(cn);
        OCI_ExecuteStmt(st, "explain plan for select 1 from dual1");
```

with an error handler doing :

```c
printf("ERROR Pos %d - %s\n", OCI_GetSqlErrorPos(OCI_ErrorGetStatement(err)), OCI_ErrorGetString(err));
```

And I get the following result instantly:

```
ERROR Pos 31 - ORA-00942: table or view does not exist
```
I cannot reproduce the issue.
Can you provide a  complete sample code and conditions (build option, oracle versions, ...) for me to reproduce it ?

By the way, I have just notice that OCI_GetStatementType() returns the value 15 for "EXPLAIN PLAN ...." that is no a public and documented statement type value in OCI documentation.
Thus, there is not ocilib counterpart value in OCI_CST_xxx defines. 
I will add it for next release.

**Comment by sidluke** [comment]
Hi Vincent,  

I confirm the false alarm. I should have check "clean" explain statement first. 
Actually I had a bug in my app around OCI_GetSqlErrorPos which was not visible due to bug fixed in 4.5.2
(hence using older dll was fixing the problem)

Regards and thank you for quick reply.

**Comment by NormanDunbar** [comment]
Hi Vincent,

> By the way, I have just notice that OCI_GetStatementType() returns the value 15 for "EXPLAIN PLAN ...." that is no a public and documented statement type value in OCI documentation.
> Thus, there is not ocilib counterpart value in OCI_CST_xxx defines.

I don't know if it's of any help, but a command code of 15 is an ALTER TABLE command. 

I've written a document on Oracle Trace Files over at https://github.com/NormanDunbar/OracleTraceFilesExplained/blob/master/OracleTraceFilesExplained.pdf and you can help yourself, if necessary. The Appendices have lists and lists of:

* Oracle Data Types - as used in the various trace lines in the `oacdty` field. There are quite a few data types that are not documented and others that are incorrect in the Oracle docs.
* Command Codes - as used in the `oct` field. You can extract a list from the database as follows:
````
select action as code,  name as command
from audit_actions
order by 1;
````
* Characterset Codes - as used in the `csi` field in the trace files. Again, these are extracted form the database with
````
select nls_charset_id(value) as code, value as CharacterSet
from v$nls_valid_values
where isdeprecated = 'FALSE'
and parameter = 'CHARACTERSET'
order by 1;
````

Hope this is useful and not 'teaching granny to sick eggs'!!

Cheers,
Norm.

**Comment by vrogier** [comment]
Hi, 

I am not talking about command codes  (these are documented in ocilib.h as  OCI_SFC_xxxx constants (not exhaustive list).
But rather statement SQL types which is a different concept provided by OCI.

Best regards :)

Vincent.

**Comment by vrogier** [comment]
Hi,

I've opened issue #207 as documented OCI_SFC_xxxx values in ocilib.h are inaccurate!
I've discovered this thanks to your last comment :)

Regards,

Vincent

**Comment by NormanDunbar** [comment]
Cheers, glad to "help". :)

Cheers,
Norm.
