### ISSUE TITLE
DNS request for OCI host

### ISSUE THREAD

**Issue by Usharovsky** [vrogier/ocilib#205]
the result of tracing our application using the strace linux utility:

sendmmsg(67, {{{msg_name(0)=NULL, msg_iov(1)=[{"X\362\1\0\0\1\0\0\0\0\0\0\3OCI\5mydomain\3com\0\0\1\0\1", 31}] ...

sendmmsg(67, {{{msg_name(0)=NULL, msg_iov(1)=[{"-D\1\0\0\1\0\0\0\0\0\0\3OCI\0\0\1\0\1", 21}]...

Application and Oracle server  have different host names.
We don't have OCI host.
OCILIB v 4.6.2
OCI v 18.3

**Comment by vrogier** [comment]
Hi,

I do not understand the problem, nor the question.

Can you make it clearer ?

thanks.

Vincent

**Comment by Usharovsky** [comment]
when establishing a connection with Oracle, the application makes a DNS request for resolving of an unknown host "OCI"

**Comment by vrogier** [comment]
This is not related to OCILIB but rather to Oracle OCI Client. 
You can check Oracle forums or support site about it.

Best regards,

Vincent
