### ISSUE TITLE
OCILIB SQL has different results from SQL*Plus or Toad. Weird.

### ISSUE THREAD

**Issue by NormanDunbar** [vrogier/ocilib#206]
I'm sure this is something I'm doing wrong, somewhere but I really can't find anything. This might be a bug in how OCILIB works, but I really doubt it, but I have no idea what else to look at. So, here goes:

I have an SQL query to pull out some data from `V$RMAN_STATUS` showing the session_recid and a LISTAGG of all the sub_jobs that ran as part of the parent job:

````
SELECT  tasks.session_recid, 
LISTAGG(
        case when (tasks.object_type like 'DB%' and tasks.operation = 'BACKUP') then 
            '<span class="green">[' || tasks.operation || '] [' || tasks.object_type || ']</span>'
        else
            '<span class="red">[' || tasks.operation || '] [' || tasks.object_type || ']</span>'
        end, '<br>')
            WITHIN GROUP (ORDER BY tasks.start_time) AS sub_jobs
FROM    V$RMAN_STATUS tasks
where   parent_recid is not null
and     start_time >= trunc(sysdate) - 1
GROUP   BY session_recid;
````

(This is part of a bigger query, but the above is small enough to show the problem.)

The various '[' and ']' characters are there to show where there might be whitespace in the data returned in the `operation` and `object_type` columns. They are not present in the final version of the code.

If I run the above in a database, I get everything correctly returned. I'm running from Toad and from SQL*Plus by the way. The "BACKUP DB INCR" and "BACKUP DB FULL" sub tasks are correctly wrapped in the 'green' class, and everything else is 'red'. So that's my testing carried out, time to build the application.

I pasted the above SQL into an OCILIB C application, as follows:

````
char *SQLTemplate =
    "------------------------------------------------------------------------------------------\n"
    "-- Get a list of sub-tasks, carried out by a session, within RMAN, in the last 24 hours.\n"
    "------------------------------------------------------------------------------------------\n"
    "    SELECT  tasks.session_recid,\n"
    "    LISTAGG(\n"
    "            case when (tasks.object_type like 'DB%' and tasks.operation = 'BACKUP') then \n"
    "                '<span class=\"green\">[' || tasks.operation || '] [' || tasks.object_type || ']</span>'\n"
    "            else\n"
    "                '<span class=\"red\">[' || tasks.operation || '] [' || tasks.object_type || ']</span>'\n"
    "            end, '<br>')\n"
    "                WITHIN GROUP (ORDER BY tasks.start_time) AS sub_jobs\n"
    "    FROM    V$RMAN_STATUS tasks\n"
    "    where   parent_recid is not null\n"
    "    and     start_time >= trunc(sysdate) - 1\n"
    "    GROUP   BY session_recid";
````

Then compiled and executed the code. Weirdly, now, everything is in class 'red' even "BACKUP DB INCR" and "BACKUP DB FULL"! It's the same code and it's been driving me nuts for days now.

I've stripped the application code down to the absolute minimum, and it should be attached somewhere. I'm building this app on:

* Windows 7 64 bit;
* Latest OCILIB version 4.6.0;
* Oracle 11.2.0.4 64bit client;
* The database is 11.2.0.4 64 bit on AIX;
* My login in Toad/Sql*Plus/the app is the same;
* My login has DBA privileges;
* I'm using CodeBlocks to build the app;
* I'm using  the TDM 64/32 bit version of mingw-gcc for Windows as I need to compile for 64 bit Oracle Client;
* OCILIB is compiled with the TDM 64/32 bit compiler in 64 bit mode;
* I'm compiling the application with `-DOCI_IMPORT_LINKAGE` and `-DOCI_CHARSET_ANSI`.

OK, here's the data when executed in TOAD:

````
35835	<span class="red">[DELETE] []</span><br><span class="green">[BACKUP] [DB INCR]</span><br><span class="red">[CONTROL FILE AND SPFILE AUTOBACK] []</span><br><span class="red">[BACKUP] [ARCHIVELOG]</span><br><span class="red">[CONTROL FILE AND SPFILE AUTOBACK] []</span><br><span class="red">[DELETE] [ARCHIVELOG]</span><br><span class="red">[DELETE] []</span>
````

And the same run in my C application:

````
SESSION_RECID: 35835
     SUB_JOBS: <span class="red">[DELETE] []</span><br><span class="red">[BACKUP] [DB INCR]</span><br><span class="red">[CONTROL FILE AND SPFILE AUTOBACK] []</span><br><span class="red">[BACKUP] [ARCHIVELOG]</span><br><span class="red">[CONTROL FILE AND SPFILE AUTOBACK] []</span><br><span class="red">[DELETE] [ARCHIVELOG]</span><br><span class="red">[DELETE] []</span>
````

Sorry it's so long. Hope someone can see what's going on here, because I can't!

Cheers,
Norm.

[OCILIB_BUG_MAYBE.zip](https://github.com/vrogier/ocilib/files/2966203/OCILIB_BUG_MAYBE.zip)

**Comment by NormanDunbar** [comment]
I was hoping someone would have had a looksee, but probably more important things to do. :( That's understandable.

I'm not a noob in Oracle, by the way, I've been a DBA/Developer for many years, so when I ask for help, it usually means I've gone as far as I can with what I know. 

I'm just really weirded out by the fact that SQL*Plus, Toad, SQL Developer running the code gives the correct result, while the same SQL in OCLIB gives different results.

Still looking at this, and still not making progress.

Any help gratefully received. 

Cheers,
Norm.

**Comment by FladoToo** [comment]
Hi Norm,
looking at your code, I fail to see how OCILIB can be the problem. I see at least one inconsistency in the way you build the SQL statement (the template has only one %s and you sprintf the daysAgo twice), so it might be beneficial to look at the statement OCILIB gets from your program, and (seeing how you've probably done SQL tracing) the statement Oracle gets from OCILIB, then compare the two.

Hope this helps.
Flado

**Comment by NormanDunbar** [comment]
Afternoon @FladoToo and many thanks for taking an interest.

I'm afraid that the code `sprintf(SQL, SQLTemplate, daysAgo, daysAgo);` is a typo. The example program is the minimum required to show the error. I extracted it from the real application and that does have two '%s' in the template.

I've actually tested this on Windows and Linux, the (broken) example you've looked at, and both return the same, wrong, results. The compiler doesn't seem to notice the extra parameter for the template. Hmm.

Anyway, thanks again, but the real application code is correct (two %s replaced by "days ago" from the command line) and gives the wrong result.

Cheers,
Norm.

**Comment by FladoToo** [comment]
Hi Norm,

what about the SQL from the sql trace? Could you post it here? Does it give
you the correct results when pasted in SQL Developer while returning the
wrong ones to OCILIB? That would be evidence for a bug - albeit in Oracle
and not in OCILIB...

I realise I could test that myself, but I'm on my phone right now.

Cheers,
Flado

**Comment by NormanDunbar** [comment]
Hi @FladoToo,

ok, I fixed the typo in the example program, recompiled it and OCILIB 4.6.0 on Windows, and ran the example program with tracing on. The relevant part of the trace is as follows. The only edits are removing a lot of unnecessary `WAIT` and `STAT` lines which are of no relevance here. I did leave in a couple of lines from the header of the trace file, just to show it's a valid test, today, with the buggy exe file! 

The actual output for the BACKUP DB INCR lines was, as before, showing a red class instead of green.

````
...
*** 2018-04-18 14:57:24.167
*** SESSION ID:(2798.51257) 2018-04-18 14:57:24.167
...
*** MODULE NAME: (ocilib_bug_maybe.exe) 2018-04-18 14:57:24.167
...
PARSING IN CURSOR #4573596656 len=864 dep=0 uid=92 oct=3 lid=92 tim=67912320402445 hv=2951437125 ad='70001049cfd36d0' sqlid='7637c7kryqqu5'
------------------------------------------------------------------------------------------
-- Get a list of sub-tasks, carried out by a session, within RMAN, in the last 24 hours.
------------------------------------------------------------------------------------------
    SELECT  tasks.session_recid,
    LISTAGG(
            case when (tasks.object_type like 'DB' and tasks.operation = 'BACKUP') then
                '<span class="green">[' || tasks.operation || '] [' || tasks.object_type || ']</span>'
            else
                '<span class="red">[' || tasks.operation || '] [' || tasks.object_type || ']</span>'
            end, '<br>')
                WITHIN GROUP (ORDER BY tasks.start_time) AS sub_jobs
    FROM    V$RMAN_STATUS tasks
    where   parent_recid is not null
    and     start_time >= trunc(sysdate) - 1
    GROUP   BY session_recid
END OF STMT
PARSE #4573596656:c=6488,e=11162,p=0,cr=2,cu=0,mis=1,r=0,dep=0,og=1,plh=1375730647,tim=67912320402445
EXEC #4573596656:c=37,e=63,p=0,cr=0,cu=0,mis=0,r=0,dep=0,og=1,plh=1375730647,tim=67912320402667
FETCH #4573596656:c=28127,e=61129,p=0,cr=0,cu=0,mis=0,r=20,dep=0,og=1,plh=1375730647,tim=67912320463860
FETCH #4573596656:c=43,e=71,p=0,cr=0,cu=0,mis=0,r=21,dep=0,og=1,plh=1375730647,tim=67912320510557
XCTEND rlbk=1, rd_only=1, tim=67912320554944
XCTEND rlbk=0, rd_only=1, tim=67912320586537
CLOSE #4573596656:c=3,e=5,dep=0,type=0,tim=67912320586609
````

As you can see, it's the correct SQL. I also re-ran the sql above, in Toad and SQL*Plus, and got the correct answer, the BACKUP DB INCR lines are in green class. As I said, weird!

Appreciate you taking a look.

Cheers,
Norm.

**Comment by FladoToo** [comment]
There we have it😊

Your sprintf is removing the percent signs from the LIKE operator's
argument, turning it into

tasks.object_type like 'DB'

I leave the rest to you.


Cheers!

Flado

**Comment by NormanDunbar** [comment]
It is so obvious.....
when someone points it out! Sigh..

Much obliged to you, if I ever have the opportunity to buy you a pint, I will.

I need to double up the `%%` obviously.

Thanks again.

Cheers,
Norm.

**Comment by NormanDunbar** [comment]
Fixed.
Works.
Closed - closure reason, idiot programmer! (Me!)

**Comment by vrogier** [comment]
Hi all,

I'l like to have a pint too :)

Best regards,

vincent

**Comment by FladoToo** [comment]
Vincent, I'd buy you a keg of the best beer Southwestern Germany has to
offer, given a chance - so don't be a stranger if you happen to pass
through these lands!

Cheers!
Flado
