### ISSUE TITLE
Class for database access

### ISSUE THREAD

**Issue by lapleski** [vrogier/ocilib#211]
Hello.

I want to create class, which would handle database connection and have a public atribute ResultSet.

Something like this:

```
#include "ocilib.hpp"
#include <string>
#include <iostream>

using namespace ocilib;

class Dao
{
private:
	
	Connection* con;
	Statement* st;

public:
	Resultset* rs;
	Dao(std::string sqlQuery);
	~Dao();

};
```
and realisation of class:
```
#include "Dao.h"

Dao::Dao(std::string sql_query)
{
	try
	{
		Environment::Initialize();
		con = new Connection("rfinfot1", "broker", "broker");
		st = new Statement(*con);
		st->Execute(sql_query.c_str());
		*rs = st->GetResultset();
	}
	catch (std::exception& ex)
	{
		std::cout << ex.what() << std::endl;
	}
}

Dao::~Dao()
{
	Environment::Cleanup();
}

```

But I got exception when I do '*rs = st->GetResultset();'.

I think that there is a problem in my architecture solution. Can you help me with right architecture for my goal?

**Comment by vrogier** [comment]
Hi,

- Environment::initialize() and Environment::Finalize() should be called only once per application life-time
- Resulsets are owned by Statements and deallocated every time their origin statement are re-prepared
- You cannot "store" a "smart reference" on a resultset (which what a ocilib::Resultset object is) but you can store a "smart reference" on a statement if you do keep trace of its connection (as statements are children objects of connections)

ocilib C++ objects are "smart reference" on handles from its C API.  You don't need to allocate them using new. Instead you can just assign them.
What you can do is:

```
#include "ocilib.hpp"
#include <string>
#include <iostream>

using namespace ocilib;

class Dao
{
private:
	
	Connection con;
	Statement st;

public:
	Dao(std::string sqlQuery);
        Resultset Result();
	~Dao();
};
```
and realisation of class:
```
#include "Dao.h"

static std::atomic<bool> ocilibInitialized;

Dao::Dao(std::string sql_query)
{
	try
	{
		if (!ocilibInitialized) 
                {
                     // quick and dirty code as there is possible race condition on the guard
                     ocilibInitialized = true; 
                     Environment::Initialize();
                }

		con = connection("rfinfot1", "broker", "broker");
		st = Statement(con);
		s.Execute(sql_query);
	}
	catch (std::exception& ex)
	{
		std::cout << ex.what() << std::endl;
	}
}

Resultset Dao::Result()
{
    return st.GetResultset();
}

Dao::~Dao()
{
	if (ocilibInitialized)
        {
             Environment::Cleanup();
        }
}
`

Regards,

Vincent

**Comment by lapleski** [comment]
Thank you!
