### ISSUE TITLE
How can I insert multiple rows in DB?

### ISSUE THREAD

**Issue by Finrod3** [vrogier/ocilib#217]
dear,
I've tried your ocilib and It's wonderful, the conn.c and insert one row in a table, work good, but I've tried to insert multiple rows and I've an error (error segmentation and core dump)
Could you give me an advice or instruction for insert multiple rows?
Thank you
this is my program:
```c
#include "ocilib.h"
void err_handler(OCI_Error *err)
{
    printf("%s\n", OCI_ErrorGetString(err));
}

int main(void)
{
    OCI_Connection *cn;
    OCI_Statement  *st;
    OCI_Resultset  *rs;
	int ctn;
	int a;
	char name,surname;
    if (!OCI_Initialize(err_handler, NULL, OCI_ENV_DEFAULT))
    {
        return EXIT_FAILURE;
    }
    cn = OCI_ConnectionCreate("db", "usr", "pwd", OCI_SESSION_DEFAULT);
    st = OCI_StatementCreate(cn);
	
	Printf("how many rows do you want insert?");
	scanf("%d",&ctn);
	
	for(int i=0;i<=ctn;i++){
	printf("add badge number: ",a);
	scanf("%i",&a);
	printf("add name :",name);
	scanf("%d",&name);
	
	printf("add surname :",surname);
	scanf("%d",&surname);
	OCI_ExecuteStmt(st, OTEXT("insert into badge ")
                        OTEXT("(badge_id, name, surname) ")
                        OTEXT("values (:a, :name, :surname)"));

	OCI_Commit(cn);
	}    

    printf("\n%d row(s) fetched\n", OCI_GetRowCount(rs));
	
    OCI_StatementFree(st);
    OCI_ConnectionFree(cn);
    OCI_Cleanup();

    return EXIT_SUCCESS;
}
```

**Comment by vrogier** [comment]
Hi,

Apparently, there are C language misuses in your code leading to segmentation faults.
A char variable is not a string, but just a single character !
name and surname variables are char variable not strings.
Unless your table "badge" defines name and surname as char(1), your code is wrong.
And also, you are using binding syntax in the SQL statement without using binding calls.

Assuming name and surname were meant to be strings, my advises would be:
- read more about C language
- read ocilib documentation

Best regards,

Vincent
