### ISSUE TITLE
ocilib window directory....

### ISSUE THREAD

**Issue by ljkoy26-sudo** [vrogier/ocilib#224]
Please give me a little detail on how to use it on the window platform.

-unzip the archive
-copy ocilib \ include \ ocilib.h to any place located in your includes path
-copy ocilib \ lib32 | 64 \ ocilib [x] .lib to any place located in your libraries path
-copy ocilib \ lib32 | 64 \ ocilib [x] .dll to any place located in your windows path

Exactly now C: \ Users \ ****** \ Documents \ Visual Studio 2015 \ Projects \ console_Ocilib

I'm working on a path but I don't know how to put the files.

please. The version is using oracle 11g r2, and the existing oci.dll oci.lib should also work together .. I'm not sure

**Comment by vrogier** [comment]
Hi,

what is not clear ? 
Let's say you have uncompressed the archive to c:\ocilib.

- You have to add "c:\ocilib\include" to your project "include path" options
- You have to add "c:\ocilib\lib32" or "c:\ocilib\lib64"to your project "library path" options
- Then you can compile your project that includes "ocilib.h"
- You can copy the ocilib(a|w).dll from the lib32 or lib64 folder to the folder where your exe is located
- Or you can add "c:\ocilib\lib32" or "c:\ocilib\lib64" to the windows PATH environment variable

Regards,

Vincent

**Comment by vrogier** [comment]
Closing as no news from op
