### ISSUE TITLE
Blong and PL/SQL block issue

### ISSUE THREAD

**Issue by crystalgreen** [vrogier/ocilib#229]
Hello Vincent,

I have trouble retrieving a `LONG RAW` value from a PL/SQL block using the `Blong` class.
The issue is that the returned `Blong` value is empty and other OUT bound values are returned incorrectly. Also, I get an Oracle error when calling `con.GetServerOutput`.

Attached you find a demo.
[ocilib-issue-228.zip](https://github.com/vrogier/ocilib/files/4557130/ocilib-issue-228.zip)

I found a workaround: bind the LONG RAW to a `Blob`. This seems to work. So the issue doesn't seem to be critical.

**Comment by vrogier** [comment]
Hi,

Indeed, OCILIB OCI_Long (Clong and Blong in C++)  implementation only supports:
-  IN binds 
-  fetching from resultsets

You made me realized that I did never thought about implementing OUT bind for it.

OCI_Long had been orignally added for supported LONG and LONG RAW.
These types are now depreciated and their OCI support though piecewise operation is a nightmare.

As these types can be mapped to OCI_Lob in OCILIB (Clob and Blob in C++ API), I was already thinking about dropping OCI_Long type in OCILIB 5.0.
Thus I don't think I will invest type in supporting OUT bind.

Version 4.7.0 is one is way, it is an internal  intermediate step allowing me to decorrelate the implementation from the surface API to work in advance on API changes without impacting current API.

Vincent

**Comment by crystalgreen** [comment]
No problem, if you don't plan on supporting this, as there is the `Blob` workaround. I just wanted to point this out. You can close the issue, if you want.

**Comment by vrogier** [comment]
As proposed by OP, issue will be closed.
Long support will be probably removed in future versions of OCILIB.
