### ISSUE TITLE
Can not kill my program when use ctrl+c

### ISSUE THREAD

**Issue by fangguangyang** [vrogier/ocilib#233]
I have read this https://github.com/vrogier/ocilib/issues/115
and set
```
DIAG_ADR_ENABLED=OFF
DIAG_SIGHANDLER_ENABLED=FALSE
DIAG_DDE_ENABLED=FALSE
```
in sqlnet.ora 
and set `TNS_ADMIN="$ORACLE_HOME/network/admin"` in env
#### my test code
```C
#include "ocilib.h"

int main(int argc, char *argv[])
{
    OCI_Connection *cn;
    OCI_Statement *st;
    OCI_Resultset *rs;

    OCI_Initialize(NULL, NULL, OCI_ENV_DEFAULT);

    cn = OCI_ConnectionCreate("lgdata", "core", "core", OCI_SESSION_DEFAULT);
    getchar();
    st = OCI_StatementCreate(cn);
    OCI_ExecuteStmt(st, "select * from user");

    rs = OCI_GetResultset(st);
    while (OCI_FetchNext(rs))
    {
        printf("%s - %s - %s\n", OCI_GetString(rs, 1), OCI_GetString(rs, 2), str);
    }

    OCI_Cleanup();
    return 0;
}
```
when this program run to `getchar();`
I can't kill it with ctrl+c

but if the test code is
```C
...
    OCI_Initialize(NULL, NULL, OCI_ENV_DEFAULT);
    getchar();
    cn = OCI_ConnectionCreate("lgdata", "core", "core", OCI_SESSION_DEFAULT);    
    st = OCI_StatementCreate(cn);
    OCI_ExecuteStmt(st, "select # from t");
...
```
before the connection create, can use ctrl+c to kill it.

So, please help me what can I do? Thanks.

**Comment by vrogier** [comment]
Hi,

Oracle Client is installing signal handlers, 
You might want to browse Oracle documentation on this topic.
OCILIB does not do anything regarding signal handling.
I am afraid that I cannot help on this topic :(

Regards,

Vincent

**Comment by cjbj** [comment]
In your 'client' sqlnet.ora, perhaps try:
```
# Not needed with 19.3 client to 19.3 server (onwards)
disable_oob=on
```

**Comment by fangguangyang** [comment]
@cjbj appreciate your advice
I had try this, it don't work to me and my oracle client is 19.6

**Comment by fangguangyang** [comment]
@vrogier Thank you for your reply

I know Oracle Client  installed signal handlers,
Now, I installed a signal by myself in my program like this
```
void SignalFunc(int sig_num)
{
    switch (sig_num)
    {
    case SIGINT:
        printf("signal int\n");
        OCI_Cleanup();
        exit(0);
        break;
    }
}

int main(int argc, char *argv[])
{
    signal(SIGINT, SignalFunc);
    ...
}
```
It can work but I don't know if there will be unknown consequences.

**Comment by vrogier** [comment]
Hi,

From OCILIB perspective, no unknown consequences. 
From OCI client perspective, you might have to check Oracle literature :)

Closing the issue as it is not related to OCILIB and a workaround exists.

Vincent
