### ISSUE TITLE
Memory issue with OCI_BAM_INTERNAL and OCI_CDT_NUMERIC

### ISSUE THREAD

**Issue by Rasmus-C** [vrogier/ocilib#236]
First: The ocilib is really great and we use it already for a long time. Thanks for sharing.

While I added a new feature in our code, I discovered a memory issue with OCI_BAM_INTERNAL and OCI_CDT_NUMERIC. More precisely with OCI_NUM_INT and OCI_BindArrayOfInts. This modified example from the documentation (replaced OCI_Date by int) should show the error:

    #include "ocilib.h"
    #define ARRAY_SIZE 10
    void err_handler(OCI_Error *err)
    {
        printf("%s\n", OCI_ErrorGetString(err));
    }
    int main(void)
    {
        OCI_Connection *cn;
        OCI_Statement *st;
        int* tab;
        int i;
        if (!OCI_Initialize(err_handler, NULL, OCI_ENV_DEFAULT))
        {
            return EXIT_FAILURE;
        }
        cn = OCI_ConnectionCreate("db", "usr", "pwd", OCI_SESSION_DEFAULT);
        st = OCI_StatementCreate(cn);
        OCI_SetBindAllocation(st, OCI_BAM_INTERNAL);
        OCI_Prepare(st, "insert into dates values (:tab)");
        OCI_BindArraySetSize(st, ARRAY_SIZE);
        OCI_BindArrayOfInts(st, ":tab", NULL, 0);
        tab = (int*) ( OCI_BindGetData( OCI_GetBind( st, 1)));
        for (i = 0; i < ARRAY_SIZE; i++)
        {
            tab[i] = i;
        }
        OCI_Execute(st);
        printf("row inserted : %d\n", OCI_GetAffectedRows(st));
        OCI_StatementFree(st);
        OCI_ConnectionFree(cn);
        OCI_Cleanup();
        return EXIT_SUCCESS;
    }

In my application the OCI_StatementFree(st) failed with a SIGABRT. After inspecting the code, I think that the macro OCI_IS_OCILIB_OBJECT does not work as expected. 

    #define OCI_IS_OCILIB_OBJECT(type, subtype)                                     \
        ( (OCI_IS_OCI_NUMBER(type, subtype)) ||                                     \
          (OCI_CDT_TEXT    != (type) &&                                             \
           OCI_CDT_RAW     != (type) &&                                             \
           OCI_CDT_BOOLEAN != (type)))

It returns true for all types of OCI_CDT_NUMERIC because one part of the or statement will be true. For that reason, allocation and deallocation for the array might fail. For my application, the following fix worked:

    @@ -461,7 +461,8 @@
     
     #define OCI_IS_OCILIB_OBJECT(type, subtype)                                     \
         ( (OCI_IS_OCI_NUMBER(type, subtype)) ||                                     \
    -      (OCI_CDT_TEXT    != (type) &&                                             \
    +      (OCI_CDT_NUMERIC != (type) &&                                             \
    +       OCI_CDT_TEXT    != (type) &&                                             \
            OCI_CDT_RAW     != (type) &&                                             \
            OCI_CDT_BOOLEAN != (type)))

I hope I described the issue in sufficient detail and did not missed something.

Beside the bug, I discovered that the documentation of OCI_SetBindAllocation() states that "OCI_Prepare() reset it (bind allocation mode) by default to OCI_BAM_EXTERNAL" which seams not to be true anymore.

**Comment by vrogier** [comment]
Hi,

Thanks for reporting the issue.
This has already been identified and fixed in 4.7.0 branch a month ago in this [commit](https://github.com/vrogier/ocilib/commit/1b7fe5777cb8aea5b946d8374a70b6c16eaaeb87)

Best regards,

Vincent

**Comment by vrogier** [comment]
v4.7.0 merged in Master.
