### ISSUE TITLE
Fetching nclobs as strings return value in hexa format

### ISSUE THREAD

**Issue by bangusi** [vrogier/ocilib#239]
Env:
Server: Oracle 12c UTF8 on Linux
NLS_NCHAR_CHARACTERSET = AL16UTF16
NLS_CHARACTERSET = AL32UTF8
NLS_LANGUAGE = AMERICAN
NLS_LENGTH_SEMANTICS = BYTE

Client: 18c UTF8
ocilib:  v4.6.4 ANSI
OS: Windows 10

```
create table NCLOBTEST
(
NAME_VALUE NCLOB
)
;
insert into NCLOBTEST
values('The quick brown fox jumps over the lazy dog');

commit;
```
Partial code:
```
stmt.Execute ( "select name_value from nclobtest") ;
rs.Get<ostring>(1)
```

Results:
54686520717569636B2062726F776E20666F78206A756D7073206F76657220746865206C617A7920646F67

**Comment by vrogier** [comment]
Hi,

Issue fixed in 4.7.0 branch. 
when converting LOBs, OCI_GetString() was handing NCLOB like BLOB, e.g. by converting it to hexa string.

**Comment by vrogier** [comment]
I will add a test suite for it tomorrow morning and publish the release later in the day.

**Comment by vrogier** [comment]
v4.7.0 merged in Master.
