### ISSUE TITLE
Calling stored functions example

### ISSUE THREAD

**Issue by lapleski** [vrogier/ocilib#241]
Hello.

I got 2 oracle functions:
```
 function createPost(
    externalId varchar2
    , postDate date default sysdate
    , text varchar2
    , commentsCount integer default 0
    ) return integer;
    
  function findPost(
      vkPostId integer default null
    ) return sys_refcursor;
```

Can you show me full examples how to properly call them (pass params and read refcursor to resultSet) via OCILIB from C++ code?

**Comment by vrogier** [comment]
Hi,

Use the following pattern:

```c++
Statement st(con);
st.Prepare("begin :ret := func(:p1, :p2,....); end;");
st.Bind(":ret", ret, BindInfo::Out); // ret
st.Bind(":p1", p1, BindInfo::In) ; // p1
st.Bind(":p2", p2, BindInfo::In) ; // p2
...
st.ExecutePrepared() ;
```

Bind a Statement object for ref cursors and then you can get the resultset using Statement::GetResultset()

Statement::Bind() overload for string take one more parameter to indicate variable max length.

You can also have a look at the cpp demo files cursor.cpp, bind.cpp, fetch.cpp and ocilib_demo.cpp.

Regards,

Vincent

**Comment by lapleski** [comment]
Thank you, Vincent.
