### ISSUE TITLE
Include conflict regarding strings.h (Ubuntu 20.04)

### ISSUE THREAD

**Issue by wcosnc** [vrogier/ocilib#242]
Build on Ubuntu 20.04 failed. GCC 9.3.0.
Includes ./strings.h instead of /usr/include/strings.h.

`$./configure --with-oracle-headers-path=/xxx/instantclient_19_8/sdk/include --with-oracle-lib-path=/xxx/instantclient_19_8

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for gcc option to accept ISO C99... none needed
checking for gcc option to accept ISO Standard C... (cached) none needed
checking for OCILIB install path... /usr/local
ls: cannot access '*.html': No such file or directory
ls: cannot access '*.css': No such file or directory
ls: cannot access '*.png': No such file or directory
checking for OCILIB version... v4.7.0 
checking for OCILIB options... import: linkage, charset = ansi 
checking for Oracle home... defined by environment : 
checking for Oracle OCI headers location... /xxx/instantclient_19_8/sdk/include
checking for Oracle OCI shared lib location... /xxx/instantclient_19_8
checking for Oracle OCI shared lib name... libclntsh.so
checking for OCI shared lib existence... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating README
config.status: creating ocilib.pc
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating doc/html/Makefile
config.status: creating demo/Makefile
config.status: creating demo/Makefile_demo
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands

$ make

make  all-recursive
make[1]: Verzeichnis „/xxx/ocilib-4.7.0“ wird betreten
Making all in doc/html
make[2]: Verzeichnis „/xxx/ocilib-4.7.0/doc/html“ wird betreten
make[2]: Für das Ziel „all“ ist nichts zu tun.
make[2]: Verzeichnis „/xxx/ocilib-4.7.0/doc/html“ wird verlassen
Making all in src
make[2]: Verzeichnis „/xxx/ocilib-4.7.0/src“ wird betreten
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I/xxx/instantclient_19_8/sdk/include -I../include  -DOCI_IMPORT_LINKAGE -DOCI_CHARSET_ANSI   -g -O2 -MT libocilib_la-agent.lo -MD -MP -MF .deps/libocilib_la-agent.Tpo -c -o libocilib_la-agent.lo `test -f 'agent.c' || echo './'`agent.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I/xxx/instantclient_19_8/sdk/include -I../include -DOCI_IMPORT_LINKAGE -DOCI_CHARSET_ANSI -g -O2 -MT libocilib_la-agent.lo -MD -MP -MF .deps/libocilib_la-agent.Tpo -c agent.c  -fPIC -DPIC -o .libs/libocilib_la-agent.o
In file included from /usr/include/string.h:432,
                 from ../include/ocilibc/config.h:60,
                 from ../include/ocilibc/types.h:37,
                 from types.h:24,
                 from agent.h:24,
                 from agent.c:21:
./strings.h:36:5: error: unknown type name ‘otext’
   36 |     otext              * buffer
      |     ^~~~~
...
`

**Comment by cg2v** [comment]
FYI, you can work around this by building ocilib with CFLAGS=-std=c99, which will prevent glibc's string.h from including any strings.h

**Comment by vrogier** [comment]
Hi,

Issue fixed in current v.4.7.1 branch (release scheduled next week).

Regards,

Vincent

**Comment by vrogier** [comment]
Fixed by commit f51ddaa

**Comment by vrogier** [comment]
Branch develop-v4.7.1 merged into master
