### ISSUE TITLE
OCI_SubscriptionRegister() returns always NULL since v4.7.0

### ISSUE THREAD

**Issue by vrogier** [vrogier/ocilib#258]
OCI_SubscriptionRegister() returns always NULL since v4.7.0 due a removed return value assignment :( 
Test suite does not include test for database notifications.
This will be fixed and a test suite added for database notifications and this issue.

**Comment by Ilyacpp** [comment]
yes now in 4.7.3. first call OCI_SubscriptionRegister return not NULL. (same as in 4.7.2)
