### ISSUE TITLE
FetchMode FetchScrollable results in OcilibResultsetFetchData ORA-22922: nonexistent LOB value Error when CLOB datatype is NULL

### ISSUE THREAD

**Issue by AwWillB** [vrogier/ocilib#261]
I have run into an error, which I'm not sure if it's an Oracle level issue or an OCILIB issue, version 4.7.0 and 4.7.2.

When attempting to do a select statement on a column with a CLOB datatype that has NULL data, the OCILIB Resultset First() method encounters the following error.  This only happens if there is an index (primary key or other unique index) that the sql statement will use.

Example from sql error logs.
01/26/21 14:12:27 Port 2100: [thread_id=000001A162369F40] sql_select: xwoprint_curs1517 
SQLERR ORA: 22922, Error occured at OcilibResultsetFetchData: ORA-22922: nonexistent LOB value

:s_0 = 'WB-TESLA-01'
:s_1 = 'WB-R01'

SELECT proc_text  FROM CLASS_TASK WHERE CLASS_class_code = :s_0  AND TASK_task_code = :s_1 
-------------------------

In this example, CLASS_TASK.proc_text is a CLOB datatype that allows NULL data.
The data row for  proc_text data is NULL.
There is primary key on the columns CLASS_class_code, TASK_task_code.

If the Primary Key is removed, which removes the primary key index, the scrollable fetch executes without error while using a full table scan.

Changing the fetch mode to FetchForward, does not run into any issues.

Example of  OCILIB code.

```
select_cda->st = new Statement(db->con);
if (ForwardFetch)
	select_cda->st->SetFetchMode(Statement::FetchForward);
else
	select_cda->st->SetFetchMode(Statement::FetchScrollable);
select_cda->st->Prepare(sql_sel);

for (i = 0; i < subKeys.size(); i++)
{
	select_cda->st->Bind(subKeys[i], c1_node->bind_values[i], static_cast<unsigned int>(c1_node->bind_values[i].size()),  BindInfo::In);
}

select_cda->st->ExecutePrepared();
Resultset rs = select_cda->st->GetResultset();

if (ForwardFetch)
	resultSetReturn = rs.Next();
else
	resultSetReturn = rs.First();
if (resultSetReturn)
{
}
```

As stated before, I'm not sure if this an issue with Oracle itself, OCILIB or improper assumptions on how CLOB datatypes can be used in Oracle.

Any insight is greatly appreciated. 

Another small issue noticed, the spelling of occurred is wrong in the OCILIB output of the error, incorrectly spelled as occured.

**Comment by vrogier** [comment]
Hi,

Can you provide a DDL and complete code snippet to reproduce the error?

I will fix the spelling typo in error message;)

Regards,

Vincent

**Comment by AwWillB** [comment]
Hi, thank you for the quick response and looking into this.

I have attached a DDL script that mimics what we are attempting to accomplish.  The TLRD is we are upgrading LONG datatypes to CLOB in an existing databases, queue the celebration music.  I that might be part of the issue.  I setup some basic DDL tests of creating a table with a primary key and a CLOB data element, insert 10k rows with some rows having NULL data for the CLOB column; but I was unable to replicate the error.  Following the process of upgrading existing LONG column with NULL data to a CLOB column, rebuilding indexes; I do run into the issue, but not all the time on the test data unlike the existing data tables that have 100k to millions of rows.

The log files are example of a test case of call the following SQL for each TASK_task_code value.  For this test case the last two NULL data rows errored out with the error.
`SELECT proc_text FROM CT_WB WHERE CLASS_class_code = 'WB-CLASS' AND TASK_task_code = 'WB-TASK<n>'`

In other tests in which the sql call randomly calls a row, the results varied with errors coming back for various rows.  With the sporadic nature, I have a feeling this might be more of an Oracle issue compared to an OCILIB issue.

[CLOBTest.zip](https://github.com/vrogier/ocilib/files/5906535/CLOBTest.zip)

**Comment by vrogier** [comment]
Hi,

I am afraid that it is more an issue related to Oracle and LONG/CLOB conversion :(

Regards,

Vincent

**Comment by vrogier** [comment]
Closing the issue as it seems related to Oracle Client.
