### ISSUE TITLE
question re: instant client

### ISSUE THREAD

**Issue by bill-torpey** [vrogier/ocilib#263]
Hi again Vincent:

We continue to test our application using OCILIB 4.7.2 along with Instant Client 21.1 using AddressSanitizer, and we're seeing a hang at shutdown in Oracle library:

```
(gdb) thread apply all bt

Thread 1 (Thread 0x7fd811d02d00 (LWP 1202791)):
#0  __lll_lock_wait (futex=futex@entry=0x7fd815be83c0, private=0) at lowlevellock.c:52
#1  0x00007fd815bf50a3 in __GI___pthread_mutex_lock (mutex=0x7fd815be83c0) at ../nptl/pthread_mutex_lock.c:80
#2  0x00007fd815be1718 in _Unwind_Find_FDE () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#3  0x00007fd815bdd848 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#4  0x00007fd815bdea10 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#5  0x00007fd815bdf75c in _Unwind_Backtrace () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#6  0x00007fd81634ea28 in ?? () from /lib/x86_64-linux-gnu/libasan.so.5
#7  0x00007fd816324862 in free () from /lib/x86_64-linux-gnu/libasan.so.5
#8  0x00007fd815be160d in __deregister_frame_info_bases () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#9  0x00007fd7decc08ce in __do_deregister_frame () from /build/share/oracle/instantclient_21_1/libociei.so
#10 0x00007fd7decc0947 in __icrt_terminate () from /build/share/oracle/instantclient_21_1/libociei.so
#11 0x00007ffea8f42e10 in ?? ()
#12 0x00007fd7decc0c49 in _fini () from /build/share/oracle/instantclient_21_1/libociei.so
#13 0x00007ffea8f42e10 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) 
```

As noted above, this is the only thread running, and the `main()` function has already exited.

Just wanted to ask if you think that OCILIB may be implicated in some way?  FWIW, we don't see this unless we run under ASAN, so we suspect that ASAN itself may be the root cause of this.

NOTE: this is on Ubuntu 20.04, running under ASAN w/clang 10.  Also, this is consistent -- we must kill process with `-9`.

Thanks for any suggestions you may have!

**Comment by vrogier** [comment]
Hi,

OCILIB codebase does not use any OS/library locking/threading primitives.
It relies on Oracle clients mutex/threads primitives only if you initialize OCILIB in OCI_ENV_THREADED.

And as the stack trace involve libasan thus I would think that is related to ASAN.
In this case, I am afraid that I won't be able to bring help :(

Regards,

Vincent

**Comment by bill-torpey** [comment]
Thanks Vincent!  That's kind of what I thought, but I figured I would at least ask ...
