### ISSUE TITLE
Memory leak in Collection binds

### ISSUE THREAD

**Issue by ggreco** [vrogier/ocilib#27]
I've found an huge memory leak using collections in prepared statement with the C++ API (version 4.2.0, platform linux 64bit, compiler gcc 4.8.3).

Here is a simple program that cause the problem.

```c++
#include <iostream>
#include "ocilib.hpp"

using namespace ocilib;

int main(int argc, char *argv[])
{
    Environment::Initialize(ocilib::Environment::Default | ocilib::Environment::Threaded);
    Environment::EnableWarnings(true);
    int iterations = 2000;

    if  (argc > 1 && atoi(argv[1]) > 0)
        iterations = atoi(argv[1]);

    try {
        Pool pool;
        pool.Open("dbname", "dbuser", "dbpwd", Pool::SessionPool, 5, 20); 
        Connection con = pool.GetConnection();
        Statement st(con);  
        TypeInfo ti(con, "myarray", TypeInfo::Type);

        for (int i = 1; i < iterations; ++i) {
            Collection<ostring> lvc(ti);

            lvc.Append("T0100101");
/*
            This block is commented since it's not needed to cause the leak

            lvc.Append("T0100102");

            st.Prepare("SELECT lane FROM vehicle_t WHERE lane MEMBER OF :v");
            st.Bind(":v", lvc,  BindInfo::In);
            st.ExecutePrepared();

            Resultset rs = st.GetResultset();

            while (rs.Next()) 
                if (!rs.IsColumnNull(1)) 
                    std::cerr << '.';
*/
        }
    }
    catch (Exception &e) { 
        std::cerr << "OCILib exception: " << e.what() << "\n";
    } catch (...) {
        std::cerr << "Unknown exception!\n";
    }
    Environment::Cleanup();
}
```

PS: Updated with the changes in the comments

**Comment by ggreco** [comment]
I've found the the problem is not related to the bind of the connection, but only to collection creation, maybe the leak is in the Collection destructor, I can reproduce the leak with the following loop:

```c++
 for (int i = 1; i < iterations; ++i) {
            Connection con = pool->GetConnection();
            Statement st(con);  

            Collection<ostring> lvc(TypeInfo(con, "myarray", TypeInfo::Type));

            lvc.Append("T0100101");
}
```

**Comment by vrogier** [comment]
Hi,

Do you get the same result if you don't create a connection in each iteration?

**Comment by ggreco** [comment]
Yes, I've localized the problem even more:

This leaks:
```c++
 for (int i = 1; i < iterations; ++i) {
        Collection<ostring> lvc(TypeInfo(con, "myarray", TypeInfo::Type));
        lvc.Append("T0100101");
  }
```

This does not:
```c++
 for (int i = 1; i < iterations; ++i) {
        Collection<ostring> lvc(TypeInfo(con, "myarray", TypeInfo::Type));
 }
```

It may be that the optimizer avoid the allocation of "lvc" if not used, but there is a big chance the problem is related to the appended items not freed in the Collection destructor...

**Comment by ggreco** [comment]
Note also that this leaks too:

```c++
TypeInfo ti(con, "myarray", TypeInfo::Type);
 for (int i = 1; i < iterations; ++i) {
        Collection<ostring> lvc(ti);
        lvc.Append("T0100101");
  }
```

**Comment by vrogier** [comment]
One question, Is the memory getting freed after Environment::Cleanup() ?

**Comment by ggreco** [comment]
Actually my tests are done with PS while the binary is running (with a great number of iterations), I tried it also with valgrind adding, Environment::Cleanup() and with a lower number of iterations, these are the results:

**100 iterations**:
==777==    definitely lost: 0 bytes in 0 blocks
==777==    indirectly lost: 0 bytes in 0 blocks
==777==      possibly lost: 162,104 bytes in 5 blocks
==777==    still reachable: 531,911 bytes in 411 blocks

**1000 iterations**:
==780==    definitely lost: 0 bytes in 0 blocks
==780==    indirectly lost: 0 bytes in 0 blocks
==780==      possibly lost: 162,104 bytes in 5 blocks
==780==    still reachable: 531,911 bytes in 411 blocks

**5000 iterations**:
==824==    definitely lost: 0 bytes in 0 blocks
==824==    indirectly lost: 0 bytes in 0 blocks
==824==      possibly lost: 162,104 bytes in 5 blocks
==824==    still reachable: 531,911 bytes in 411 blocks

So it seems that the "variable" amount leaked is freed by the Cleanup() method or it cannot be seen by valgrind. Removing Cleanup() at the end of the program I get (with 100 iterations):

==1251==    definitely lost: 0 bytes in 0 blocks
==1251==    indirectly lost: 0 bytes in 0 blocks
==1251==      possibly lost: **1,000,446** bytes in 156 blocks
==1251==    still reachable: 531,912 bytes in 411 blocks

and with 5000:

==1301==    definitely lost: 0 bytes in 0 blocks
==1301==    indirectly lost: 0 bytes in 0 blocks
==1301==      possibly lost: **1,246,926** bytes in 171 blocks
==1301==    still reachable: 531,912 bytes in 411 blocks

... so it seems that cleanup is able to free that dangling collections...

**Comment by ggreco** [comment]
I can add that the bug is probably not in the C++ interface, but also in the C API, this leaks (and I think it should not):

```c
        for (int i = 1; i < iterations; ++i) {
            OCI_Coll *coll = OCI_CollCreate(ti);
            OCI_Elem *elem = OCI_ElemCreate(ti);
            OCI_ElemSetString(elem, "T0100101");
            OCI_CollAppend(coll, elem);
            OCI_ElemFree(elem);
            OCI_CollFree(coll);
        }
```

**Comment by vrogier** [comment]
HI,

OCI is handling a local cache of pinned object (such as collection elements).
I will check if this is OCILIB that does not unpin these objects or the cache itself that decide to not reuse them and allocates new ones.
One question, if you provide an error handler to OCI_Initialize() and then call OCI_Cleanup() after the test, is it fired with a message "Found %d unfreed Object handles" ? I

**Comment by ggreco** [comment]
Nope, I've build the program using OCI_Initialize() instead of Environment::Initialize(), the program seems to work as before (leaking, and releasing the leak on Cleanup()), but the error handler does not capture nothing... I've added also a cerr after cleanup to be sure that the program reach that point.

For the error handler I used the code from the example in ocilib documentation:

https://vrogier.github.io/ocilib/doc/html/group___ocilib_c_api_error_handling.html

**Comment by vrogier** [comment]
Can you provide the DDL of "myarray"?

**Comment by ggreco** [comment]
create type MYARRAY as table of varchar2(10);

BTW: if it's an oracle internal caching what happens to OCI collections that's not a very smart caching since we had a process constantly growing for this leak that was killed after a month  by the OS with an "out of memory" error!

**Comment by vrogier** [comment]
The issue is not direcly linked to collections but rather about with the
collection type you're using. When dealing with collection of strings,
Oracle client API does not use regular string (ansi or wide char) but
rather an opaque object OCIString. Thus OCILIB has to manipulate them.
Oracle documentation was not really clear about their memory management.
I found the right way to clear the memory of these string objects.
And will commit a fix for it this evening.

Regards

**Comment by ggreco** [comment]
Thanks, I compiled with the git version and I can confirm the fix works.
