### ISSUE TITLE
AddressSanitizer reports mismatched new[] vs delete

### ISSUE THREAD

**Issue by bill-torpey** [vrogier/ocilib#272]
Finding a few more related to https://github.com/vrogier/ocilib/issues/262

**Comment by bill-torpey** [comment]
Attached file has details ...

**Comment by bill-torpey** [comment]
[ocilib-errs.txt](https://github.com/vrogier/ocilib/files/6191713/ocilib-errs.txt)

**Comment by allanarbeit** [comment]
Clang reports the same warning when compiling.
The allocation happens in line 66
`_data(core::OnAllocate(new NativeType[size + 1], size + 1)),`
