### ISSUE TITLE
ocilib::Object causes Segmentation fault (SIGSEGV)

### ISSUE THREAD

**Issue by mrfazlali** [vrogier/ocilib#278]
Hi . 
I have a problem with my code and using ocilib . 

I'm using ocilib in multi-threaded env.
3 to 5 of 10 times of running my app , I get different kinds of error , exception , signal when calling to ocilib::Object

segmentation fault mostly happens at this point of ocilib code .

`inline TypeInfo::TypeInfo(const Connection &connection, const ostring& name, TypeInfoType type)
{
    Acquire(core::Check(OCI_TypeInfoGet(connection, name.c_str(), type)), static_cast<HandleFreeFunc>(nullptr), nullptr, connection.GetHandle());
}`

and sometimes i get exception with this message . 
`what():  Error occured at OcilibTypeInfoGetConnection: A null TypeInfo handle has been provided`

I wrote a sample app to demonstrate my problem and here is the code .

`class my_entity
{
public:
    std::optional<int64_t> id;
    std::optional<std::string> code;
    std::optional<entity_state> state;
    std::optional<std::string> serial_no;
    std::optional<int64_t> group_id;
};

int main()
{
    ocilib::Environment::Initialize(ocilib::Environment::Threaded);

    ocilib::Pool oci_pool("database_name" , "username" , "password"  ,
                          ocilib::Pool::ConnectionPool , 200 , 300 );

    auto worker_lambda = [](ocilib::Pool & pool)
    {

        try
        {
            auto result = 0;

            auto conn = pool.GetConnection();

            ocilib::Statement stmt(conn);

            auto entity_db_obj = ocilib::Object (ocilib::TypeInfo(conn, "MY_ENTITY_OBJ", ocilib::TypeInfo::Type));

            std::string sql = R"(
                                BEGIN
                                    :RESULT := MY_PACKAGE_PKG.GET_ENTITY_BY_CODE(:CODE , :ENTITY_INFO);
                                END;
                                )";
            stmt.Prepare(sql);
            stmt.Bind(":RESULT", result, ocilib::BindInfo::Out);
            std::string entity_code = "00000001";
            stmt.Bind(":CODE", entity_code, 8, ocilib::BindInfo::In);
            stmt.Bind(":ENTITY_INFO", entity_db_obj, ocilib::BindInfo::Out);

            stmt.ExecutePrepared();

            if (result)
            {
                my_entity one_entity;
                if ( !entity_db_obj.IsAttributeNull("ID"))
                    one_entity.id = entity_db_obj.Get<int>("ID");

                if ( !entity_db_obj.IsAttributeNull("CODE"))
                    one_entity.code = entity_db_obj.Get<std::string>("CODE");

                if ( !entity_db_obj.IsAttributeNull("STATE"))
                    one_entity.state = static_cast<entity_state>(entity_db_obj.Get<short>("STATE"));

                if ( !entity_db_obj.IsAttributeNull("SERIAL_NO"))
                    one_entity.serial_no = entity_db_obj.Get<std::string>("SERIAL_NO");

                conn.Close();
            }
        }
        catch(const ocilib::Exception & ex)
        {
            throw std::runtime_error(ex.what());
        }
    };

    std::vector<std::thread> threads(200);

    for ( int i= 0; i < 200; i++)
    {
        threads[i] = std::thread(
                worker_lambda , std::ref(oci_pool)
                );
    }

    for ( int i = 0; i < 200; i++)
        if ( threads[i].joinable())
            threads[i].join();

    ocilib::Environment::Cleanup();

    return 0;
}`

Thanks in advance.

**Comment by vrogier** [comment]
Hi,

Sorry for the delay.
I will try your sample code asap and let you know.

Regards,

Vincent

**Comment by vrogier** [comment]
What's your ocilib version ? and Oracle version ?

**Comment by vrogier** [comment]
Hi,

Root issue(s) were identified and a fix provided in the v4.7.4 branch

**Comment by mrfazlali** [comment]
Hi vrogier . Thanks a lot .
