### ISSUE TITLE
ORA-00931 in OCI_TypeInfoGet when using SYS.RAW type

### ISSUE THREAD

**Issue by iliasaz** [vrogier/ocilib#281]
Hi,
I'm trying to use AQ interface (OCI_Dequeue* functions) for a queue with RAW payload type. Prior to creating a Dequeue object, I call OCI_TypeInfoGet and pass SYS.RAW as name and OCI_TIF_TYPE as type. This call results in ORA-00931 error on 19c (19.10) and ADW (19.12). I'm using 19.8 instant client. The error seems to be coming from OCIDescribeAny OCI function.
If I use a UDT, everything works fine.

Please advise if there is any workaround.
Thanks!

**Comment by iliasaz** [comment]
Hi Vincent,

Any update on the RAW issue? No rush, just checking. 

Thanks!
Ilia

**Comment by vrogier** [comment]
Hi,

Sorry for the delay! 
You're right for the reminder. Once backed from holidays, I forgot to look at the issue.

It seems that Oracle changed the behavior of OCIDescribeAny().
In previous Oracle versions, calling it with "SYS.RAW" was working (returning a TDO - a type descriptor) and it is not anymore :(
While deprecated Oracle call OCITypeByName() is still working in 19c and returns the TDO of sys.raw when passing "SYS.RAW"....
Not very logical nor coherent!

Thus, I have there to find out more on how to make it work!

I am on it.

Vincent

**Comment by vrogier** [comment]
Hi,

I've got a fix for it that will be included in v4.7.4.
And also fixed other stuff related to raw sys type with aq.
I will pull the 4.7.4 branch by this evening. 
The release will be probably by the end of the week.

Regards,

Vincent

**Comment by vrogier** [comment]
I pushed the 4.7.4 branch with a fix for it.
Notes:
When using OCI_QueueTableCreate(), use "RAW" (with recent Oracle versions)
When using OCI_TypeInfoGet(), use "SYS.RAW"

**Comment by iliasaz** [comment]
Hi Vincent,

OCI_TypeInfoGet works fine now - thank you for fixing it!

I'm still having trouble with my use case, and I have just submitted a new issue #283. It's kind of a corner case, but that's what my app uses.

Thanks!

**Comment by cjbj** [comment]
> It seems that Oracle changed the behavior of OCIDescribeAny().

Send me email and I'll follow up with the OCI team.

**Comment by vrogier** [comment]
@cjbj  Done :)
