### ISSUE TITLE
OCI_DequeueGet returns null pointer when message has empty payload

### ISSUE THREAD

**Issue by iliasaz** [vrogier/ocilib#283]
Hi Vincent,

It appears that OCI_DequeueGet exits prematurely and returns a null pointer whenever a message being dequeued has NULL payload. I have a RAW queue in my app, and the data is passed as a correlation ID, hence the payload is NULL. If the payload has at least one byte, everything works fine.

Here is my test case:

```
begin
   dbms_aqadm.create_queue_table( 
      queue_table            => 'test_qtab', 
      queue_payload_type     => 'raw'); 
end;
/

begin
   dbms_aqadm.create_queue( 
      queue_name          => 'test_q', 
      queue_table         => 'test_qtab'); 
end;
/
```

`exec dbms_aqadm.start_queue (queue_name => 'test_q');`

```
declare
  l_enqueue_options     dbms_aq.enqueue_options_t;
  l_message_properties  dbms_aq.message_properties_t;
  l_message raw(256);
  c_msg_queue_name varchar2(100) := 'test_q';
  message_handle raw(16);
begin
  l_message_properties.correlation := '123'; -- the only thing I need from the message
  l_message := null; --hextoraw('FF'); -- works fine when the payload is not empty
  dbms_aq.enqueue(
        queue_name              => c_msg_queue_name,
        enqueue_options         => l_enqueue_options,
        message_properties      => l_message_properties,
        payload                 => l_message,
        msgid                   => message_handle
    );
  commit;
  dbms_output.put_line('enqueued msg ' || rawtohex(message_handle));
end;
/
```

By the way, even though OCI_DequeueGet returns null, which is an indication of a failure, OCI_GetLastError doesn't return any error.

Thanks!

**Comment by vrogier** [comment]
Hi,

Indeed, OCI_DequeueGet() returns a null OCI_Msg when payload is null.
I will change its behaviour to return a valid OCI_Msg even if payload is null.
Code changes and tests will be committed today.

Regards,

Vincent

**Comment by vrogier** [comment]
Fix committed for this issue.
Some issues were related to the 4.7.0 code refactoring :(
This week, I will add more non regression tests on this part of the API in the Test suite.

Regards,

Vincent

**Comment by iliasaz** [comment]
I can dequeue the message now, but I think the latest change in OcilibMessageGetID is breaking this function now, i.e. I'm not getting the message ID. It worked in the previous version.
My guess is that since max_len is always 0, len is also 0 because of min(). Hence the value is not copied.

`unsigned int max_len = 0;
    *len = 0;

    if (msg->id)
    {
        const ub4 raw_len = OCIRawSize(msg->typinf->con->env, msg->id);

        *len = min(max_len, raw_len);

        memcpy(id, OCIRawPtr(msg->typinf->con->env, msg->id), (size_t) (*len));
    }`

**Comment by vrogier** [comment]
hi,

Sorry for the issue. 
Previous change was committed to quickly.
I've just fixed it.
I will add more tests i the test suite this week on updated code.

Regards,

Vincent

**Comment by iliasaz** [comment]
Works like a charm! Thanks for building and maintaining this amazing library.

**Comment by iliasaz** [comment]
Sorry, one more question about OcilibMessageGetID()
During Enqueue, I'd like to retrieve a message ID that has just been put in the queue. So I make the following sequence of calls:

```
OCI_TypeInfoGet
OCI_EnqueueCreate
msgHandle = OCI_MsgCreate
OCI_MsgSetCorrelation
// put in the message body if not empty
OCI_EnqueuePut
if success {
OCI_MsgGetID(msgHandle)
// check for success and unpack the buffer
commit
}
```

OCI_MsgGetID returns success, but the message ID is not in the buffer. I ran it in debugger, and I think the message ID that is supposed to be returned by OCIAQEnq function is being ignored in the following call in OcilibEnqueuePut:

```
ret = OCIAQEnq(enqueue->typinf->con->cxt, enqueue->typinf->con->err,
                       (OraText*)name, enqueue->opth, msg->proph,
                       enqueue->typinf->tdo, &payload, &ind, NULL, OCI_DEFAULT);
```

Is this something you can fix?

Thanks!

**Comment by vrogier** [comment]
Hi, I will create an issue and commit a fix today for that :)

Thanks for reporting that msg id is was not available after enqueue on the msg :)

Regards,

Vincent

**Comment by vrogier** [comment]
Created issued #284 and committed a change (c371644e) to implement the enhancement request
