### ISSUE TITLE
OCI_MsgGetID() returns a NULL ID after being queued with OCI_DequeuePut()

### ISSUE THREAD

**Issue by vrogier** [vrogier/ocilib#284]
OCI_MsgGetID() returns a valid ID only when messages are retrieved from OCI_DequeueGet().
When an OCI_Msg instance is created in code and queued using OCI_DequeuePut(), OCI_MsgGetID() return NULL despite the information being available from Oracle Client.

**Comment by iliasaz** [comment]
Works great now - thanks!
