### ISSUE TITLE
configuring with --with-oracle-charset=wide CFLAGS="-O2 -m64" gives Abort trap: 6 in macos

### ISSUE THREAD

**Issue by bhregmi** [vrogier/ocilib#286]
In ocilib v4.7.3
./configure --with-oracle-home=$ORACLE_HOME --with-oracle-lib-path=$ORACLE_HOME --with-oracle-headers-path=$ORACLE_HOME/sdk/include  --disable-dependency-tracking
works correctly in MacOS but doesn;t display unicode

So to display unicode i  configured with following : 
./configure --with-oracle-home=$ORACLE_HOME --with-oracle-lib-path=$ORACLE_HOME --with-oracle-headers-path=$ORACLE_HOME/sdk/include --with-oracle-charset=wide --disable-dependency-tracking CFLAGS="-O2 -m64"

and when i try to run the same c file, it gives me the following error : 
Abort trap: 6

So what's the above issue when configured with "--with-oracle-charset=wide" in macos ? 
Whats the solution to display unicode characters in macos (works in ubuntu though) ?

**Comment by vrogier** [comment]
when configuring ocilib with "--with-oracle-charset=wide" it means that all strings are not char * but wchar_t *.
Your code is using ansi string, thus it cannot work.

It should be;

```c
    int main(int argc, char *argv[])
    {
        OCI_Connection* cn;
        OCI_Statement* st;
        OCI_Resultset* rs;
     
        OCI_Initialize(NULL, NULL, OCI_ENV_DEFAULT);
     
        cn = OCI_ConnectionCreate(L"localhost:1521/ORCLPDB1.localdomain", L"odb", L"oracle1", OCI_SESSION_DEFAULT);
        st = OCI_StatementCreate(cn);
     
        OCI_ExecuteStmt(st, L"select age, firstname from test_name");
     
        rs = OCI_GetResultset(st);
     
        while (OCI_FetchNext(rs))
        {
            printf("%i - %ls\n", OCI_GetInt(rs, 1), OCI_GetString(rs,2));
        }
     
        OCI_Cleanup();
     
        return EXIT_SUCCESS;
    }
```

**Comment by vrogier** [comment]
Closing the issue - Question answered and charset behaviors already described in the documentation
