### ISSUE TITLE
the first data change sometimes not be notified

### ISSUE THREAD

**Issue by linglongxian** [vrogier/ocilib#287]
i want to use the "data change notification" function in my application, but i find that sometimes the application does not get the notification about first data change. so i do the following simple test, and it still happened.

i insert three records, but the application only get two notifications. the first change is not notified.

environments: ubuntu16.04   oracle11 / oracle19c    ocilib4.7.3

codes:

EventHandler() and SetupNames() are copyed from the  notification.cpp

```c++
int main(int argc, char* argv[])
{
    SetupNames();
    try
    {
        Environment::Initialize(Environment::Events);

        Connection con("db", "user", "pwd");
        con.SetAutoCommit(true);

        Statement st(con);

        Subscription sub;
        sub.Register(con, "sub-00", Subscription::AllChanges, EventHandler, 5468, 0);
        sub.Watch("select * from testTable");

        while(1)
        WaitForEvents();
    }
    catch (std::exception &ex)
    {
        std::cout << ex.what() << std::endl;
    }

    Environment::Cleanup();
}
```

results:
![140728702-e6ef7c15-5a07-4297-89db-45f4210400b9](https://user-images.githubusercontent.com/36992313/140759449-4fdab647-1cac-4a2a-b6d7-0a5854e4c0d8.png)

**Comment by vrogier** [comment]
Hi,

I just made a test from your code (19.3 server and client on windows)  and I get the 3 notifications.
How long after running the app are you making the inserts ?

Regards,

Vincent

**Comment by linglongxian** [comment]
Hi, vrogier!  Thanks for your replying!

it happens not every time, but sometimes. so to reproduce it, maybe it need to try some times.

i update the codes and the result, print the time of starting the watch and the time of inserting.  so it may be clearer.

code:
`const ostring format = "YYYY-MM-DD HH24:MI:SS";
Connection *con = NULL;
int main(int argc, char* argv[])
{
    SetupNames();
    try
    {
        Environment::Initialize(Environment::Events);

        con = new Connection("db", "user", "pwd");
        con->SetAutoCommit(true);

        //Statement st(*con);
        //        st.Execute("CREATE TABLE testTable("
        //                    "id number(6) not null,"
        //                    "CreateTime Date default sysdate not null)");

        Subscription sub;
        sub.Register(*con, "sub-00", Subscription::AllChanges, EventHandler, 5468, 0);
        sub.Watch("select * from testTable");

        Date date = Date::SysDate();
        std::cout << "time for starting watch: " << date.ToString(format) << std::endl;

        while(1)
            WaitForEvents();
    }
    catch (std::exception &ex)
    {
        std::cout << ex.what() << std::endl;
    }

    Environment::Cleanup();
}`
`void EventHandler(Event &evt)
{
    std::cout << "** Notification : " << evt.GetSubscription().GetName() << std::endl;
    std::cout << "** Database     : " << evt.GetDatabaseName() << std::endl;
    std::cout << "** Event        : " << EventTypes[evt.GetType()] << std::endl;

    if (evt.GetType() == Event::ObjectChanged)
    {
        std::cout << ".... Object : " << evt.GetObjectName() << std::endl;
        std::cout << ".... Action : " << ObjectEvents[evt.GetObjectEvent()] << std::endl;
        std::cout << ".... RowID  : " << evt.GetRowID() << std::endl;

        Statement st(*con);
        st.Prepare("select id, CreateTime from testTable where rowid = :row_id");
        ostring rowid = evt.GetRowID();
        st.Bind(":row_id", rowid, 20, BindInfo::In);
        st.ExecutePrepared();

        Resultset rs = st.GetResultset();
        rs.Next();

        int id = rs.Get<int>(1);
        Date date = rs.Get<Date>(2);

        std::cout << "id: " << id << " time: " << date.ToString(format) << std::endl;
    }

    std::cout << std::endl;
}`
![Screenshot from 2021-11-08 21-44-56](https://user-images.githubusercontent.com/36992313/140753880-9d4beb3c-dfe6-4ed5-967c-56242640c10e.png)

results:

**Comment by linglongxian** [comment]
> Hi,
> 
> I just made a test from your code (19.3 server and client on windows) and I get the 3 notifications. How long after running the app are you making the inserts ?
> 
> Regards,
> 
> Vincent

Hi, vrogier! Thanks for your reply!

i have update more info about this issue in the comment. Could you look at it and make another test.

**Comment by vrogier** [comment]
Data change notification involves, at oracle client level, setuping a socket channel. How and how long and when Oracle client creates it, is a matter of the Oracle Client. Can be instant, a couple of seconds or more, we don't control on that.
For example, on windows, using local server/client, it is instant.
In production environments, between machines and OSes, this link can be longer to establish.
Your attached results show server time (created time on server) and client time (start watching time).
Is the client and server on same machine (might be time difference if not).
OCILIB data change notification relies purely on Oracle client built-in mechanisms. 
If making change right after starting watching misses first changes (within few seconds), it is then more at oracle client level.

Regards,

Vincent
