### ISSUE TITLE
Set Fetch\Prefetch not working with Execute

### ISSUE THREAD

**Issue by alexeyvo** [vrogier/ocilib#29]
Hi I noticed that when I do this:
```
  Statement st(cn);
  st.SetFetchSize(2);
  st.SetPrefetchSize(5);
  st.Execute("SELECT * from mytable");
```
getters returns values I set, however rows fetched using default values(20, 20) I used wireshark to confirm that.

But when I do this:
```
  Statement st(cn);
  st.Prepare("SELECT * from mytable");
  st.SetFetchSize(2);
  st.SetPrefetchSize(5);
  st.ExecutePrepared();
```
it fetch rows as expected. It think this should be fixed, or at least doc for setters should notice they should be called after prepare and getters should return actual values used.

**Comment by vrogier** [comment]
Hi,

You are correct.
Values were discarded with Oracle client > 9.2 as the statement handle are allocated in the prepare call instead at Statement object allocation time. The commit fixes the issue.

Regards,

Vincent
