### ISSUE TITLE
OcilibDirPathArrayToStream has a parameter row_from, but this is not used

### ISSUE THREAD

**Issue by Enni74** [vrogier/ocilib#290]
The function OcilibDirPathArrayToStream has a parameter row_from (which seems to be the row to start from), but this is not used internally. Shouldn't it be used in the following call as last parameter?
ret = OCIDirPathColArrayToStream(dp->arr, dp->ctx, dp->strm, dp->con->err, dp->nb_entries, (ub4) 0);

**Comment by vrogier** [comment]
Hi,

Indeed it would make more sense !
Let me review if for any reasons it was on purpose at that time or if it is something I forgot to use.

Regards,

Vincent

**Comment by vrogier** [comment]
Hi,

In fact, row_from in OcilibDirPathArrayToStream() is used to record the index of the errored row index in the list of errored rows, not for the call to oacle client call OCIDirPathColArrayToStream().
Thus, it is normal that the last parameter passed to OCIDirPathColArrayToStream() is 0.

Regards,

Vincent
