### ISSUE TITLE
OCI_DirPathLoad() can never returns in case of internal load errors (infinite loop)

### ISSUE THREAD

**Issue by Enni74** [vrogier/ocilib#298]
The following code is in OcilibDirPathLoad:

    while (OCI_DPR_ERROR == dp->res_load)
    {
        dp->res_load = OcilibDirPathLoadStream(dp);
    }

The problem here is: If a real error happens (tablespace full) it seems to try forever.

**Comment by vrogier** [comment]
Hi, 

Good catch!
I will commit a fix for it this week!

Thanks!

Vincent

**Comment by vrogier** [comment]
Hi,

I added a check that prevents the infinite loop if the number of loaded rows does not increase over iterations on failures.

Regards,

Vincent
