### ISSUE TITLE
Null binding

### ISSUE THREAD

**Issue by OCIntel** [vrogier/ocilib#300]
Bonjour Vincent,

Je voulais savoir comment dire au statement d'être en allocation interne depuis le C++ pour pouvoir passer des chaînes null en paramètre en mode InOut ?
Et de façon plus général, comment peut-on gérer en C++ le gestion des paramètres null en mode InOut ?

Merci d'avance !

**Comment by vrogier** [comment]
Hi,

OCILIB C API Internal allocation mode (OCI_BAM_INTERNAL) is not currently supported by the surface C++ API.
Current C++ binding API relies on C++ references which implies passing host variables.
Implementing internal allocation mode in C++ API  would require quite significant changes.
For handling nulls, you still have to bind host variable and then retrieve the BindInfo object from Statement::GetBind() and call BindInfo::SetNull() or BindInfo::SetNullAt() for array binds when a given bind value is null prior executing the statement.
Note that it has to be reverted back at next iteration if the next value is not null.

Regards,

Vincent
