### ISSUE TITLE
Wrong precision returned if querying string is a long one.

### ISSUE THREAD

**Issue by BCSN000001** [vrogier/ocilib#302]
Hi Vrogier,

On my side, I encountered a bug recently, if I use ocilib c++ api to query some data of stocks, for example, to query 4000 stocks daily data on some date,  the database table key is security code and trade date, security code is varchar(20) like '000001.SZ' while trade date is number(8) like 20220325. If I just query 10 stocks data, the result is correct, i.e., the precision function of column 'trade date' returns 8 while if I query 4000 stocks one time, the precision function of column 'trade date' returns 0 instead of 8. So, is there any limit of the query string.  I mean whether there is a limit length of query_str in below function.

                    ocilib::Statement st(db_inst);
			st.SetFetchMode(ocilib::Statement::FetchForward);
			st.Execute(query_str);
			ocilib::Resultset rs = st.GetResultset();

My platform is Visual Studio 2022 on Windows.

Many tks!

**Comment by vrogier** [comment]
Hi,

I don't really understand the issue.
Can you provide more issue information, technical information (oracle version, ocilib version, ....)  and sample code to reproduce the issue ?

thanks

Vincent

**Comment by BCSN000001** [comment]
I think I found the related warning

Warning
For numeric columns, the value may be not accurate at all! OCI does not allow to find out the real SQL precise type of an numeric column (int, real, ...). OCI based libraries can only 'guess' some types in some situations : float, binary_float, binary_float, number. For example:
with the statement 'select 101 from dual', OCI would report numeric type NUMBER.
if a column is declared as "INT", OCI would report also NUMBER.

In some situations, it guess an integer trade_date as NUMBER and the size is 22.
