### ISSUE TITLE
Object::Set specialized for Collection of Objects

### ISSUE THREAD

**Issue by mrfazlali** [vrogier/ocilib#305]
Hi Vincent.

ocilib has different specializations of Object::Set template function . but there is no one that takes an ocilib::Collection of ocilib::Object as parameter among them. neither there is no specialized version of Set function to takes a std::vector of ocilib::Object.
Object::Get function has specialized version for Collection .
I want to have one ocilib::object which one of its member is a Collection of another object. so how can i do that.

Thanks i advance .

**Comment by vrogier** [comment]
Hi, 

Default Object::Set<T>() implementation is reserved for collections.
You can see its usage in demo/geometry.cpp

Regards,

vincent

**Comment by mrfazlali** [comment]
Hi again Vincent.
You are right , I could accomplish that by looking at that demo.
Thanks for your help.
