### ISSUE TITLE
Compile error under GCC when accessing to an ocilib::Collection item

### ISSUE THREAD

**Issue by mrfazlali** [vrogier/ocilib#306]
Hello Vincent. 

I have a problem with compiling the code below  . The code is from demo/coll.cpp . 

`void print_const_coll_by_index(const ocilib::Collection<ocilib::Object> & coll)
    {
        std::cout << "fetch using const index access" << std::endl;

        unsigned int i = 1, n = coll.GetCount();

        for (; i <=n ; i++)
        {
            auto elem = static_cast<ocilib::Object>(coll[i]);
           // some code here
        }
    }`

and here is the compile time error :

`/usr/local/include/ocilibcpp/detail/Collection.hpp:491:13: error: invalid conversion from ‘const ocilib::Collection<ocilib::Object>*’ to ‘ocilib::CollectionElement<ocilib::Object>::CollectionType*’ {aka ‘ocilib::Collection<ocilib::Object>*’} [-fpermissive]
  491 |     return  CollectionElement<T>(this, index);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |             |
      |             const ocilib::Collection<ocilib::Object>*
`

* If i change function declaration and remove const , the code will get compile successfully. 

`void print_const_coll_by_index(ocilib::Collection<ocilib::Object> & coll)`

My OS is fedora  34 and gcc version is 11.2.1

Thanks a lot.

**Comment by mrfazlali** [comment]
Hi again Vincent.
is there any way for me to change ocilib code and build it again to solve this issue.
I'll be really grateful if you could give me some hint to fix this.

Thanks a lot .

**Comment by mrfazlali** [comment]
Hi.

I tried to change ocilib code to solve this issue . so here is what i did .

In types.hpp file , i change the constructor and private member of CollectionElement class . so here is the changed code.

`    template<class T>
    class CollectionElement
    {
        template<class>
        friend class CollectionIterator;

    public:

        typedef T ValueType;
        typedef Collection<ValueType> CollectionType;

        CollectionElement();
        CollectionElement(const CollectionType * coll, unsigned int pos);
        operator T() const;
        CollectionElement& operator = (const ValueType& other);
        CollectionElement& operator = (const CollectionElement& other);
        bool IsNull() const;
        void SetNull();

    private:

        const CollectionType * _coll;
        unsigned int _pos;
    };`

I also changed the implementation of constructor in CollectionElement.hpp file .

and I think it did the trick . It seems that it solved my problem .

**Comment by vrogier** [comment]
Hi,

The code from demo/coll.hpp compiles fine under Windows.
I will check again with GCC (might have forgot to test it under GCC)
If I get same issue, I will address it in v4.7.5

Regards,

Vincent

**Comment by vrogier** [comment]
Hi,

the issue seeems logical - MSVC seems to to detect it.
I will fix differently by adding a const_cast to remove the const on this in Collection<T>::operator [](unsigned int index) const
