### ISSUE TITLE
Memory leak in C++ Resultsets?

### ISSUE THREAD

**Issue by SivitriScarzam** [vrogier/ocilib#31]
Hi vrogier,

I've been diagnosing a memory leak in an application I'm writing that uses C++ OCILIB. This is my minimal diagnostic program:

```c++
#ifdef OCI_CHARSET_ANSI
#undef OCI_CHARSET_ANSI
#endif
#ifndef OCI_CHARSET_WIDE
#define OCI_CHARSET_WIDE
#endif

#include <ocilib\ocilib.hpp>

#ifdef _MSC_VER

#if defined(OCI_CHARSET_WIDE)
#pragma comment(lib, "ocilibw.lib")
#elif defined(OCI_CHARSET_ANSI)
#pragma comment(lib, "ociliba.lib")
#endif

#endif

#ifndef OCI_SHARED_LIB
#if defined(_WINDOWS)
#if defined(OCI_CHARSET_WIDE)
#define OCI_SHARED_LIB                   "ocilibw.dll"
#else
#define OCI_SHARED_LIB                   "ociliba.dll"
#endif
#else
#define OCI_SHARED_LIB                   "libocilib.so"
#endif
#endif

using namespace ocilib;

void testDataRetrievalMemoryLeak()
{
    Environment::Initialize();
    Connection dbConnection1;
    dbConnection1.Open(service, usr, pwd);
    Statement st(dbConnection1);
    for (int i = 0; i < 10000; i++) {
        wstring sel = L"select 'test' from dual";
        st.Execute(sel);
        Resultset rs = st.GetResultset();
    }
    dbConnection1.Close();
    Environment::Cleanup();
}

int main(int argc, char *argv[])
{
    testDataRetrievalMemoryLeak();
    return 0;
}
```

I have found that without the line `Resultset rs = st.GetResultset();`, the test application's memory usage is flat. With it, it grows without bound. 

I diagnosed with the Performance Monitor on a Windows Server 2012 machine to get a broad idea of memory growth. 

From my own investigations, I noted that the C function `OCI_ReleaseResultsets` is never called from C++, which means neither is `OCI_ResultsetFree`, since Resultsets in C++ are created without a HandleFreeFunc function. 

Any insight on this, or am I using OCILIB incorrectly?

**Comment by vrogier** [comment]
Hi,

Resultsets do not have to be freed by applications. 
There are automatically freed by statements. 
OCI_ReleaseResultsets() is an optional call for applications that want to free asap resultsets without waiting for the statement destructor to free them.

The issue you are encountering is a known Oracle Bug related to Unicode.
If you build your application using OCI_CHARSET_ANSI / ociliba.dll, you'll notice that there will be no leak at all.
When OCILIB creates a resultset, it gathers information about all columns in the resultset (name, type, ...). 
The Oracle client method that returns the column name is leaking when the oracle client is initialized in Unicode mode. 
I've entered a bug few years ago on metalink/oracle support when i still had at that time access to it. The bug has been confirmed by Oracle and they've planned to fix in 11gR2  But apparently they did not fixed it. As I do not have access to oracle support anymore, I cannot check the bug status.
I've tried to find a workaround for that Oracle bug in OCILIB without success :(

Unfortunately, There is nothing i can do about it!
I will try again to find a workaround but don't expect any resolution.

Best regards,

Vincent

**Comment by vrogier** [comment]
Picked from the Oracle Documentation of the Oracle Client call OCIAttrGet():

> In UTF-16 mode, particularly when executing a loop, try to reuse the same pointer variable corresponding to an attribute and copy the contents to local variables after OCIAttrGet() is called. If multiple pointers are used for the same attribute, a memory leak can occur.

The funny thing is it only happens for the column name (attribute OCI_ATTR_NAME)...

**Comment by FladoToo** [comment]
Do you mean "Bug 9838993 : OCI: MEM LEAK OCIATTRGET() W. OCI_ATTR_NAME RUN IN MODE OCI_UTF16"? 
That one is in status "92 - Closed, Not a Bug". No explanation in the description.

**Comment by vrogier** [comment]
Yes, that is the one  !

**Comment by vrogier** [comment]
That's funny because:
- Last time i had access to that bug i entered on oracle support it was confirmed by oracle stuff as a bug and planned for 11gR2
- At that time, OCIAttrGet() Oracle documentation did not mention the part related to leaks in UTF16 mode
- Thus they've closed the bug as "not a bug" and added a mention to the leak in the doc.

This is not nice as lots of OCI wrappers in various language are describing columns (and thus gather column name) when they execute a statement even in UTF16 mode.

So, they force these libs, including OCILIB, with an awful bug when using UTF16...

Vincent

**Comment by vrogier** [comment]
If any of you with oracle support access can challenge Oracle about that issue, I would be interested :)

**Comment by FladoToo** [comment]
Yes, I feel your pain, but I cannot request them to reopen this bug - it only affects Windows clients and we only talk to oracle from Unix.

**Comment by vrogier** [comment]
And the worse in the end is that after doing some retro engineering in the memory layout, we can retrieve the column name without leak and using much less CPU in both ansi and UTF16 modes !!

currently, OCILIb is retrieving the column name in column.c using : 
        
        OCI_CALL1
        (
            res, con, stmt,

            OCIAttrGet((dvoid *) param, (ub4) OCI_DTYPE_PARAM, (dvoid *) &dbstr,
                       (ub4 *) &dbsize, (ub4) attrname, con->err)
        )


the param variable is an opaque pointer to internal OCI structure. After analyzing the memory, I found a way to access directly to the column name:

        struct column_param_dummy4
        {
            void *dummy1;
            void *dummy2;
            void *dummy3;
            void *dummy4;
            void *dummy5;
            void *dummy6;
            char *column_name;
        };

        struct column_param
        {
            void *dummy1;
            void *dummy2;
            void *dummy3;
            struct column_param_dummy4 *dummy4;
        };


        struct column_param *cp = (struct column_param*)param;

       //   cp->dummy4->column_name Is the column anme is ANSI !!

Arghh!!!!

**Comment by vrogier** [comment]
I can't rely on that retro engineering in OCILIB as Oracle may change its internal structure.
But what I can do is :
- by default do as today with the leak in UTF16
- add the possibility to handle that issue with a environment variable. If the environment variable is set, then access the column name directly.

**Comment by SivitriScarzam** [comment]
This situation with Oracle not fixing memory leaks in OCI is so aggravating! I've had to deal with the environment leak and now this leak in column names?

Thanks for your effort with OCILIB and being so responsive. I'll start a workaround for myself, but your approach to retro engineering the column names would be cool to have.

**Comment by vrogier** [comment]
I will work on it and try to see if I can get an acceptable workaround not impacting the library based on what I've exposed earlier on :)

**Comment by vrogier** [comment]
Hi,

I've just committed a workaround for that bug that can be activated using an environment variable.
This is a rough commit. 
Let me know if it work for you and if the way to activate it must be enhanced or refactored

Best regards,

Vincent

**Comment by AlexanderSchukin** [comment]
Hello Vincent,
Thank you for your library and your effort to support and bugfixing. This workaround also works fine for me on Oracle11.2.0.3.0.
I fully understand that this bug is exceptionally Oracle bug.
Just wanted to ask,  do you have a possibility to use workaround that they proposed? I mean -
`to reuse the same pointer variable corresponding to an attribute and copy the contents to local variables after OCIAttrGet() is called.`
