### ISSUE TITLE
Pool::GetConnection waits for an infinite time on network failure or disconnection 

### ISSUE THREAD

**Issue by mrfazlali** [vrogier/ocilib#311]
Hello Vincent.
I have a problem.
Suppose network failure or disconnection happens during running of application.
When creating Pool Object , if the network get disconnected somehow , it will throw an exception.
but after that, i mean when pool is created , if network is disconnected , calling pool.GetConnection() cause infinite waiting and it never returns .

here is an example to simulate the situation . 

`
_
Environment::Initialize();

Pool pool(db, user, pass, Pool::PoolType::Type::ConnectionPool, 1 , 10, 1);
pool.SetNoWait(true);

// Sleep here for a while so i can disconnect network
std::this_thread::sleep_for(std::chrono::seconds(20));

auto conn = pool.GetConnection();      // It blocks for ever.

conn.Close();
Environment::Cleanup();
_
`
os : fedora 36 
gcc version : 12.
Thanks in advance

**Comment by vrogier** [comment]
Hi,

you can tune the sqlnet.ora in order to palliate such situations (see for timeout settings)

Regards,

Vincent
