### ISSUE TITLE
windows vs2019 OCI_ERR_LOADING_SHARED_LIB

### ISSUE THREAD

**Issue by hewittzgh** [vrogier/ocilib#315]
@vrogier 
Hi! I am trying to use ocilib. my environment is win11, vs2019. my `C` code is as follows:

```
OCI_Connection* oracle_cn;
OCI_Statement* oracle_st;
OCI_Resultset* oracle_rs;


if (!OCI_Initialize(oracle_err_handler, NULL, OCI_ENV_DEFAULT))
{
printf("Init Fail!");
return EXIT_FAILURE;
}

// ...
```
The function "OCI_Initialize" can not work. I get `OCI_ErrorGetType` and `OCI_ERR_LOADING_SHARED_LIB` error.
I tried the method in the [link,](http://vrogier.github.io/ocilib/doc/html/group___ocilib_c_api_connections.html#ga47258f61e45f047ebca8e8b13b9d89e7) but I couldn't solve it.
Can you give me some suggestions?

**Comment by hewittzgh** [comment]
PS: I install the ocilib 4.7.3 package through NuGet package manager. Of course, I had tested 4.7.2/4.7.1/4.7.0 version and tried to install it by configure the vs project manually, but it never worked.

**Comment by vrogier** [comment]
Hi,

Have you install an oracle client or downloaded an instant client package?
If not, there error is normal.
OCILIB relies on oracle OCI client libraries to interact with Oracle databases.

Regards,

Vincent

**Comment by hewittzgh** [comment]
Thanks! I will try. If it works, I will close the issue.

**Comment by hewittzgh** [comment]
@vrogier Hi! I have solved the initialization problem. But when I connect the oracle server, I find the `OCI_ConnectionCreate` api return NULL. My OCI client library version is [11.2.0.4.0](https://www.oracle.com/database/technologies/instant-client/winx64-64-downloads.html) basic. Do you known what causes this problem? Thank you!
My code:
`oracle_cn = OCI_ConnectionCreate("<ip>:<port>", "<username>", "<password>", OCI_SESSION_DEFAULT);`

**Comment by vrogier** [comment]
The first parameter can be:
- a full connection string 
- a tns alias
- a easy connect string 

You can check oracle documentation for more details.

In your example, the easy connect string is not correct.

Easy connect string is host:port/servicename.

Regards,

Vincent

**Comment by vrogier** [comment]
Hi, Any news ?

**Comment by vrogier** [comment]
Closing the issue as no news from OP and given information provided, invalid connection string was used.
