### ISSUE TITLE
I encountered a confusing issue

### ISSUE THREAD

**Issue by krosjean** [vrogier/ocilib#317]
I built the development environment under Windows 11 , MingW64, GCC, Clion. Everything seemed OK.
Then I wrote a simple piece of test code which was compiled and run successfully,  but to my surprise,  no record was fetched however.
Cound you  please give any guidance?  Thanks a lot .  Apologize for my inept English and programming  :-)

```c++
#include <iostream>

#include "ocilib.hpp"

#ifdef OCI_CHARSET_ANSI
#undef OCI_CHARSET_ANSI
#endif
#define OCI_CHARSET_ANSI UTF-8
#define  ENDL '\n'

using namespace ocilib;
using std::cout;

int main() {
    ostring db("ORACLE19C");
    ostring user("CUSER");
    ostring pwd("xxxx");

    try
    {
        Environment::Initialize();
        Connection   con(db, user, pwd);
        Statement    stmt(con);

        stmt.Execute("select 1 as num from dual");
        Resultset rs = stmt.GetResultset();
        if (!rs) {
            cout << "Null RecordSet" << ENDL;
        }
        else {
            cout << "Num of Rows:" << rs.GetCount() << ENDL;
        }
    }

    catch (std::exception &ex)
    {
        std::cout << ex.what() << ENDL;
    }

    Environment::Cleanup();

    return EXIT_SUCCESS;
}
```

**Comment by vrogier** [comment]
Hi,

In your sample code, you did not fetch rows from the resultset.
rs.GetCount() returns the number of rows fetched by the application, in this case, none.
You need to keep fetching rows using rs.Next() or rs++ until it returns false.
After each fetch call, you retrieve values at the current row for each column using rs.Get<T>() either by column index or name.

Regards,

Vincent

**Comment by vrogier** [comment]
By the way, you cannot define OCI_CHARSET_ANSI the way you do.
This macro is not supposed to have any value.
By default, it is automatically defined.

**Comment by krosjean** [comment]
Thank you very much, Vincent !    I've got it all figured out
