### ISSUE TITLE
Cancel/Terminate/Stop connection request

### ISSUE THREAD

**Issue by unficyp** [vrogier/ocilib#321]
First, thanks for this great library!

Lets say i enter a non-existing db or the IP behind the service name is not reachable in Connection con("db", "usr", "pwd") - the connect would fail after a timeout.
Whats the best way to cancel/stop/terminate the connection request ? (from a Qt application)
I tried to put the connect into a separate thread - but stop/exit the thread does not work and a terminate dumps out some interal oracle library stuff:
```
ORA-24550: signal received: [si_signo=6] [si_errno=0] [si_code=-6] [si_int=0] [si_ptr=(nil)] [si_addr=0x3e80002e445]
kpedbg_dmp_stack()+394<-kpeDbgCrash()+204<-kpeDbgSignalHandler()+113<-skgesig_sigactionHandler()+258<-__sighandler()<-pthread_key_delete()+332<-0x0000564069B24BD0<-0x0000564069B24BD0<-0x0000564069B24BD0<-0x0000564069B24BD0<-0x0000564069B24BD0<-0x0000564069B24BD0<-0x0000564069B24BD0<-0x0000564069B24BD0<-0x0000564069B24BD0<-0x0000564069B24BD0<-0x0000564069B24BD0<-0x0000564069B24BD0<-0x0000564069B24BD0<-0x0000564069B24BD0<-0x0000564069B24BD0<-0x0000564069B24BD0<-0x0000564069B24BD0<-0x0000564069B24BD0<-0x0000564069B24BD0
```

thanks in advance

**Comment by vrogier** [comment]
Hi,

OCI_Break() can be used for aborting long running calls on a connection.
But there is no built-in mechanisms provided Oracle OCI client to do that when connecting to a database (when using OCI in blocking mode).
You can reduce/customize the timeout in the sqlnet.ora file.
I am not aware of any other means.

Regards,

Vincent

**Comment by unficyp** [comment]
guess i will run the connect in a separate thread to not block the rest of the UI and let the connect run or "fake" the cancel with removing the connection dialog but leave the connect running inthe background until the timeout occurs.

thanks :)
