### ISSUE TITLE
C++ API: Exception GetMessage

### ISSUE THREAD

**Issue by unficyp** [vrogier/ocilib#322]
Hi,
using Version 4.7.4, how can i get the plain Oracle error message in an exception ?
GetMessage always includes "Error occurred at xxx:" - do i have to cut this string out by myself ?

thanks in advance,
gerald

**Comment by vrogier** [comment]
Hi,

Oracle original error codes in the C++ API are available using Exception::GetOracleErrorCode().
For Error messages, Exception::GetMessage() content  can be issued by Oracle or by OCILIB itself (C API and C++ API)  and  code location of the error is indeed prepended to the final exception message by either OCILIB C or C++ API.
Currently there is no way, out of the box, to get only the Oracle Error string.
Adding dedicated primitives to both C and C++ API for exposing only error messages issued by oracle would make the API more complex.
I will see what I do about it.

Regards,

Vincent

**Comment by unficyp** [comment]
thanks, not that important :) right not i remove every text until the first colon.

**Comment by vrogier** [comment]
Closing the issue as there will be not change related to it in the short term.
