### ISSUE TITLE
oculib and openssl have type conflicts

### ISSUE THREAD

**Issue by jacky526** [vrogier/ocilib#33]
my c++ code is :

```
#include <stdio.h>

#include <ocilib.h>
#include <openssl/crypto.h>
#include <openssl/ssl.h>
#include <openssl/err.h>
#include <openssl/rand.h>

int main(int argc, char *argv[])
{
	printf("Hello, world\n");
	
	return 0;
}
```

Compile error is :
In file included from /usr/include/openssl/objects.h:960,
                 from /usr/include/openssl/evp.h:98,
                 from /usr/include/openssl/x509.h:73,
                 from /usr/include/openssl/ssl.h:156,
                 from ocitest.c:5:
/usr/include/openssl/asn1.h:526: error: multiple types in one declaration
/usr/include/openssl/asn1.h:526: error: declaration does not declare anything

I found that /usr/include/openssl/asn1.h:526 boolean variable is conflicts with ocilib.h:#define boolean int

 I replace it to OCIBoolean, and than is Compile successfully.

Poor English, please forgive me.
thx!

**Comment by jacky526** [comment]
`
#include <ocilib.h>
#include <openssl/crypto.h>
#include <openssl/ssl.h>
#include <openssl/err.h>
#include <openssl/rand.h>
`

**Comment by vrogier** [comment]
Hi,

This is a known issue regarding mixing openssl/openssh headers and other libraries.
ocilib.h must be included after any openssh headers...

Do you know why ? openssh had the brilliant idea to declare one of their structure members (struct asn1_type_st in asn1.h) with the name 'boolean' that is a type declared by ocilib but also internally by oci. It is even used as a type name in some win32 header files !!!!
So the problem would be the same with a pure oracle oci code or a native windows headers.

Thus, you have 2 options:
1 - Include ocilib.h after openssh headers
2 - undef boolean before openssh headers inclusion and redefines it after 

Regards,

Vincent

**Comment by jacky526** [comment]
Thank you!
