### ISSUE TITLE
Error occurred at OcilibEnvironmentInitialize: Cannot load OCI shared library (oci.dll)

### ISSUE THREAD

**Issue by MagicXran** [vrogier/ocilib#336]
I use vcpkg to install ocilib 4.7.5 and integrate project in vs2019, But the runtime to report an error: "Error occurred at OcilibEnvironmentInitialize: Cannot load OCI shared library (oci.dll)"，I have reinstalled it many times with vcpkg. How to solve it?

**Comment by MagicXran** [comment]
The version I installed is ocilib:x86-windows runs in Debug x86 environment.

**Comment by vrogier** [comment]
Hi,

The reported error means that the Oracle Client library cannot be loaded by OCILIB. It is either missing on the machine or not accessible from current process.

Make sure you have either installed an Oracle client and are using an instant Oracle client.

Regards,

Vincent

**Comment by MagicXran** [comment]
yeah, That's it. It was my fault.~ but
