### ISSUE TITLE
Why does ocilib::Resultset restrict the default construct?

### ISSUE THREAD

**Issue by MagicXran** [vrogier/ocilib#345]
Sometimes I want to declare an empty ocilib::Resultset to receive the result set, but the constructor has been privatized. Why? Any concerns?

**Comment by vrogier** [comment]
Hi,

A resultset only make sense within the context of his Statement object.
You can store Statement object and call ist method GetResultset() that will return the same resultset.
A resultset is not a standalone object as in underlying OCI, the concept of resultset does not exist and  this is the statement handle that is used to fetch data.
View the the Resultet as conceptual interface to data accessible from an executed statement.

Vincent.
