### ISSUE TITLE
crash with using change notification

### ISSUE THREAD

**Issue by Miki-123** [vrogier/ocilib#346]
Hi Vincent,

I would like to report you an error in subscription.c. In function OcilibSubscriptionRegister you call free(sub) in a cleanup section on line 338. But in function OcilibSubscriptionUnregister(sub) which is called before, you call free(sub) too (on line 370). It caused double free crash.

Best regards and thanks for your work on this project
Miki

**Comment by vrogier** [comment]
Hi,

This has already been fixed in v4.7.6 and is a duplicate of issue #323 

Closing this issue.

Regards,

Vincent
