### ISSUE TITLE
Using OCI_SetFetchMode(st, OCI_SFM_SCROLLABLE); with long column type

### ISSUE THREAD

**Issue by pierre-laplante** [vrogier/ocilib#35]
If I use OCI_SetFetchMode(st, OCI_SFM_SCROLLABLE);
and try to read a table with a long column type, the call
OCI_FetchLast does not work.

If I remove the column DATA_DEFAULT, it will work.

If I remove OCI_SetFetchMode(st, OCI_SFM_SCROLLABLE), the program will work but I will not really know the number of row return until I fetch them all but I need to know it prior to fetch them.

What I want is the number of rows return from the select even if they are more than 20 rows...
So I fetch the last record to get the number of row. Is there a better way?

Here is the program:

#include "ocilib.h"

    int main(int argc, char *argv[])
    {
        OCI_Connection* cn;
        OCI_Statement* st;
        OCI_Resultset* rs;

        OCI_Initialize(NULL, NULL, OCI_ENV_DEFAULT | OCI_ENV_CONTEXT);

        cn = OCI_ConnectionCreate(...)
        st = OCI_StatementCreate(cn);
        OCI_SetFetchMode(st, OCI_SFM_SCROLLABLE);

        OCI_ExecuteStmt(st, "SELECT COLUMN_NAME,DATA_DEFAULT  FROM ALL_TAB_COLUMNS WHERE OWNER='B2BTRUST' and TABLE_NAME='ADNOVE_CAMPAGNES' ORDER BY COLUMN_ID");

        rs = OCI_GetResultset(st);
        OCI_FetchNext(rs);
        fprintf(stderr, "1 row=%d\n", OCI_GetRowCount(rs));
        OCI_FetchLast(rs);
        fprintf(stderr, "2 row=%d\n", OCI_GetRowCount(rs));
        OCI_FetchFirst(rs);

        do {
            printf("v1 %s\n", OCI_GetString(rs,1));
        } while (OCI_FetchNext(rs));

        OCI_Cleanup();

        return EXIT_SUCCESS;
    }

**Comment by vrogier** [comment]
Hi,

You cannot use scrollable cursors when resulsets contain LONG column.

Here is an extract of the from Oracle documentation : 

"Oracle does not support DML operations on scrollable cursors. A cursor cannot be made scrollable if the LONG datatype is part of the select list."

Best regards,

Vincent
