### ISSUE TITLE
OCI_Break has no effect when called under linux

### ISSUE THREAD

**Issue by Zeks** [vrogier/ocilib#36]
I have an app that is compiled for both windows 64bit and linux (centos 6.5)  32bit. 
OCI_Break only works on windows (I call it from a separate thread).
On linux it is definitely called, and definitely from a thread, but the thread which is locked up by ocilib call never unlocks upon OCI_Break's execution an continues to hang until DB connection is reestablished.

P.S. I tried on both ocilib 3.x and the latest one from repo

**Comment by vrogier** [comment]
Hi,

Can you provide a sample code that leads to the issue?

Thanks,

Vincent

**Comment by Zeks** [comment]
tha might be a little tricky as we use Qt. I will see if I can whip up an example without qt::concurrent or qtthread tomorrow

**Comment by vrogier** [comment]
Hi,

Any news ?

Without response, i would have to close the issue.

Regards,

Vincent

**Comment by Zeks** [comment]
Crap, I got sick and forgot about this completely >_< Sorry, I will try to provide a sample this weekend

**Comment by vrogier** [comment]
thanks :)

**Comment by Zeks** [comment]
Updating on the issue:
It's not that oci_break doesn't work. it's that it _cant_ work when network cable has been physically disconnected. However, the difference is:

On windows after a relatively short timeout you get: ORA-12152: TNS:unable to send break message

On linux it just freezes indefinitely which is really, really bad, because it stops any attempt at error processing.

**Comment by rajeshm9** [comment]
Please check with following parameter defined at sqlnet.ora

SQLNET.SEND_TIMEOUT = 60
SQLNET.RECV_TIMEOUT = 60
TCP.CONNECT_TIMEOUT = 60
SQLNET.INBOUND_CONNECT_TIMEOUT = 60

**Comment by Zeks** [comment]
That was exactly what I needed, thanks.
