### ISSUE TITLE
Update OCILIB User Guide 

### ISSUE THREAD

**Issue by x0d3r** [vrogier/ocilib#37]
Would be great to have the user guide updated.

**Comment by vrogier** [comment]
Hi,

It would be great to have enough time to update it ;)
It takes a lot of time to write this kind of guide!
And unfortunately, I don't currently have time for it.
Maintaining, supporting and extending the library consume the entire time I can allocate to OCILIB.

If anybody is interested in contributing to Ocilib documenation and guide, let me know.

Vincent
