### ISSUE TITLE
Direct Path API need to support Oracle native datatypes, not strings only

### ISSUE THREAD

**Issue by dbpm** [vrogier/ocilib#42]
OCI_DirPathSetEntry by default is able to handle string values only; DATE, TIMESTAMP, NUMBER values must be passed as C-like strings only, with further conversion.

That is not true for general case, such conversion can lead to data loss issues and has some performance drabacks.

Moreover - string conversion does not allow to convert/pass some values: 
* DATE value, which is presented by all zeroed bytes in DUMP(), those can be found in PL/SQL Profiler tables);
* some DATE values which is produced by JDBC the same way (JDBC client passes all zeroes in buffer, but some conversion still happens);
* TIMESTAMP WITH TIMEZONE values with textual timezone info, like Europe/Moscow - those values will be silently converted into absolute offset, -03:00, losing textual part, it's known OCI limitation 

Main goal is to be able to SELECT DUMP(x, 16) values from source database, covert them from textual hexadecimal back to native binary format and to pass to Direct path API calls AS-IS - that way it will be possible pass practically any value which is valid from source database point of view.

Taking values from OCI_Date and OCI_Timestamp is not an option - Oracle converts DATE values when passes them to client, and for TIMESTAMP values it's not possible to lookup into raw buffer - only handles are visible. 

As result there is no need to extend list of existing OCILIB functions. We can extend existing ones next backward compatible way:

OCI_DirPathSetColumn() - if maxsize will be set to 0 and format to NULL - that can set mode to proceed with binary/no-conversion way for further OCI_DirPathSetEntry() calls; 
for DATE, TIMESTAMP WITH TIME ZONE, TIMESTAMP WITH LOCAL TIME ZONE and TIMESTAMP the
dbcol->sqlcode should be set to SQLT_DAT, SQLT_TIMESTAMP_TZ, SQLT_TIMESTAMP_LTZ and... suddenly, 180, instead of SQLT_TIMESTAMP (I don't know why but it works that way only), respectively

where

OCI_DirPathSetEntry() - will take value as void pointer which we can point it to source buffer, which was built from source hexadecimal DUMP(x, 16) database function output.

Please note - for DATE values the buffer is practically always 7 byte structure
For TIMESTAMP values it can be either 11 or 7 byte structure, it depends on part which encodes fractional part of second. The same is true for TIMESTAMP WITH LOCAL TIME ZONE
For TIMESTAMP WITH TIMEZONE value size is always 13 byte structure, as I see.
For NUMBER values buffer size varies, up to 22 bytes in total.

But size of exact value is derived from database, so OCI_DirPathSetEntry() must always take into account user specified size argument

**Comment by vrogier** [comment]
As most of the time, direct path is used with text files, its support was made using string in OCILIB.
You're right indeed. It is a nice enhancement.

**Comment by dbpm** [comment]
Also I think it's worse to be able to handle BINARY_FLOAT, BINARY_DOUBLE the same way, though I have not faced with those types yet:
https://support.oracle.com/knowledge/Oracle%20Database%20Products/1315200_1.html

and INTERVAL types - those do work fine with current textual conversion at the moment, but taking into account that such conversion is potentially buggy - I'd copy them using DUMP()ed values as well.

**Comment by dbpm** [comment]
Final findings for today:

1) While DATE, TIMESTAMP values can be copied  using
    memcpy(data, value, (size_t) size);

the NUMBER raw values need to be copied using

    memcpy(data, value, (size_t) size + 1);

due subsequent

        dpcol->lens[row-1]  = size;

2) Also I was not able to find any documented example how to handle the TIMESTAMP values for Direct Path API properly, in terms of the sqlcode values - do we need to specify SQLT_ ones or actual DUMP() Types, probably it worse to debug SQL*Loader calls - gbd is able to set breakpoint on OCIAttrSet()

Accodring to the next link 
https://ellebaek.wordpress.com/2011/02/25/oracle-type-code-mappings/

for NUMBER and DATE the SQLT_NUM, SQLT_DAT and DUMP()ed type codes are the same (2 and 12, respectively), 


while for timestamps those differ, and each type has own behavior:

for TIMESTAMP WITH LOCAL TIMEZONE only 232 (SQLT_TIMESTAMP_LTZ) - fits, DUMP() shows 231 as result, if we initially specify 231 then OCI gives AV error.

for TIMESTAMP WITH TIMEZONE both 181 and 188 (SQLT_TIMESTAMP_TZ) work fine, DUMP() shows 181 as result but 

for TIMESTAMP only 180 fits, while 187 code, i.e. SQLT_TIMESTAMP gives conversion result.
DUMP() shows 180

So there is no unambiguous way how to handle sqlcode for the TIMESTAMPs, unfortunately.

**Comment by vrogier** [comment]
Closing this issue (7 years old) as it won't be addressed in a near future.
