### ISSUE TITLE
OCI_IsNull OCI_GetObject strange behaviour

### ISSUE THREAD

**Issue by albertino80** [vrogier/ocilib#48]
I'm using version 4.2.1 downloaded sources released under "releases" section.

SQL File to generate problem: create_table.sql
Code to generate problem: test_case.cpp

Using staticcaly liked c++ ocilibfiles with this preprocessor defines:
OCI_CHARSET_ANSI
OCI_IMPORT_RUNTIME

IDE/Compiler: Visual Studio 2010

Symptoms:
1 wrong OCI_IsNull return value when (FIELD01 = 31 and FIELD02 = 00015)
2 hangs immediately after that

Stranges:
If I change "order by FIELD01,FIELD02" with "order by FIELD02" all goes right.

I suspect the problem is noly presenting when object type columns are used (as MDSYS.SDO_GEOMETRY).

[test_files.zip](https://github.com/vrogier/ocilib/files/297670/test_files.zip)

Thanks for your precious work.

**Comment by vrogier** [comment]
Hi,

using provided files (sql and code), I get correct output:

```
5 - 00036 - GEOM Is NOT NULL, GTYPE: 2001
5 - 00037 - GEOM Is NOT NULL, GTYPE: 2001
5 - 00038 - GEOM Is NOT NULL, GTYPE: 2001
5 - 00051 - GEOM Is NOT NULL, GTYPE: 2001
5 - 00052 - GEOM Is NOT NULL, GTYPE: 2001
5 - 00095 - GEOM Is NOT NULL, GTYPE: 2001
5 - 00098 - GEOM Is NOT NULL, GTYPE: 2001
7 - 00036 - GEOM Is NOT NULL, GTYPE: 2001
7 - 00086 - GEOM Is NOT NULL, GTYPE: 2001
7 - 00128 - GEOM Is NOT NULL, GTYPE: 2001
30 - 00059 - GEOM Is NOT NULL, GTYPE: 2001
30 - 00060 - GEOM Is NOT NULL, GTYPE: 2001
30 - 00085 - GEOM Is NULL
30 - 00086 - GEOM Is NOT NULL, GTYPE: 2001
30 - 00087 - GEOM Is NOT NULL, GTYPE: 2001
30 - 00094 - GEOM Is NOT NULL, GTYPE: 2001
30 - 00095 - GEOM Is NOT NULL, GTYPE: 2001
30 - 00096 - GEOM Is NOT NULL, GTYPE: 2001
30 - 00097 - GEOM Is NOT NULL, GTYPE: 2001
30 - 00152 - GEOM Is NOT NULL, GTYPE: 2001
30 - 00154 - GEOM Is NOT NULL, GTYPE: 2001
30 - 00156 - GEOM Is NOT NULL, GTYPE: 2001
31 - 00015 - GEOM Is NULL
31 - 00043 - GEOM Is NOT NULL, GTYPE: 2001
31 - 00044 - GEOM Is NOT NULL, GTYPE: 2001
31 - 00153 - GEOM Is NULL
```

Testes using latest GIT repository code, win32./win64 builds of ocilib, Oracle 12g regular client and instant client

By the way, you shall not call OCI_ObjectFree() on a fetched object!

Best regards,

Vincent

**Comment by albertino80** [comment]
You are right!

OCI_ObjectFree caused the hang.

Using "Instant Client Package 11.2.0.1.0" when FIELD01=31 and FIELD02='00015' i get:
"31 - 00015 - GEOM Is NOT NULL, GTYPE: 0"

Using "Instant Client Package 12.1.0.2.0" i get:
"31 - 00015 - GEOM Is NULL"

In the underlying table the value of that field is NULL.

Something strange on "old" Oracle client libraries. With 11 Version, OCI_IsNull on MDSYS.SDO_GEOMETRY is not always reliable.
