### ISSUE TITLE
SIGSEGV in oci_getraw for varbinary (variable binary[raw])  -   timesten

### ISSUE THREAD

**Issue by amirhakh** [vrogier/ocilib#52]
hello
i received signal SIGSEGV when call fetch next on result of select query with varbinary column in timesten (direct|client) connection.
i was write a sample query in OCI (not ocilib) for "select \* from my_table"  and get my data in var binary format.

can fix this bug!

stack trace:
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff33a14c5 in __intel_new_memset ()
   from /opt/oracle/product/12.1.0/dbhome_1/lib/libclntsh.so.12.1
(gdb) bt
#0  0x00007ffff33a14c5 in __intel_new_memset ()

   from /opt/oracle/product/12.1.0/dbhome_1/lib/libclntsh.so.12.1
#1  0x00007ffff339eed6 in _intel_fast_memset.J ()

   from /opt/oracle/product/12.1.0/dbhome_1/lib/libclntsh.so.12.1
#2  0x00007ffff36ae690 in x10dfnInit2Stmt ()

   from /opt/oracle/product/12.1.0/dbhome_1/lib/libclntsh.so.12.1
#3  0x00007ffff36a63b8 in x10allBundledStmt ()

   from /opt/oracle/product/12.1.0/dbhome_1/lib/libclntsh.so.12.1
#4  0x00007ffff36a6801 in x10allBundled ()

   from /opt/oracle/product/12.1.0/dbhome_1/lib/libclntsh.so.12.1
#5  0x00007ffff369913d in x10odr ()

   from /opt/oracle/product/12.1.0/dbhome_1/lib/libclntsh.so.12.1
#6  0x00007ffff4563b3a in upirtrc ()

   from /opt/oracle/product/12.1.0/dbhome_1/lib/libclntsh.so.12.1
#7  0x00007ffff456df46 in kpurcsc ()

   from /opt/oracle/product/12.1.0/dbhome_1/lib/libclntsh.so.12.1
#8  0x00007ffff456b5a5 in kpufch0 ()

   from /opt/oracle/product/12.1.0/dbhome_1/lib/libclntsh.so.12.1
#9  0x00007ffff4569c05 in kpufch ()

   from /opt/oracle/product/12.1.0/dbhome_1/lib/libclntsh.so.12.1
#10 0x00007ffff278119b in OCIStmtFetch2 ()

   from /opt/oracle/product/12.1.0/dbhome_1/lib/libclntsh.so.12.1
#11 0x00007ffff7b98f23 in OCI_FetchData (rs=rs@entry=0x857608, mode=mode@entry=2,

```
offset=offset@entry=0, success=success@entry=0x7fffffffdb8c) at resultset.c:520
```
#12 0x00007ffff7b99cca in OCI_FetchNext (rs=0x857608) at resultset.c:1100

**Comment by vrogier** [comment]
Hi,

Can you provide oracle and ocilib versions ?
Can you also provide sample ddl for the table ?
Thanks

Regards,

Vincent

**Comment by vrogier** [comment]
And also sample code for bind variable.

Thanks

**Comment by vrogier** [comment]
Closing issue as no more information provided

**Comment by amirhakh** [comment]
Hello
Bind 'varbinary (256)' value type in oracle TimesTen cuse this bug.
i use oracle oci to solve this issue.
