### ISSUE TITLE
Bulk insert calls when ExecutePrepared () function, which leads to the block for a long time

### ISSUE THREAD

**Issue by ljx0305** [vrogier/ocilib#54]
Why I simulate add 50000 records, in ExecutePrepared () function call block at least 5 minutes.
Below is my test example, platform is Windows 10 oracle11g

typedef struct _User
{
    int nID;
    int nAge;
}User;

int main(void)
{
    ostringstream oss;
    vector<Blob> vtrBlob;

```
InitEnvironment();

oss << "(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=" << "127.0.0.1" <<")(PORT="<< "1521" <<"))(CONNECT_DATA=(SERVICE_NAME="<<"orcl"<<")))";
ostring strConn = oss.str();
Connection conn(strConn.c_str(), "test", "test"/*,Environment::SessionSysDba*/);
try
{
    Blob blob(conn);
    User user;
    user.nID = 1;
    user.nAge = 10;
    Raw raw((unsigned char*)&user,(unsigned char*)&user+sizeof(User));
    blob.Write(raw);

    int nItem = 0;
    vtrBlob.reserve(50000);
    for(;nItem < 50000;nItem++)
    {
        vtrBlob.push_back(blob);
    }
    Statement st(conn);
    try
    {
        ostring insertSql = "insert into test_blob (data) values (:data)";
        st.Prepare(insertSql);
        st.SetBindArraySize(vtrBlob.size());
        st.Bind(OTEXT(":data"),vtrBlob,BindInfo::In);
        st.ExecutePrepared();
    }
    catch(Exception &ex)
    {
        std::cout << ex.GetOracleErrorCode() << " " << ex.what() << std::endl;
    }

    conn.Commit();
}
catch(Exception &ex)
{
     std::cout << ex.what() << std::endl;
}
conn.Close();
UnInitEnvironment();
return EXIT_SUCCESS;
```

}

**Comment by vrogier** [comment]
hi,

​Using 50000 elements for DML array operations is far too much especially with oracle blobs.
It is even slower than inserting blobs one by one.
Efficient DML bind array size depends on plenty of factors.
It must be​ computed pragmatically .

Best regards,

Vincent

**Comment by ljx0305** [comment]
What's the good method can realize bulk warehousing，Direct path method whether can submit performance

**Comment by jmptrader** [comment]
Hi,

In my case, I define an number of rows in commit block, p.e. 8192. accord to my requeriment.

JM

**Comment by vrogier** [comment]
Closing it as answers have been provided.
