### ISSUE TITLE
ResultSet::next() crashes!!!

### ISSUE THREAD

**Issue by romancegirls** [vrogier/ocilib#55]
hi , I met an occi problem, I want to get interval value from oracle, but it was crashed ,why?
the stack is:
`
favorite
#0  0x0000003d7e432925 in raise () from /lib64/libc.so.6
#1  0x0000003d7e43408d in abort () from /lib64/libc.so.6
#2  0x00007ff601e3ba55 in os::abort(bool) () from /usr/java/jdk1.7.0_67-cloudera/jre/lib/amd64/server/libjvm.so
#3  0x00007ff601fbbf87 in VMError::report_and_die() () from /usr/java/jdk1.7.0_67-cloudera/jre/lib/amd64/server/libjvm.so
#4  0x00007ff601e4096f in JVM_handle_linux_signal () from /usr/java/jdk1.7.0_67-cloudera/jre/lib/amd64/server/libjvm.so
#5  <signal handler called>
#6  0x00007ff5fe8f218e in LdiInterFromArray () from /home/zhaojuan/project/DataType/thirdparty/occi-11.2/lib/libclntsh.so.11.1
#7  0x00007ff5ff85a1eb in kpcceiyd2iyd () from /home/zhaojuan/project/DataType/thirdparty/occi-11.2/lib/libclntsh.so.11.1
#8  0x00007ff600138c1d in ttccfpg () from /home/zhaojuan/project/DataType/thirdparty/occi-11.2/lib/libclntsh.so.11.1
#9  0x00007ff600136e90 in ttcfour () from /home/zhaojuan/project/DataType/thirdparty/occi-11.2/lib/libclntsh.so.11.1
#10 0x00007ff5fe5c45f3 in kpufcpf () from /home/zhaojuan/project/DataType/thirdparty/occi-11.2/lib/libclntsh.so.11.1
#11 0x00007ff5fe5c2872 in kpufch0 () from /home/zhaojuan/project/DataType/thirdparty/occi-11.2/lib/libclntsh.so.11.1
#12 0x00007ff5fe5c110f in kpufch () from /home/zhaojuan/project/DataType/thirdparty/occi-11.2/lib/libclntsh.so.11.1
#13 0x00007ff5fe556a03 in OCIStmtFetch () from /home/zhaojuan/project/DataType/thirdparty/occi-11.2/lib/libclntsh.so.11.1
#14 0x00007ff600a29b33 in oracle::occi::ResultSetImpl::next(unsigned int) () from /home/zhaojuan/project/DataType/thirdparty/occi-11.2/lib/libocci.so.11.1
#15 0x0000000000c6f481 in xcloud::xos::OracleLoader::RunLoadMain (this=0x78e6680) at /home/zhaojuan/project/DataType/be/src/exec_xos/OracleLoader.cpp:366'
setbuffer code:
`if (ttype == oracle::occi::OCCI_SQLT_INTERVAL_YM) {
                LOG(INFO) << "set YM buffer";
                m_res->setDataBuffer(i + 1, m_colBuf[i], ttype, 5, &(m_resultInfos[i].fieldLens[0]),
                        &(m_resultInfos[i].fieldFlags[0]), &(m_resultInfos[i].fieldRCs[0]));
            } else if (ttype == oracle::occi::OCCI_SQLT_INTERVAL_DS) {
                m_res->setDataBuffer(i + 1, m_colBuf[i], ttype, 11, &(m_resultInfos[i].fieldLens[0]),
                        &(m_resultInfos[i].fieldFlags[0]), &(m_resultInfos[i].fieldRCs[0]));
            }`
m_res is a type of oracle::occi::ResultSet* 
m_colBuf[i] is alloc(colWidth[i] * fetchsize) 
and it was crashed at:
`            if (0 == m_res->next(m_fetchSize)) {
                LOG(INFO) << "Oracle Fetch finished!";
                break;
            }`

**Comment by vrogier** [comment]
this not an ocilib issue but rather an occi issue.
