### ISSUE TITLE
Columns with varrays never gets NULL while fetching

### ISSUE THREAD

**Issue by HerbertMetzdorf** [vrogier/ocilib#56]
Hi Vincent,
i fetch data from a table which contains a column with an "varray(10) of integer".
For some rows the column with the int-array is set to NULL.
If I now fetch the data with different settings of "OCI_SetFetchSize(st, 10)" i get different results:

-     OCI_IsNull() never gets TRUE even if the column with the int-array is definitly null
-     the first array fetch gives correct data for the size of the int-array (OCI_CollGetSize is 0)
-     the following array fetches didnt clean the previous results, so arrays which are NULL will have a size and data from the previous fetch

affected Version: 4.2.1
sourcecode is attached

Regards
Herbert Metzdorf
[testcoll.zip](https://github.com/vrogier/ocilib/files/552468/testcoll.zip)

**Comment by vrogier** [comment]
Hi,

Thanks for reporting issues :)

The problem is confirmed and the root cause identified (wrong usage of null indicators for collection based columns).

I will commit a fix asap by this evening or tomorrow.

Thanks.

Regards,

Vincent
