### ISSUE TITLE
How use External Credentials with OCI_POOL_SESSION?

### ISSUE THREAD

**Issue by jmptrader** [vrogier/ocilib#57]
Hi Vicent,

When I use the external credentials (Oracle Wallet) with  OCI_POOL_CONNECTION my code run OK,

OCI_Initialize(NULL, NULL, OCI_ENV_DEFAULT | OCI_ENV_CONTEXT  | OCI_ENV_THREADED )
OCI_PoolCreate(g_config.tns, 
                NULL, 
                NULL, 
                OCI_POOL_CONNECTION, 
                OCI_SESSION_DEFAULT,
                g_config.min_conn, 
                g_config.max_conn, 
                g_config.inc_conn);

_**in this case, I can only see level TCP / IP, an open socket **_

...
But I use with OCI_POOL_SESSION my code not running.

Note:
_** when I use OCI POOL SESSION with User/Password explicit running OK,
   and in this case, I can see the level of TCP / IP, 'N' open sockets **_

...
I use  ocilib-4.2.1 and Oracle 12c ( oracle oci 12.1)
...

What can be happening?

Thank's
JM

**Comment by vrogier** [comment]
Hi, 

I found the issue.
Could it be possible for you to test a patch ? ( I do not have a setup with oracle wallet on)

Regards,

Vincent

**Comment by vrogier** [comment]
Hi,

I've setup a oracle wallet and tested with success my patch.
I will commit shortly

Regards,

Vincent

**Comment by jmptrader** [comment]
Hi Vicent,

Great news. Very Thank´s. I will prepare an environment for test this patch.

I wait your new release.

Regards,
JM

**Comment by vrogier** [comment]
Hi,

Fix has been commited.
You can retrieve latest version and compile ocilib for checking the
resolution (worked on my box).

I'm thinking about releasing v4.3 on Wednesday.

Best regards,
Vincent

**Comment by jmptrader** [comment]
Hi Vincent,

I've setup my oracle wallet and adjust my code with success.

Running very fine.

´´´
´g_pool = OCI_PoolCreate(g_config.tns, 
                NULL, 
                NULL, 
                OCI_POOL_SESSION, 
                OCI_SESSION_DEFAULT,
                g_config.min_conn, 
                g_config.max_conn, 
                g_config.inc_conn);

    if ( g_pool == NULL ) { 
        messageLog(LOG_ERROR, "No fue posible inicializar el Pool de connecciones.");
        return STS_FAIL;
    }´
´´´
Thank's very much.

JM
