### ISSUE TITLE
Bug with CLOBS

### ISSUE THREAD

**Issue by albertino80** [vrogier/ocilib#58]
Hi Rogier,

[bug_test.zip](https://github.com/vrogier/ocilib/files/577795/bug_test.zip)
as you can see using example attached, there is a problem in 
```
string.c
function unsigned int OCI_StringGetFromType
case OCI_CDT_LOB:

```

If you comment 
`putenv( "NLS_LANG=.AL32UTF8" );`
all goes ok

I think about the declaration of 
`otext lob_buf[OCI_SIZE_BUFFER + 1 ];`
this can be 
`otext lob_buf[OCI_SIZE_BUFFER + 4 ];`

P.S:
See folder fix_vs2010
Using VS2010 with last release, the declarations of variables in functions:
```
boolean OCI_API OCI_Initialize
OCI_Mutex * OCI_MutexCreateInternal
```
Must be moved on top of the function, else there is a C Compiler errors.

Thanks for your patience.

**Comment by vrogier** [comment]
Issue Fixed :)

Regards,

Vincent
