### ISSUE TITLE
Exception in statement upgrading from OCILIB 3.12 to 4.3

### ISSUE THREAD

**Issue by Ben136KBC** [vrogier/ocilib#60]
In statement.c OCI_ExecuteInternal now calls OCI_BindCheckAll which has this code:

            /* extra work for internal allocated binds buffers */

            if (bnd->alloc)
            {
                if (bnd->is_array)
                {
                    for (j = 0; j < bnd->buffer.count && OCI_STATUS; j++)
                    {
                        OCI_STATUS = OCI_BindCheck(bnd, (ub1*)bnd->input[j], (ub1*)bnd->buffer.data, j);
                    }

If your prepared SQL statement is:

INSERT INTO Collections (CollectionID, ParentCollectionID, CollectionType, Name, Path, BuildNumber, BuildType, GenerationDate, Author, Description, Revision, SampleDate, Tag, CollectionStatus, LockedBy) VALUES (:l1, :l2, :s1, :s2, :s3, :s4, :s5, :s6, :s7, :s8, :l3, :s9, :s10, :l4, :s11)

then for i=0. for the :l1 in the statement, bnd-input correctly points to the passed in allocated array (an array which holds big ints in my case), which has the correct entry data. But in the line:

 OCI_STATUS = OCI_BindCheck(bnd, (ub1*)bnd->input[j], (ub1*)bnd->buffer.data, j);

expression "(ub1*)bnd->input[j]" takes the first data entry (a bigint data value) and casts that to a (bu1*) which then causes OCI_BindCheck to crash with a bad pointer for argument ub1* src.

Is it possible that my code is passing or setting it up wrong? Maybe, but all the right values always ended up in the database before and it never threw any exceptions, suggesting that what I passed in was right. The corresponding bind check code in 3.12 does not trigger this issue and is different.

I love OCILIB and appreciate all of your hard work, but with respect, I think you introduced a nasty crash...

(OCI_NUM_BIGINT == bnd->subtype  so in OCI_BindCheck)

Thank you.

**Comment by vrogier** [comment]
Hi,

Thanks for reporting issues ! 

Can you provide a minimal compilable code sample reproducing the issue ? 
Thanks a lot.

PS :  what is your target environment ?  

Vincent

**Comment by Ben136KBC** [comment]
This is under Windows. Sadly, the code is part of a very large complex system, and not easy to reproduce with a smaller system. I love it when our customers do that to me, so I know how you feel. I was hoping that the explanation above would be helpful. Does this help?

            ist = OCI_StatementCreate(cn);
            boolean prepok = OCI_Prepare(ist, insertBindString);

insertBindfString = "INSERT INTO Collections (CollectionID, ParentCollectionID, CollectionType, Name, Path, BuildNumber, BuildType, GenerationDate, Author, Description, Revision, SampleDate, Tag, CollectionStatus, LockedBy) VALUES (:l1, :l2, :s1, :s2, :s3, :s4, :s5, :s6, :s7, :s8, :l3, :s9, :s10, :l4, :s11)"

numLongBindings = 4;

               longBindings = new big_int* [numLongBindings];
               for (i=0; i<numLongBindings; i++)
                  {
                  longBindings[i] = new big_int[arraySize];
                  memset(longBindings[i],0,arraySize*sizeof(big_int));
                  Text bs = ":l"; bs.AppendNumber(i+1);
                  boolean bi = OCI_BindArrayOfBigInts(ist, bs, longBindings[i], 0);
                  }

And then:

            OCI_BindArraySetSize(ist, cursorPos);

(cursorPos == 1)

And then:

            boolean ok = OCI_Execute(ist);

which crashes in OCI_BindCheckAll on the first bind check.

**Comment by Ben136KBC** [comment]
Hi,

If you have time now and the inclination, I can always give you access to my development machine so you can see what happens?

Do you have teamviewer?

**Comment by vrogier** [comment]
No problems :)

I will try to reproduce asap! And commit a fix as well if i can reproduce.

Vincent

**Comment by vrogier** [comment]
DO you get the crash in OCI_NumberSetNativeValue() ?

**Comment by Ben136KBC** [comment]
Yes: It craches in OCI_BindCheck because the src pointer being passed in is invalid.  So src_bint is also invalid and then it crashes in OCI_NumberSetNativeValue.

            else if (OCI_NUM_BIGINT == bnd->subtype)
            {
                big_int   *src_bint = (big_int *)(src + index * sizeof(big_int));
                OCINumber *dst_num  = (OCINumber *)dst;

                OCI_STATUS = OCI_NumberSetNativeValue
                (
                    bnd->stmt->con, dst_num, (uword) sizeof(big_int), bnd->subtype, bnd->code, src_bint
                );

**Comment by vrogier** [comment]
Code is faullty indeed :( 

I will commit a fix with the next 2 hours :)

**Comment by Ben136KBC** [comment]
Thank you very much. The code work fine if you are just reading. It only has issues when you try prepared statement bulk inserts.

**Comment by FladoToo** [comment]
You rock, man!

**Comment by vrogier** [comment]
Hello,

I've committe a fix for it.

Here is a sample C application for testing the changes and impacted code.

Best regards,

Vincent

```C
#include "ocilib.h"

#define ARRAY_SIZE 10

void err_handler(OCI_Error *err)
{
    printf("%s\n", OCI_ErrorGetString(err));
}

/*
create type test_obj as object(value number);
/
create table test_table_array(i number, d date, n number, t timestamp, o test_obj);

*/

int main(void)
{
    OCI_Connection *cn;
    OCI_Statement  *st;
    OCI_TypeInfo   *ti;

    big_int        tab_bi[ARRAY_SIZE];
    OCI_Date*      tab_dt[ARRAY_SIZE];
    OCI_Number*    tab_nm[ARRAY_SIZE];
    OCI_Timestamp* tab_ts[ARRAY_SIZE];
    OCI_Object*    tab_ob[ARRAY_SIZE];

    int i;

    if (!OCI_Initialize(err_handler, NULL, OCI_ENV_DEFAULT | OCI_ENV_CONTEXT))
    {
        return EXIT_FAILURE;
    }

    cn = OCI_ConnectionCreate("db", "usr", "pwd", OCI_SESSION_DEFAULT);
    st = OCI_StatementCreate(cn);
    ti = OCI_TypeInfoGet(cn, "test_obj", OCI_TIF_TYPE);

    OCI_Prepare(st, "insert into test_table_array values(:i, :d, :n, :t, :o)");
    OCI_BindArraySetSize(st, ARRAY_SIZE);
    OCI_BindArrayOfBigInts(st, ":i", &tab_bi[0], 0);
    OCI_BindArrayOfDates(st, ":d", &tab_dt[0], 0);
    OCI_BindArrayOfNumbers(st, ":n", &tab_nm[0], 0);
    OCI_BindArrayOfTimestamps(st, ":t", &tab_ts[0], OCI_TIMESTAMP, 0);
    OCI_BindArrayOfObjects(st, ":o", &tab_ob[0], ti, 0);

    for (i = 0; i<ARRAY_SIZE; i++)
    {
        tab_bi[i] = i + 10;
        tab_dt[i] = OCI_DateCreate(cn);
        tab_nm[i] = OCI_NumberCreate(cn);
        tab_ts[i] = OCI_TimestampCreate(cn, OCI_TIMESTAMP);
        tab_ob[i] = OCI_ObjectCreate(cn, ti);

        OCI_DateSysDate(tab_dt[i]);
        OCI_DateAddDays(tab_dt[i], i);
        OCI_TimestampSysTimestamp(tab_ts[i]);
        OCI_NumberSetValue(tab_nm[i], OCI_NUM_INT, &i);
        OCI_ObjectSetInt(tab_ob[i], "value", i * 100);
    }

    OCI_Execute(st);

    printf("row inserted : %d\n", OCI_GetAffectedRows(st));

    OCI_Commit(cn);

    for (i = 0; i<ARRAY_SIZE; i++)
    {
        OCI_DateFree(tab_dt[i]);
        OCI_TimestampFree(tab_ts[i]);
        OCI_NumberFree(tab_nm[i]);
        OCI_ObjectFree(tab_ob[i]);
    }

    OCI_StatementFree(st);
    OCI_ConnectionFree(cn);
    OCI_Cleanup();

    return EXIT_SUCCESS;
}
```

**Comment by Ben136KBC** [comment]
Awesome turn around! Thank you. I shall get the latest and test my application.

**Comment by Ben136KBC** [comment]
This crash is fixed now, but sadly, there is another crash which I shall log.

**Comment by vrogier** [comment]
Must be something else... Try to get information about the new crash

**Comment by Ben136KBC** [comment]
I have just logged issue 61. It is a different issue. Not sure exactly what...

**Comment by Ben136KBC** [comment]
vrogier, thank you for this thankless task... but we really love OCILIB, it makes life so much easier for a lot of people. You take care of a lot of ugly stuff we do not have to worry about. So.. THANK YOU.

**Comment by Ben136KBC** [comment]
I can confirm that the first issue above is indeed fixed and no longer crashes. That now works fine.

**Comment by Ben136KBC** [comment]
I have upgraded from 4.30 to 4.3.1. Everything seems to be working fine. Thank you.
