### ISSUE TITLE
Exception in BLOBs when upgrading from OCILIB 3.12 to 4.3

### ISSUE THREAD

**Issue by Ben136KBC** [vrogier/ocilib#61]
We were using OCILIB 3.12 and had no issue or exception ever. However, when using the latest code, the following code snippet reliably crashes. It never crashed in 3.12, and that was with 32 and 64 bit versions and diagnostic heaps etc.

         OCI_Statement* st = OCI_StatementCreate(cn);
         bool ok = OCI_Prepare(st, ti->insertBindString);

         //insertBindString = "INSERT INTO PSIM_BLOB (CollectionID, BLOBID, BLOBType, BLOBName, TheBLOB) VALUES (:l1, :l2, :s1_255, :s2_255, :b1)"
         
         //Create the BLOB:
         OCI_Lob* lob = OCI_LobCreate(cn, OCI_BLOB);
 
         //Write some binary bytes, all ok. 
         unsigned int nwrite = OCI_LobWrite(lob, buffer, fileSize);
         
         //Bind the variables in the insertion statement:
         ok = ok && OCI_BindLob(st, ":b1", lob);

         big_int bi1 = l1;  //l1 = 38
         big_int bi2 = l2;  //l2 = 0
         ok = ok && OCI_BindBigInt(st, ":l1", &bi1);
         ok = ok && OCI_BindBigInt(st, ":l2", &bi2);

         const char* s1 = "Full SimCase";
         const char* s2 = "Ñ‹ÑŽÐ¹Ð¶ Test3.ksc";
         
         ok = ok && OCI_BindString(st, ":s1_255", (char*)s1, strlen(s1));
         ok = ok && OCI_BindString(st, ":s2_255", (char*)s2, strlen(s2));

         //And execute it:
         if (ok)
            {
            ok = OCI_Execute(st);
            //Calls OCI_ExecuteInternal, which crashes on the call to OCIStmtExecute
            if (!ok)
               {
               LogError();
               }
            }

         ok = ok && OCI_Commit(cn);

         OCI_LobFree(lob);
         OCI_StatementFree(st);

**Comment by vrogier** [comment]
it crashes at what point ?

**Comment by Ben136KBC** [comment]
In the call to OCI_Execute which calls OCI_ExecuteInternal. It crashes on the line that calls OCIStmtExecute.

**Comment by Ben136KBC** [comment]
It seems to be crashing on a near null pointer. Access violation reading location 0x00000010. The issue in bug 60 also manifested as a crash due to a near zero pointer, where some long values passed in were low integers. With 60 I could find and point at the flawed code, but with this one it is not so clear... sorry. I am really hoping you can find it!

**Comment by vrogier** [comment]
I found the issue... Arghh.... Fix is coming soon. I can't believe I've messed up to this point binding handle!

**Comment by Ben136KBC** [comment]
It happens even in the best families. *smiles*. Thank you for fixing it. Sorry for reporting all of these problems. Been a while since I updated and our application is a heavy database user.

**Comment by Ben136KBC** [comment]
I am guessing not many people make use of BLOBs and prepared array bindings, otherwise issues 60 and 61 would have been found earlier. Both are tricky, but work well once you get them working. Thank you for OCILIB, we love it!

**Comment by vrogier** [comment]
In fact that issue was introduced by my previous commit :(
Sorry about that.
I've just committed a fix that works for single and array binds.
It shall be ok now. Let me know if not.
Here a complete testing app for impacted code

```C
#include "ocilib.h"

#define ARRAY_SIZE 10

void err_handler(OCI_Error *err)
{
    printf("%s\n", OCI_ErrorGetString(err));
}

/*
create type test_obj as object(value number);
/
create table test_table_array(i number, d date, n number, t timestamp, o test_obj, l blob);

*/

int main(void)
{
    OCI_Connection *cn;
    OCI_Statement  *st;
    OCI_TypeInfo   *ti;

    big_int        tab_bi[ARRAY_SIZE];
    OCI_Date*      tab_dt[ARRAY_SIZE];
    OCI_Number*    tab_nm[ARRAY_SIZE];
    OCI_Timestamp* tab_ts[ARRAY_SIZE];
    OCI_Object*    tab_ob[ARRAY_SIZE];
    OCI_Lob*       tab_lb[ARRAY_SIZE];

    unsigned char blob[10] = { 0, 1, 2, 4, 5, 6, 7, 8, 9 };

    int i;

    if (!OCI_Initialize(err_handler, NULL, OCI_ENV_DEFAULT | OCI_ENV_CONTEXT))
    {
        return EXIT_FAILURE;
    }

    cn = OCI_ConnectionCreate("db", "usr", "pwd", OCI_SESSION_DEFAULT);
    st = OCI_StatementCreate(cn);
    ti = OCI_TypeInfoGet(cn, "test_obj", OCI_TIF_TYPE);

    for (i = 0; i<ARRAY_SIZE; i++)
    {
        tab_bi[i] = i + 10;
        tab_dt[i] = OCI_DateCreate(cn);
        tab_nm[i] = OCI_NumberCreate(cn);
        tab_ts[i] = OCI_TimestampCreate(cn, OCI_TIMESTAMP);
        tab_ob[i] = OCI_ObjectCreate(cn, ti);
        tab_lb[i] = OCI_LobCreate(cn, OCI_BLOB);

        OCI_DateSysDate(tab_dt[i]);
        OCI_DateAddDays(tab_dt[i], i);
        OCI_TimestampSysTimestamp(tab_ts[i]);
        OCI_NumberSetValue(tab_nm[i], OCI_NUM_INT, &i);
        OCI_ObjectSetInt(tab_ob[i], "value", i * 100);
        OCI_LobWrite(tab_lb[i], blob, sizeof(blob));
    }

    // SINGLE BIND

    OCI_Prepare(st, "insert into test_table_array values(:i, :d, : n, : t, : o, :l)");
    OCI_BindBigInt(st, ":i", &tab_bi[0]);
    OCI_BindDate(st, ":d", tab_dt[0]);
    OCI_BindNumber(st, ":n", tab_nm[0]);
    OCI_BindTimestamp(st, ":t", tab_ts[0]);
    OCI_BindObject(st, ":o", tab_ob[0]);
    OCI_BindLob(st, ":l", tab_lb[0]);

    OCI_Execute(st); 

    printf("row inserted : %d\n", OCI_GetAffectedRows(st));

    OCI_Commit(cn);

    // ARRAY BIND

    OCI_Prepare(st, "insert into test_table_array values(:i, :d, : n, : t, : o, :l)");
    OCI_BindArraySetSize(st, ARRAY_SIZE);
    OCI_BindArrayOfBigInts(st, ":i", &tab_bi[0], 0);
    OCI_BindArrayOfDates(st, ":d", &tab_dt[0], 0);
    OCI_BindArrayOfNumbers(st, ":n", &tab_nm[0], 0);
    OCI_BindArrayOfTimestamps(st, ":t", &tab_ts[0], OCI_TIMESTAMP, 0);
    OCI_BindArrayOfObjects(st, ":o", &tab_ob[0], ti, 0);
    OCI_BindArrayOfLobs(st, ":l", &tab_lb[0], OCI_BLOB, 0);

    OCI_Execute(st);

    printf("row inserted : %d\n", OCI_GetAffectedRows(st));

    OCI_Commit(cn);

    for (i = 0; i<ARRAY_SIZE; i++)
    {
        OCI_DateFree(tab_dt[i]);
        OCI_TimestampFree(tab_ts[i]);
        OCI_NumberFree(tab_nm[i]);
        OCI_ObjectFree(tab_ob[i]);
        OCI_LobFree(tab_lb[i]);
    }

    OCI_StatementFree(st);
    OCI_ConnectionFree(cn);
    OCI_Cleanup();

    return EXIT_SUCCESS;
}
```

Best regards,

Vincent

**Comment by Ben136KBC** [comment]
Thank you very much Sir Vincent. I can confirm that it no longer crashes, and that issues 60 and 61 are both fixed now. So I can update the OCILIB code in our application now.  <phew>

Just curious, these testing apps... do you run through them all each time you make a change?

**Comment by vrogier** [comment]
I should indeed .. 
I've got a collection of them but sometimes, it appears that I forget to run some of them  : (
I also run the ones in the demo folder before each release.
The thing is I should integrate proper unit testing in the ocilib repo. But running tests against a real db during CI (I'am using travis) is a pain as oracle db must be installed and deployed during each CI job. Would take too long.
Mocking oracle client is not easy as well.

And adding a whole bunch of propers automated and portable test suites is also a huge effort (especially as I have the C and C++ apis) that I don't unfortunately have time for : (

I wish that my spare time after work could be more extensible ; )

I'll be more carefull next time.

As issue  #60 was major, I have to release a v4.3.1 asap. I will run all possible prior to the release that will occur next week I guess.


Thanks again  ; )

Best regards,

Vincent

**Comment by Ben136KBC** [comment]
Thank you Vincent, you are doing a great service for all of us. From my limited experience with Oracle, I can well imagine the effort in trying to run through a validation suite. Please let us know if there are any changes in 4.3.1.
