### ISSUE TITLE
hanging oci

### ISSUE THREAD

**Issue by zlojvavan** [vrogier/ocilib#62]
hello

been suffering from hanging process using 4.3.0 running on win 7 and connecting to oracle 11.2.0.4.0

here is excerpt from process trace

thread $3024:
7755f8da +0000e ntdll.dll                                    NtWaitForSingleObject
7758e5e9 +2c319 ntdll.dll                                    RtlEnterCriticalSection
60f8d65e +00016 oracore11.dll                                sltsmna
61aa92d4 +00c4e oracommon11.dll                              ttcc2u
61aaccc5 +006bf oracommon11.dll                              ttcdrv
0ed7d138 +001f0 orageneric11.dll                             kghalp
61aaceef +008e9 oracommon11.dll                              ttcdrv
755d6e0f +0006e WS2_32.dll                                   WSARecv
0f9b56ae +0002e oran11.dll                                   nioqwa
62dc07b7 +0003f OraClient11.Dll                              upirtrc
62d473ff +00055 OraClient11.Dll                              kpurcsc
62d0490a +018a4 OraClient11.Dll                              kpuexec
62c2a9bd +0001f OraClient11.Dll                              OCIStmtExecute
0ebc89fd +0003d oci.dll                                      OCIStmtExecute
00288451 +000a1 OCILIBA.DLL                                  _OCI_Execute@4

thread $22c0:
7755f8da +0000e ntdll.dll                                   NtWaitForSingleObject
7758e5e9 +2c319 ntdll.dll                                   RtlEnterCriticalSection
60f8d65e +00016 oracore11.dll                               sltsmna
62cfc420 +00016 OraClient11.Dll                             kpughndl
62c2aca1 +0007b OraClient11.Dll                             OCIStmtPrepare2
0eb813d8 +00040 oci.dll                                     OCIStmtPrepare2
00287a02 +000b2 OCILIBA.DLL                                 _OCI_Prepare@8

etc.

lib is initialized via OCI_Initialize(NULL, NULL, OCI_ENV_DEFAULT | OCI_ENV_CONTEXT | OCI_ENV_THREADED)

any idea what could be wrong?

p.s. according to https://github.com/vrogier/ocilib/issues/61#issuecomment-265608224 I thought you were going to release 4.3.1 soon?

thank you

**Comment by vrogier** [comment]
It seems that you've got a deadlock between 2 threads that are locking critical sections.
Can you identify the 2 call stacks waiting for each other ? 

Regarding v4.3.1, I expect to release it on Wednesday.

Regards,

Vincent

**Comment by zlojvavan** [comment]
as you can see those critical sections belong to oci/oracle internals. my threads use different oracle connections and don't interact to each other

**Comment by vrogier** [comment]
Whatever you're using one or many connections, they alll use the same environment and thus sharing synchronization primitives.
It would be interesting to identify wich thread A is locking  CS1 while thread B is trying to acquire CS2 that is already locked by thread A.
And check their callstacks.

**Comment by zlojvavan** [comment]
any idea how "to identify wich thread A is locking CS1 while thread B is trying to acquire CS2 that is already locked by thread A"? at the moment I captured that trace there was the only one another thread (beside those two above) waiting for prepare to complete:

thread $3660:
7755f8da +0000e ntdll.dll                                   NtWaitForSingleObject
7758e5e9 +2c319 ntdll.dll                                   RtlEnterCriticalSection
60f8d65e +00016 oracore11.dll                               sltsmna
62cfc420 +00016 OraClient11.Dll                             kpughndl
62c2aca1 +0007b OraClient11.Dll                             OCIStmtPrepare2
0eb813d8 +00040 oci.dll                                     OCIStmtPrepare2
00287a02 +000b2 OCILIBA.DLL                                 _OCI_Prepare@8

**Comment by vrogier** [comment]
Can you dump the process when the issue occurs  ?  
With a dump file, you can find what thread is locking a given CS

**Comment by zlojvavan** [comment]
do you recommend to use windbg? as my main tools are borland related and sometimes I use cdb32 for debugging I guess it will take some time to get used to windbg and learn how to diagnose deadlocks there, but I'll try as soon as I get some dump. thank you

**Comment by vrogier** [comment]
If you want, you can dump the process (full dump) and put it somewhere i can get access to it.
As I don't have your application pdbs, but only ocilib pdbs, i could do the analysis regarding oci/ocilib usage without having knowledge of your application code.

**Comment by zlojvavan** [comment]
I don't even have pdbs as borland tools produce .tds files
I'll report back as I have any additional info/dump
thank you again

**Comment by zlojvavan** [comment]
btw I guess I've found some problem in my code, apparently I only create/init statements, parse and execute those, then get output params but do not invoke OCI_StatementFree. as this is my first ever app utilizing ocilib in its c incarnation and I'm accustomed to other oracle libs/wrappers automatically freeing statement resources I somehow overlooked that step. do you think such stupid error could manifest itself as hanging oci call?

**Comment by vrogier** [comment]
Closing a connection automatically closes and frees all of its child statements.
But you'd better free then when no longer needed

**Comment by zlojvavan** [comment]
I do not close those connections. there is typical thread/connection pool serving database requests. I'll add OCI_StatementFree to see if it change anything

**Comment by vrogier** [comment]
You do not close connections ? 
Even when using connections from a pool, you need to call OCI_ConnectionFree()  when it is no longer needed. 
If the connection had been retrieved from OCI_PoolGetconnection(), OCI_ConnectionFree() will not really close the connection but rather free ocilib resources wrapping the oci connection.
How do you handle the pool ?

**Comment by zlojvavan** [comment]
no I don't as the app is intended to run 24x7 and I don't use built-in pool

**Comment by vrogier** [comment]
Thus, you are usong a custom hand made pool ?

**Comment by zlojvavan** [comment]
right

**Comment by zlojvavan** [comment]
may I ask you which file sharing hosting would you prefer? dump file is 451 Mb

**Comment by vrogier** [comment]
any hosting that i can access (web based, cloud, ftp, ....).
Send me a email if it requires special link and / or credentials

**Comment by vrogier** [comment]
Hi, 

Have you tried using another version or Oracle client such as a 12c client ?
The deadlock seems to be deep into the Oracle OCI client.

**Comment by zlojvavan** [comment]
not yet, but I'll try and report back

**Comment by zlojvavan** [comment]
not yet, but I'll try and report back

**Comment by zlojvavan** [comment]
I believe it would be safe to assume that the problem is gone with client v.12
