### ISSUE TITLE
ocilib.hpp minor problem

### ISSUE THREAD

**Issue by empsftwr** [vrogier/ocilib#63]
Hi,
I was compiling a program today using your C++ wrapper. At some point of the compilation it complained that `ptrdiff_t` is unrecognized, so I added `#include  <cstddef>` to ocilib.hpp in order to sort it out.

`...
#ifndef OCILIBCPP_H_INCLUDED
#define OCILIBCPP_H_INCLUDED

/* includes */

#include \<string\>
#include \<list\>
#include \<vector\>
**#include \<cstddef\>**

extern "C"{
#include "ocilib.h"
}
...
`

I am compiling on openSuse 42.2 Linux with g++ 4.8.5.

Best regards.

**Comment by vrogier** [comment]
Hi,

Thanks for reporting it.

That's weird as I did not encounter this issues on other g++ installations (nor with clang and msvc)

I will check that point .

Best regards

Vincent
