### ISSUE TITLE
Can't insert number null

### ISSUE THREAD

**Issue by cyz7758520** [vrogier/ocilib#65]
hello

I use OCILIB 4.3.0 running on win 8.1 and connecting to oracle 11.2.0.3.0.

I use OCI_BindArrayOfNumbers() insert some numerical, and use OCI_BindSetNullAtPos() set some null.
OCI_Execute() return is TURE, but no data in the oracle table.

If i use OCI_BindArrayOfNumbers() insert some numerical, and not use OCI_BindSetNullAtPos() set some null.
OCI_Execute() return is TURE, There is data in the oracle table.

Why?

Thank you!

**Comment by vrogier** [comment]
Hi,

I will check it this asap.

Regards,

Vincent

**Comment by cyz7758520** [comment]
I have discovered.

This is my test sql and code.

SQL:
drop table mytab;
create table mytab (mynumber number, mydate date);
select * from mytab;

C Code:
#include <stdio.h>
#include "..\LibOciLib\ocilib.h"
#if (defined _WIN64) && (defined _DEBUG)
#pragma comment(lib, "..\\LibOciLib\\LibOciLib_x64_Debug_MDd_LIB.lib")
#pragma comment(lib, "..\\LibOciLib\\oci_x64.lib")
#elif (defined _WIN64) && (defined NDEBUG)
#pragma comment(lib, "..\\LibOciLib\\LibOciLib_x64_Release_MD_LIB.lib")
#pragma comment(lib, "..\\LibOciLib\\oci_x64.lib")
#elif (defined _WIN32) && (defined _DEBUG)
#pragma comment(lib, "..\\LibOciLib\\LibOciLib_x86_Debug_MDd_LIB.lib")
#pragma comment(lib, "..\\LibOciLib\\oci_x86.lib")
#elif (defined _WIN32) && (defined NDEBUG)
#pragma comment(lib, "..\\LibOciLib\\LibOciLib_x86_Release_MD_LIB.lib")
#pragma comment(lib, "..\\LibOciLib\\oci_x86.lib")
#endif

int main (int argc, char ** argv)
{
	OCI_Connection * hOraConn = NULL;//存放Oracle数据库连接句柄
	OCI_Statement * hOraStat = NULL;//存放Statement句柄
	OCI_Number * pstNumber = NULL;
	OCI_Date * pstDate = NULL;

	if (!OCI_Initialize(NULL, NULL, OCI_ENV_DEFAULT | OCI_ENV_CONTEXT))//如果初始化OCILIB库失败，就报错
	{
		printf ("OCI_Initialize 初始化OCILIB库失败！\n");
		return -1;
	}

	if ((hOraConn = OCI_ConnectionCreate ("orcl", "test", "test", OCI_SESSION_DEFAULT)) == 0)//如果连接数据库失败，就报错
	{
		printf ("OCI_ConnectionCreate 连接Oracle数据库失败！原因：%s\n", OCI_ErrorGetString (OCI_GetLastError ()));
		return -1;
	}

	hOraStat = OCI_StatementCreate (hOraConn);//创建Statement
	/*
	if (OCI_Prepare (hOraStat, "insert into mytab (mydate) values (:mydate)") == FALSE)//如果准备SQL查询语句失败
	{
		printf ("OCI_Prepare 准备SQL语句失败！原因：%s\n", OCI_ErrorGetString (OCI_GetLastError ()));
		return -1;
	}
	
	pstDate = OCI_DateCreate( hOraConn);
	OCI_BindDate( hOraStat, ":mydate", pstDate);
	OCI_BindSetNull(OCI_GetBind2( hOraStat, ":mydate"));
	*/
	
	if (OCI_Prepare (hOraStat, "insert into mytab (mynumber) values (:mynumber)") == FALSE)//如果准备SQL查询语句失败
	{
		printf ("OCI_Prepare 准备SQL语句失败！原因：%s\n", OCI_ErrorGetString (OCI_GetLastError ()));
		return -1;
	}

	pstNumber = OCI_NumberCreate( hOraConn);
	//OCI_NumberFromText( pstNumber, "99.99", NULL);
	OCI_BindNumber( hOraStat, ":mynumber", pstNumber);
	OCI_BindSetNull(OCI_GetBind2( hOraStat, ":mynumber"));
	
	OCI_Execute( hOraStat);
	OCI_Commit(hOraConn);

	if( hOraStat != NULL) OCI_StatementFree (hOraStat);//释放Statement
	if( hOraConn != NULL) OCI_ConnectionFree (hOraConn);//断开数据库
	OCI_Cleanup();

	return 0;
}

Run this code is no data in the oracle table.
I change "//OCI_NumberFromText( pstNumber, "99.99", NULL);" to "OCI_NumberFromText( pstNumber, "99.99", NULL);", There is data in the oracle table.

**Comment by vrogier** [comment]
Hi,

Found the issue:)
Currently, even if using  OCI_BindSetNullAtPos(), each element in the array must be non NULL and for number, must have been initialized with some value (using OCI_NumberSetValue()).
If you do so, (set value and then mark it as NULL), it works.

I will make the folllowing changes for v4.3.1:
- whatever the content of a OCI_Number array item (initialized or not), if OCI_BindSetNullAtPos() has been called, it will be considered as NULL as execution time
- for IN binds, allowing to have a NULL item in arrays (for all OCI_xxx) types, it will considered as NULL as execution time

for the moment, you can apply the workaround (make sure an OCI_Number array item has an initialized value in all cases) until v4.3.1 release (next week).

Regards,

Vincent

**Comment by cyz7758520** [comment]
Look forward to the new! Thank you very much!
