### ISSUE TITLE
C++ HAVE_MOVE_SEMANTICS & HandleHolder problem

### ISSUE THREAD

**Issue by berserker** [vrogier/ocilib#67]
I use OCILIB 4.3.0 on VC15 sp3.
VS is reporting me lots of memory leaks is my app and I managed to identify the problem: if **HAVE_MOVE_SEMANTICS** macro is enabled (as "detected" by default) it seems that the "move constructor" doesn't manage the internal __smartHandle_ correctly.

You can reproduce the problem with this simple code:
```
ocilib::Number createNumber()
{
   ocilib::Number num(true);
   return num;
}

void main()
{
   for(int i = 0; i < 10; ++i)
   {
       ocilib::Number test = createNumber();
   }
}
```
When **HAVE_MOVE_SEMANTICS** is enabled **OCI_NumberFree** is never called while if I manually disable the macro I can track a call to **OCI_NumberFree** for every corresponding **OCI_NumberCreate**.

**Comment by vrogier** [comment]
Hi,
Thanks for reporting this issue.
The move semantic is indeed not properly implemented. It will be removed asap as in thte end it does not bring that much as ocilib C handles are already managed like shared ptrs...
It will commit the removal this weekend.

Regards

Vincent
