### ISSUE TITLE
Statement connection issue

### ISSUE THREAD

**Issue by GlassyPeou** [vrogier/ocilib#69]
Hi,

I've provided sample code showing the issue i'm seeing.

		ocilib::Environment::Initialize();

		ocilib::Pool pool(connect, user, pwd, ocilib::Pool::SessionPool, 1, 3, 1);

		ocilib::Connection connection = pool.GetConnection();

		if (connection.IsNull())
			std::cout << "a" << std::endl;

		ocilib::Statement statement(connection);

		if (statement.GetConnection().IsNull())
			std::cout << "b" << std::endl;

		statement.Prepare(_T("begin select count(*) into :1 from SomeTable; end;"));

		if (statement.GetConnection().IsNull())
			std::cout << "c" << std::endl;

		int count = 0;
		statement.Bind(_T(":1"), count, ocilib::BindInfo::Out);

		statement.ExecutePrepared();

		ocilib::Environment::Cleanup();

When I run the code above I see "b" outputted to the screen but yet the statement executes properly and I don't see the output of "c". Since "b" is outputted it looks like the connection within the statement is NULL but the execution is ran fine. Is this natural behavior?

**Comment by vrogier** [comment]
Hi,

In fact OCI_StatementGetConnection() was returning ... the SQL string ... instead of the OCI_Connection  object pointer.

I've committed a fix for it.

Sorry for the inconvenience.

Regards,

Vincent

**Comment by GlassyPeou** [comment]
That’s good to hear. When are you projected to put out a release?

Glassy Peou | placesign | Software Engineer
16885 West Bernardo Drive #385, San Diego, CA, 92127
glassy.peou@placesign.com<mailto:glassy.peou@placesign.com> | office: 858.312.7771 x7008 | mobile: 562.277.2833

**Comment by vrogier** [comment]
Pretty soon. By the end of the week I guess.
Currently v4.3.2 only addresses issues #69 & #70.

Regards,

Vincent

**Comment by GlassyPeou** [comment]
Ok

Thanks

Glassy Peou | placesign | Software Engineer
16885 West Bernardo Drive #385, San Diego, CA, 92127
glassy.peou@placesign.com<mailto:glassy.peou@placesign.com> | office: 858.312.7771 x7008 | mobile: 562.277.2833
