### ISSUE TITLE
Cppcheck findings

### ISSUE THREAD

**Issue by kornefalk** [vrogier/ocilib#7]
[src/connection.c:196]: (error) Possible null pointer dereference: con
[src/memory.c:116]: (error) Common realloc mistake: 'mem_block' nulled but not freed upon failure

<h2> connection.c</h2>
Line 194 should be (but probably there will be an error before if item=NULL which probably will crash the application)
   if (res && con)

if item still is NULL, then it fails (following a NULL pointer):

     90     OCI_Connection *con  = NULL;
     91     OCI_Item       *item = NULL;
     92     boolean         res  = TRUE;
     93 
     94     /* create connection object */
     95 
     96     item = OCI_ListAppend(OCILib.cons, sizeof(*con));
     97 
     98     if (item)
     99     {

    190     }
    191 
    192     /* update internal status */
    193 
    194     if (res)
    195     {
    196         con->cstate = OCI_CONN_ALLOCATED;
    197     }

<h2> memory.c</h2>
    115     {
    116         mem_block = (OCI_MemoryBlock *)realloc(mem_block, size);
    117 
if realloc fails, the return value is NULL, but the memory still exist and now the old memory pointer is overwritten and therefore the memory is lost.

**Comment by vrogier** [comment]
Hi,

Thanks again for reporting issues.

Fixes committed :)

Regards,

Vincent
