### ISSUE TITLE
Issue when binding unsigned long long integers vs integers

### ISSUE THREAD

**Issue by GlassyPeou** [vrogier/ocilib#71]
Here’s the code I’m running:

	try
	{
		ocilib::Environment::Initialize();

		ocilib::Pool pool(connect, user, pwd, ocilib::Pool::SessionPool, 1, 3, 1);
		ocilib::Connection connection = pool.GetConnection();

		ocilib::Statement statement(connection);
		statement.Prepare(_T("begin select count(*) into :1 from dual where rownum = :2; end;"));

		int count = 0;
		int rownum = 1;

		statement.Bind(_T(":1"), count, ocilib::BindInfo::Out);
		statement.Bind(_T(":2"), rownum, ocilib::BindInfo::In);

		statement.ExecutePrepared();

		ocilib::Environment::Cleanup();
	}
	catch (ocilib::Exception e)
	{
		std::cout << e.what() << std::endl;
	}

This code runs fine and variable “count” is 1.

When I change the datatype of variable "rownum" from int to unsigned long long like this:
int rownum = 1; => unsigned long long rownum = 1;

and I rerun the code the value of “count” is 0.

**Comment by vrogier** [comment]
Hi, 

There was an issue indeed (introduced recently) when binding big_uint host variables only (unsigned long long).
I've committed a fix.
Sorry for the inconvenience ( v4.3.0 had introduced few regressions fixed in v4.3.1 and upcoming v4.3.2)

Best regards,

Vincent

**Comment by GlassyPeou** [comment]
Hi,

When are you projected in the next release?

Thank you

Glassy Peou

**Comment by vrogier** [comment]
I originally thought this weekend but rather by Tuesday 7th
