### ISSUE TITLE
OCI_LobErase() return value mismatch

### ISSUE THREAD

**Issue by vrogier** [vrogier/ocilib#72]
OCI_LobErase() returns 1 on success and 0 on failure instead of returning the number of elements erased from the LOB

**Comment by FladoToo** [comment]
That was fast :-)  :+1:

**Comment by vrogier** [comment]
Hi,

One of my 2017 new year resolution was to enhance good practices for OCILIB  :)
It includes tracking properly any bug separately , even the ones not reported by users.

Best regards,

Vincent
