### ISSUE TITLE
Statement can not be release after copy constructor

### ISSUE THREAD

**Issue by lv0zj** [vrogier/ocilib#76]
src code:
template<class T>
HandleHolder<T>::HandleHolder(HandleHolder<T> && other)  : _smartHandle(nullptr)
{
	std::swap(_smartHandle, other._smartHandle);
}

before swap, this._smartHandle(such as "this" address is A) is null, other._smartHandle(such as "other" address is B) member var "_holders" contains "other" address B,
after swap,this._smartHandle member var "_holders" still contains "other" address B, when "this" be
released,it will remove address is A, so holders.remove will be failure!

**Comment by lv0zj** [comment]
I have just tested it.

**Comment by vrogier** [comment]
Hi,

This code has already been removed in v4.3.1

Best regards

Vincent
