### ISSUE TITLE
demo pool.cpp excute some problem

### ISSUE THREAD

**Issue by lv0zj** [vrogier/ocilib#77]
src code:
void worker(ThreadHandle handle, void *data)
{
    Connection con = ((Pool *)data)->GetConnection();
    Statement st(con);
    st.Execute("select to_char(sysdate, 'YYYYMMDD HH24:MI:SS') from dual");
    Resultset rs = st.GetResultset();
    rs.Next();
    std::cout << handle << " - " << rs.Get<ostring>(1) << std::endl;
    con.Close();
}

every time  " ((Pool *)data)->GetConnection();" will wait 40 seconds ,and then get a connection,i do not know why?

**Comment by vrogier** [comment]
This is a known issue with Oracle Clients 11 & 12 when using connection pools only.
Dos not occurs with session pools. 
Not an OCILIB issue.
See issue #50
