### ISSUE TITLE
muti-thread test,frequently crash or dead lock

### ISSUE THREAD

**Issue by lv0zj** [vrogier/ocilib#80]
muti-thread test,frequently crash or dead lock, always in destruction,I'm using ocilib the first time ,I don't know why,
I'm sorry to bother you,but would you help me?thank you very much.

stack info:
1st:
 Thread 32 (Thread 0x7f6304206700 (LWP 84819)):
#0  0x00007f6316c22f4d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f6316c1ed02 in _L_lock_791 () from /lib64/libpthread.so.0
#2  0x00007f6316c1ec08 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x00007f630dc08cab in sltsmna () from /home/oracle/app/oracle/product/11.2.0/dbhome_1/lib/libclntsh.so.11.1
#4  0x00007f630cd1d9d0 in kpltMutexAcquire () from /home/oracle/app/oracle/product/11.2.0/dbhome_1/lib/libclntsh.so.11.1
#5  0x00007f630cc42779 in OCIThreadMutexAcquire () from /home/oracle/app/oracle/product/11.2.0/dbhome_1/lib/libclntsh.so.11.1
#6  0x00007f630e59d39d in OCI_MutexAcquire (mutex=0xa26a28) at mutex.c:135
#7  0x00007f630e84b686 in ocilib::Mutex::Acquire (mutex=0xa26a28) at /home/scm/rxserver/lib/ocilib/include/ocilib_impl.hpp:1274
#8  0x00007f630e84ae73 in ocilib::Locker::Lock (this=0x7f630ea79ea0 <ocilib::Environment::GetInstance()::envHandle>) at /home/scm/rxserver/lib/ocilib/include/ocilib_impl.hpp:566
#9  0x00007f630e84af4f in ocilib::Lockable::Lock (this=0x7f630ea79eb8 <ocilib::Environment::GetInstance()::envHandle+24>) at /home/scm/rxserver/lib/ocilib/include/ocilib_impl.hpp:592
#10 0x00007f630e85466c in ocilib::ConcurrentMap<void*, ocilib::Handle*>::Remove (this=0x7f630ea79eb8 <ocilib::Environment::GetInstance()::envHandle+24>, key=0x7f62f80ff738) at /home/scm/rxserver/lib/ocilib/include/ocilib_impl.hpp:624
#11 0x00007f630e856a8b in ocilib::Environment::SetSmartHandle<ocilib::HandleHolder<OCI_Coll*>::SmartHandle*> (ptr=0x7f62f80ff738, handle=0x0) at /home/scm/rxserver/lib/ocilib/include/ocilib_impl.hpp:1198
#12 0x00007f630e856c36 in ocilib::HandleHolder<OCI_Coll*>::SmartHandle::~SmartHandle (this=0x7f62f810aee0, __in_chrg=<optimized out>) at /home/scm/rxserver/lib/ocilib/include/ocilib_impl.hpp:802
#13 0x00007f630e856d0e in ocilib::HandleHolder<OCI_Coll*>::SmartHandle::~SmartHandle (this=0x7f62f810aee0, __in_chrg=<optimized out>) at /home/scm/rxserver/lib/ocilib/include/ocilib_impl.hpp:819
#14 0x00007f62e257876b in ocilib::HandleHolder<OCI_Coll*>::SmartHandle::Release (this=0x7f62f810aee0, holder=0x7f63042049b8) at /home/scm/rxserver/lib/ocilib/include/ocilib_impl.hpp:855
#15 0x00007f62e2577462 in ocilib::HandleHolder<OCI_Coll*>::Release (this=0x7f63042049b8) at /home/scm/rxserver/lib/ocilib/include/ocilib_impl.hpp:533
#16 0x00007f62e257597e in ocilib::HandleHolder<OCI_Coll*>::~HandleHolder (this=0x7f63042049b8, __in_chrg=<optimized out>) at /home/scm/rxserver/lib/ocilib/include/ocilib_impl.hpp:425
#17 0x00007f62e2580929 in ocilib::Collection<ocilib::Object>::~Collection (this=0x7f63042049b0, __in_chrg=<optimized out>) at /home/scm/rxserver/lib/ocilib/include/ocilib.hpp:4988

2st:
Thread 2 (Thread 0x7faf2c2db700 (LWP 19967)):
#0  0x00007faf45c7df4d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007faf45c79d02 in _L_lock_791 () from /lib64/libpthread.so.0
#2  0x00007faf45c79c08 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x00007faf3cba0b8f in sltsmna () from /home/fm/server/lib/oci/lib/libclntsh.so.11.1
#4  0x00007faf3bcb1fd8 in kpltMutexAcquire () from /home/fm/server/lib/oci/lib/libclntsh.so.11.1
#5  0x00007faf3bbd6d81 in OCIThreadMutexAcquire () from /home/fm/server/lib/oci/lib/libclntsh.so.11.1
#6  0x00007faf3783c39d in OCI_MutexAcquire (mutex=0xb2a818) at mutex.c:135
#7  0x00007faf103fc23e in ocilib::Mutex::Acquire (mutex=0xb2a818) at /home/scm/rxserver/lib/ocilib/include/ocilib_impl.hpp:1274
#8  0x00007faf103fbbb3 in ocilib::Locker::Lock (this=0x7faf38aab100 <ocilib::Environment::GetInstance()::envHandle>) at /home/scm/rxserver/lib/oc
ilib/include/ocilib_impl.hpp:566#9  0x00007faf103fbc8f in ocilib::Lockable::Lock (this=0x7faf38aab118 <ocilib::Environment::GetInstance()::envHandle+24>) at /home/scm/rxserver/l
ib/ocilib/include/ocilib_impl.hpp:592#10 0x00007faf104032ba in ocilib::ConcurrentMap<void*, ocilib::Handle*>::Remove (this=0x7faf38aab118 <ocilib::Environment::GetInstance()::envHand
le+24>, key=0x7faf20222e58) at /home/scm/rxserver/lib/ocilib/include/ocilib_impl.hpp:624#11 0x00007faf104023ab in ocilib::Environment::SetSmartHandle<ocilib::HandleHolder<OCI_Statement*>::SmartHandle*> (ptr=0x7faf20222e58, handle=0x0
) at /home/scm/rxserver/lib/ocilib/include/ocilib_impl.hpp:1198#12 0x00007faf10402c30 in ocilib::HandleHolder<OCI_Statement*>::SmartHandle::~SmartHandle (this=0x7faf20222f00, __in_chrg=<optimized out>) at /ho
me/scm/rxserver/lib/ocilib/include/ocilib_impl.hpp:802#13 0x00007faf10402d62 in ocilib::HandleHolder<OCI_Statement*>::SmartHandle::~SmartHandle (this=0x7faf20222f00, __in_chrg=<optimized out>) at /ho
me/scm/rxserver/lib/ocilib/include/ocilib_impl.hpp:819#14 0x00007faf104017d7 in ocilib::HandleHolder<OCI_Statement*>::SmartHandle::Release (this=0x7faf20222f00, holder=0x7faf2c2d99c0) at /home/scm/rx
server/lib/ocilib/include/ocilib_impl.hpp:855#15 0x00007faf10400260 in ocilib::HandleHolder<OCI_Statement*>::Release (this=0x7faf2c2d99c0) at /home/scm/rxserver/lib/ocilib/include/ocilib_imp
l.hpp:533#16 0x00007faf103fe858 in ocilib::HandleHolder<OCI_Statement*>::~HandleHolder (this=0x7faf2c2d99c0, __in_chrg=<optimized out>) at /home/scm/rxser
ver/lib/ocilib/include/ocilib_impl.hpp:425#17 0x00007faf103fbf0e in ocilib::Statement::~Statement (this=0x7faf2c2d99c0, __in_chrg=<optimized out>) at /home/scm/rxserver/lib/ocilib/include

3st:
#0  0x00007fb284b0dfcb in raise () from /lib64/libpthread.so.0
#1  0x00007fb27b4876c6 in skgesigOSCrash () from /home/fm/server/lib/oci/lib/libclntsh.so.11.1
#2  0x00007fb27b738f79 in kpeDbgSignalHandler () from /home/fm/server/lib/oci/lib/libclntsh.so.11.1
#3  0x00007fb27b4878d6 in skgesig_sigactionHandler () from /home/fm/server/lib/oci/lib/libclntsh.so.11.1
#4  <signal handler called>
#5  0x00007fb2832e45f7 in raise () from /lib64/libc.so.6
#6  0x00007fb2832e5ce8 in abort () from /lib64/libc.so.6
#7  0x00007fb284d7b9d5 in __gnu_cxx::__verbose_terminate_handler() () from /lib64/libstdc++.so.6
#8  0x00007fb284d79946 in ?? () from /lib64/libstdc++.so.6
#9  0x00007fb284d78909 in ?? () from /lib64/libstdc++.so.6
#10 0x00007fb284d79574 in __gxx_personality_v0 () from /lib64/libstdc++.so.6
#11 0x00007fb28367f903 in ?? () from /lib64/libgcc_s.so.1
#12 0x00007fb28367fe37 in _Unwind_Resume () from /lib64/libgcc_s.so.1
#13 0x00007fb250856d43 in ocilib::HandleHolder<OCI_Statement*>::SmartHandle::~SmartHandle (this=0x7fb2604af6e0, __in_chrg=<optimized out>) at /home/scm/rxserver/lib/ocilib/include/ocilib_impl.hpp:819
#14 0x00007fb250856d62 in ocilib::HandleHolder<OCI_Statement*>::SmartHandle::~SmartHandle (this=0x7fb2604af6e0, __in_chrg=<optimized out>) at /home/scm/rxserver/lib/ocilib/include/ocilib_impl.hpp:819
#15 0x00007fb2508557d7 in ocilib::HandleHolder<OCI_Statement*>::SmartHandle::Release (this=0x7fb2604af6e0, holder=0x7fb26b168a90) at /home/scm/rxserver/lib/ocilib/include/ocilib_impl.hpp:855
#16 0x00007fb250854260 in ocilib::HandleHolder<OCI_Statement*>::Release (this=0x7fb26b168a90) at /home/scm/rxserver/lib/ocilib/include/ocilib_impl.hpp:533
#17 0x00007fb250852858 in ocilib::HandleHolder<OCI_Statement*>::~HandleHolder (this=0x7fb26b168a90, __in_chrg=<optimized out>) at /home/scm/rxserver/lib/ocilib/include/ocilib_impl.hpp:425
#18 0x00007fb25084ff0e in ocilib::Statement::~Statement (this=0x7fb26b168a90, __in_chrg=<optimized out>) at /home/scm/rxserver/lib/ocilib/include/ocilib.hpp:5474

**Comment by vrogier** [comment]
Hi,

Please, provide:

- Platform information (OS, Architecture)
- OCILIB version
- Application source snippets or sample app code demonstrating the issue

Providing only call stacks is meaningless.

Regards,

Vincent

**Comment by lv0zj** [comment]
the issue is from my code,i mistake bind type .
thank you for your response!
