### ISSUE TITLE
Varchar to Int with OCI_VERSION_COMPILE = OCI_11_2

### ISSUE THREAD

**Issue by albertino80** [vrogier/ocilib#81]
I'm using ocilib on a workstation with **Oracle driver 11.2.0.1**

If I fetch a column of type **VARCHAR2** with `OCI_GetInt` I get always 0 as result
The varchar column contains "101".

I've changed in function `boolean OCI_NumberFromString`
from:
`#if OCI_VERSION_COMPILE >= OCI_12_1`
to:
`#if OCI_VERSION_COMPILE >= OCI_11_2`

And everything works fine. `OCI_GetInt` returns 101

So if you want to keep OCI_GetInt with string to int compatible for Oracle 11, consider this change.

Thanks.

**Comment by vrogier** [comment]
Hi,

Thanks for reporting issues:)

I cannot remember why I've added this the define you are referring to in v4.2.0 (even no trace in the related commit comment, which is not a good thing!)

I'm going to commit a fix that removes the define...

Best regards,

Vincent
