### ISSUE TITLE
Oracle DCN on linux?

### ISSUE THREAD

**Issue by Zeks** [vrogier/ocilib#82]
It works fine on windows but stops indefinitely on the line below on linux:

            OCI_EXEC(OCISubscriptionRegister(sub->con->cxt, &sub->subhp, (ub2) 1, sub->err,(ub4) OCI_DEFAULT))
It just hangs indefinitely on pthread_cond_wait after that call

Both Centos 6.7 32 and 64 bit, older and newer ocilib drivers. Tried both 11 and 12 version of oracle instant client.

ocilib is compiled with wide charset

**Comment by vrogier** [comment]
Hi,

Seems to be either an oracle related (internal oci conditional variable) issue or network issue (you may check your sqlnet.ora file).

Regards,

Vincent

**Comment by vrogier** [comment]
Closing the issue as no new from OP.
