### ISSUE TITLE
Oracle exception message is different when using unsigned int vs unsigned long long

### ISSUE THREAD

**Issue by GlassyPeou** [vrogier/ocilib#86]
I'm seeing an issue when reading an oracle exception message in c++.

Here's the oracle table and constraint i've set up:
CREATE TABLE TestTableTbl(
	id NUMBER
);

ALTER TABLE TestTableTbl
	ADD CONSTRAINT TestTableTbl_id_uk 
	UNIQUE (id);

Here is the oracle package i've defined:
CREATE OR REPLACE PACKAGE TestAdapter IS
	PROCEDURE TestInsert(
		p_in	IN NUMBER,
		p_out	OUT NUMBER
	);
END TestAdapter;

CREATE OR REPLACE PACKAGE BODY TestAdapter IS
	PROCEDURE TestInsert(
		p_in	IN NUMBER,
		p_out	OUT NUMBER
	)
	AS
	BEGIN
		INSERT INTO PlatSys.TestTableTbl ( id )
		VALUES
		(
			p_in
		)
		RETURNING id
		INTO p_out;
	END TestInsert;
END TestAdapter;

Here is the C++ code i'm running:
try
{
	ocilib::Pool pool(connect, user, pwd, ocilib::Pool::SessionPool, 0, 3);
	ocilib::Connection connection = pool.GetConnection();
	ocilib::Statement statement(connection);
	int in = 1;
	unsigned long long out = 0; // scenario A
	unsigned int out = 0; // scenario B
	statement.Prepare(_T("begin TestAdapter.TestInsert( :1, :2 ); end;"));
	statement.Bind(_T("1"), in, ocilib::BindInfo::In);
	statement.Bind(_T("2"), out, ocilib::BindInfo::Out);
	statement.ExecutePrepared();
}
catch (ocilib::Exception e)
{
	std::cout << e.what() << std::endl;
}

I've inserted one row into the TestTableTbl with id = 1.

When I run the C++ code with scenario A in place e.what doesn't reflect the constraint violation i'm expecting.
When I run the C++ code with scenario B e.what does show the constraint violation i'm expecting.

Why is this happening? Am I doing something wrong when using unsigned long long vs unsigned int?

**Comment by vrogier** [comment]
Hi,

I will test your code and check the source of the issue.
Basically,  when binding 32bits integers, the host variable address is directly passed to oracle.
When binding 64bits integers, ocilib is using an OCINumber (OCI C counter part of server side generic NUMBER) and does assignment from/to host variable before/after statement execution (Oracle only support native bindings for 64bits integers starting with 12cR1)
In that process, ocilib might loose the original error as more internal intermediate code is executed.
I will check it and find it a fix for it this week.

Thanks for reporting issues :)

Best regards,

Vincent

**Comment by GlassyPeou** [comment]
Great. When do you think the release will be out with this fix?
