### ISSUE TITLE
OCI_BindArrayOfStrings memory corruption

### ISSUE THREAD

**Issue by stevemqeen** [vrogier/ocilib#89]
When using this bind function to update DB in batch mode, the application crash is explored. The problem is in the **OCI_StringUTF16ToUTF32**, the input data is stored as **UTF16**, but the step is (**index * size * sizeof(otext)**), when ocilib compiled to use widechar the otext variable will be set to **UTF32**. For a little workaround you can look at this commit - https://github.com/stevemqeen/ocilib/commit/5c28fbbd1e1c715cf220090f7c2083d80038eccd

**Comment by vrogier** [comment]
Hi,

Thanks for reporting issues. 

I will commit a fix for it this evening and release v4.3.3 by the weekend.

Best regards,

Vincent
