### ISSUE TITLE
Get Korean character with Windows C++(VS2013)

### ISSUE THREAD

**Issue by dduckk** [vrogier/ocilib#91]
Hi, vrogier.

i can't get korean character correctly at demo from **rowid.c** on windows platform. The original string that inserted database is "한글테스트", but printed string is "?쒓??뚯뒪?"

but this result on linux(centOS) is printed correctly("한글테스트")

using OCILIB Version is v4.3.2

Windows : Define OCI_IMPORT_LINKAGE, OCI_CHARSET_ANSI and OCI_API=__stdcall
                  link libocia.lib(dll)
                  Environment Variable : NLS_LANG=AMERICAN_AMERICA.AL32UTF8

ORACLE NLS_LANG : AMERICAN_AMERICA.AL32UTF8

	OCI_Immediate(cn, "select rowid from products where code = 1", OCI_ARG_TEXT, rowid);

	OCI_Prepare(st, "select code, name, rowid from products where rowid = :id");

	OCI_BindString(st, ":id", rowid, (unsigned int)strlen(rowid));
	OCI_Execute(st);
	rs = OCI_GetResultset(st);
	OCI_FetchNext(rs);
	printf("code [%d], name [%s], rowid [%s]", OCI_GetInt(rs, 1), OCI_GetString(rs, 2), OCI_GetString(rs, 3));

	OCI_StatementFree(st);
	OCI_ConnectionFree(cn);
	OCI_Cleanup();`

fetch result on linux :       code [1], name [한글테스트], rowid [AAASE3AAFAAAACOAAA]
fetch result on windows : code [1], name [?쒓??뚯뒪??, rowid [AAASE3AAFAAAACOAAA]

Thanks for your help!

**Comment by vrogier** [comment]
Hi,

I've missed the notification for this issue :(

When you say "printing", do you mean printing on the ouput console ?
 Is your md windows console charset the right one ?
Can you dump individual char  of  'bind" char array values from linux and windows program to see any difference ?

thanks

vincent

**Comment by vrogier** [comment]
Closing the issue as no news from OP.
