### ISSUE TITLE
Labwindows/CVI calling convention problem

### ISSUE THREAD

**Issue by Kugelkopf** [vrogier/ocilib#92]
Hello Vincent,

I may misunderstand the concept of calling conventions, but I would like to really find out how this works.
I would like to use the OCILIB functions with variables, but Labwindows/CVI ( which is an ANSI C intergrated developement environment) does not let me compile the project when i set the calling convention to cdecl instead of stdcall. I would like to use functions like this : 
OCI_ExecuteStmt(st, "insert into table1 values(1, 10.5)");
with paramters like this : 
 OCI_ExecuteStmt(st, "insert into table(i) values(a, b)");
I have also modified the calling ceonvention in the ocilib.h file
/* Calling convention */

#ifndef OCI_API
  #ifdef _MSC_VER
    #define OCI_API __stdcall
  #else
    #define OCI_API 
  #endif
#endif

Though, it still does not work only with the constant numbers. From the ReadMe.txt file i could not find out the problem. Please let me know where i went wrong.

Thank you in advance!

**Comment by vrogier** [comment]
Hi,

I don't really understand your issue. 
What's the relation between the calling convention and using bind variables ?
Using LabView, OCI_API is not defined and default calling convention is cdecl.
If you're using precompiled OCILIB Dlls, you must define OCI_API to __stdcall.
You generally do that by passing the flag -DOCI_API=__stdcall to your compiler.
Regards,

Vincent

**Comment by vrogier** [comment]
Hi,

Here is it!

Vincent
[UnitTests.txt](https://github.com/vrogier/ocilib/files/1144493/UnitTests.txt)

**Comment by vrogier** [comment]
Closing the issue as no news from OP
