### ISSUE TITLE
Doesn't compatible with boost asio

### ISSUE THREAD

**Issue by Cqspel** [vrogier/ocilib#93]
Because of
`#ifndef boolean`
`  #define boolean int`
`#endif`

in ocilib.h (line 1068), get error:
boost/asio/detail/socket_option.hpp:33:1: error: declaration of anonymous class must be a definition
class boolean

Could be repaired by changing to (bad hack)
`using boolean = int;`

**Comment by vrogier** [comment]
Many libraries / frameworks define a "boolean" type : Oracle, Windows, openssl, boost::asio, ...

Even if ocilib was not defining it, it would be an issue when mixing any of the headers from the libs mentioned above.

You can play with header inclusion order and define/undef clauses to make it work....

Regards,

Vincent

**Comment by Cqspel** [comment]
No doubts, headers inclusion reorganization works, but you have to spent some time to make the code right. If the legacy project is big you'll wastе a lot of time searching the right header file.

By the way, using ocilibC++ version you don't expect to catch a problem on global "boolean" macro definition.
Even namespaces can't help:
...
`namespace boost {`
`namespace asio {`
`namespace detail {`
`namespace socket_option {`

`// Helper template for implementing boolean-based options.`
`template <int Level, int Name>`
`class boolean`
`{`
....
`};`

**Comment by vrogier** [comment]
There is pretty much nothing I can do about it as Oracle OCI headers and Windows headers also define this value. Even if ocilib was not defining it, the latter one would do.
