### ISSUE TITLE
Valgrind Error running on C sample application

### ISSUE THREAD

**Issue by Taymindis** [vrogier/ocilib#97]
Attached valgrind report file for reference.

Is this common behaviour from oracle Lib?

[output.txt](https://github.com/vrogier/ocilib/files/1229979/output.txt)

**Comment by Taymindis** [comment]
~~Dr.M~~
~~Dr.M~~ Error #1: POSSIBLE LEAK 40 direct bytes 0x0000000000629260-0x0000000000629288 + 0 indirect bytes
~~Dr.M~~ # 0 replace_malloc               [/home/dispatch/testMap/drmemory/common/alloc_replace.c:2576]
~~Dr.M~~ # 1 libocilib.so.4!OCI_MemAlloc  [/home/dispatch/testMap/ocilib/src/memory.c:56]
~~Dr.M~~ # 2 libclntsh.so.11.1!kpummealloc+0x5f     (0x00007f1cb2ef2a28 <libclntsh.so.11.1+0xb19a28>)
~~Dr.M~~ # 3 libclntsh.so.11.1!?         +0x0      (0x00007f1cb2ef47d7 <libclntsh.so.11.1+0xb1b7d7>)
~~Dr.M~~ # 4 libclntsh.so.11.1!?         +0x0      (0x00007f1cb2ef4576 <libclntsh.so.11.1+0xb1b576>)
~~Dr.M~~ # 5 libclntsh.so.11.1!?         +0x0      (0x00007f1cb2930a25 <libclntsh.so.11.1+0x557a25>)
~~Dr.M~~ # 6 libclntsh.so.11.1!?         +0x0      (0x00007f1cb292e705 <libclntsh.so.11.1+0x555705>)
~~Dr.M~~ # 7 libclntsh.so.11.1!nlstdggo  +0x2e9    (0x00007f1cb4397df6 <libclntsh.so.11.1+0x1fbedf6>)
~~Dr.M~~ # 8 libclntsh.so.11.1!nlstdgg   +0x1a     (0x00007f1cb4397b07 <libclntsh.so.11.1+0x1fbeb07>)
~~Dr.M~~ # 9 libclntsh.so.11.1!nigini2   +0x39e    (0x00007f1cb29d887b <libclntsh.so.11.1+0x5ff87b>)
~~Dr.M~~ #10 libclntsh.so.11.1!?         +0x0      (0x00007f1cb2ef4db4 <libclntsh.so.11.1+0xb1bdb4>)
~~Dr.M~~ #11 libclntsh.so.11.1!kpeDbgTLSInit+0xff     (0x00007f1cb2ef4c88 <libclntsh.so.11.1+0xb1bc88>)
~~Dr.M~~
~~Dr.M~~ Error #2: POSSIBLE LEAK 176 direct bytes 0x0000000000677630-0x00000000006776e0 + 476 indirect bytes
~~Dr.M~~ # 0 replace_malloc               [/home/dispatch/testMap/drmemory/common/alloc_replace.c:2576]
~~Dr.M~~ # 1 libocilib.so.4!OCI_MemAlloc  [/home/dispatch/testMap/ocilib/src/memory.c:56]
~~Dr.M~~ # 2 libclntsh.so.11.1!LhtIntCreate+0x627    (0x00007f1cb2baeccc <libclntsh.so.11.1+0x7d5ccc>)
~~Dr.M~~ # 3 libclntsh.so.11.1!kpummpin  +0x2f9    (0x00007f1cb2ef3452 <libclntsh.so.11.1+0xb1a452>)
~~Dr.M~~ # 4 libclntsh.so.11.1!kpuenvcr  +0xaa     (0x00007f1cb2885c53 <libclntsh.so.11.1+0x4acc53>)
~~Dr.M~~ # 5 libclntsh.so.11.1!OCIEnvCreate+0x33     (0x00007f1cb28578fe <libclntsh.so.11.1+0x47e8fe>)
~~Dr.M~~ # 6 libocilib.so.4!OCI_Initialize [/home/dispatch/testMap/ocilib/src/library.c:1419]
~~Dr.M~~ # 7 libc.so.6!__GI_bsearch
~~Dr.M~~ # 8 main                         [/home/dispatch/testMap/ocilib/test.c:9]
~~Dr.M~~
~~Dr.M~~ Error #3: POSSIBLE LEAK 16 direct bytes 0x0000000000677820-0x0000000000677830 + 0 indirect bytes
~~Dr.M~~ # 0 replace_malloc               [/home/dispatch/testMap/drmemory/common/alloc_replace.c:2576]
~~Dr.M~~ # 1 libocilib.so.4!OCI_MemAlloc  [/home/dispatch/testMap/ocilib/src/memory.c:56]
~~Dr.M~~ # 2 libclntsh.so.11.1!LhtqmAlloc+0x16     (0x00007f1cb2baf30f <libclntsh.so.11.1+0x7d630f>)
~~Dr.M~~ # 3 libclntsh.so.11.1!LhtIntCreate+0x1cb    (0x00007f1cb2bae870 <libclntsh.so.11.1+0x7d5870>)
~~Dr.M~~ # 4 libclntsh.so.11.1!kpummpin  +0x2f9    (0x00007f1cb2ef3452 <libclntsh.so.11.1+0xb1a452>)
~~Dr.M~~ # 5 libclntsh.so.11.1!kpuenvcr  +0xaa     (0x00007f1cb2885c53 <libclntsh.so.11.1+0x4acc53>)
~~Dr.M~~ # 6 libclntsh.so.11.1!OCIEnvCreate+0x33     (0x00007f1cb28578fe <libclntsh.so.11.1+0x47e8fe>)
~~Dr.M~~ # 7 libocilib.so.4!OCI_Initialize [/home/dispatch/testMap/ocilib/src/library.c:1419]
~~Dr.M~~ # 8 libc.so.6!__GI_bsearch
~~Dr.M~~ # 9 main                         [/home/dispatch/testMap/ocilib/test.c:9]
~~Dr.M~~
~~Dr.M~~ Error #4: POSSIBLE LEAK 272 direct bytes 0x0000000000677870-0x0000000000677980 + 0 indirect bytes
~~Dr.M~~ # 0 replace_malloc               [/home/dispatch/testMap/drmemory/common/alloc_replace.c:2576]
~~Dr.M~~ # 1 libocilib.so.4!OCI_MemAlloc  [/home/dispatch/testMap/ocilib/src/memory.c:56]
~~Dr.M~~ # 2 libclntsh.so.11.1!LhtqmAlloc+0x16     (0x00007f1cb2baf30f <libclntsh.so.11.1+0x7d630f>)
~~Dr.M~~ # 3 libclntsh.so.11.1!LhtIntCreate+0x245    (0x00007f1cb2bae8ea <libclntsh.so.11.1+0x7d58ea>)
~~Dr.M~~ # 4 libclntsh.so.11.1!kpummpin  +0x2f9    (0x00007f1cb2ef3452 <libclntsh.so.11.1+0xb1a452>)
~~Dr.M~~ # 5 libclntsh.so.11.1!kpuenvcr  +0xaa     (0x00007f1cb2885c53 <libclntsh.so.11.1+0x4acc53>)
~~Dr.M~~ # 6 libclntsh.so.11.1!OCIEnvCreate+0x33     (0x00007f1cb28578fe <libclntsh.so.11.1+0x47e8fe>)
~~Dr.M~~ # 7 libocilib.so.4!OCI_Initialize [/home/dispatch/testMap/ocilib/src/library.c:1419]
~~Dr.M~~ # 8 libc.so.6!__GI_bsearch
~~Dr.M~~ # 9 main                         [/home/dispatch/testMap/ocilib/test.c:9]
~~Dr.M~~
~~Dr.M~~ Error #5: POSSIBLE LEAK 139264 direct bytes 0x00007f1cb14b1040-0x00007f1cb14d3040 + 192 indirect bytes
~~Dr.M~~ # 0 replace_calloc               [/home/dispatch/testMap/drmemory/common/alloc_replace.c:2616]
~~Dr.M~~ # 1 libclntsh.so.11.1!slwmmgetmem+0x14     (0x00007f1cb2bb48c5 <libclntsh.so.11.1+0x7db8c5>)
~~Dr.M~~ # 2 libclntsh.so.11.1!lmmstvrt  +0x8c     (0x00007f1cb2bb465d <libclntsh.so.11.1+0x7db65d>)
~~Dr.M~~ # 3 libclntsh.so.11.1!lmmstchnk +0x75     (0x00007f1cb2bb2fde <libclntsh.so.11.1+0x7d9fde>)
~~Dr.M~~ # 4 libclntsh.so.11.1!lmmstsml  +0xc1     (0x00007f1cb2bb44e2 <libclntsh.so.11.1+0x7db4e2>)
~~Dr.M~~ # 5 libclntsh.so.11.1!lmmstmalloc+0xdd     (0x00007f1cb43f42ba <libclntsh.so.11.1+0x201b2ba>)
~~Dr.M~~ # 6 libclntsh.so.11.1!lmmmalloc +0x91     (0x00007f1cb43f38ee <libclntsh.so.11.1+0x201a8ee>)
~~Dr.M~~ # 7 libclntsh.so.11.1!lmmcis    +0x60     (0x00007f1cb2bb0f89 <libclntsh.so.11.1+0x7d7f89>)
~~Dr.M~~ # 8 libclntsh.so.11.1!lpmpali   +0x2e7    (0x00007f1cb2bb61a4 <libclntsh.so.11.1+0x7dd1a4>)
~~Dr.M~~ # 9 libclntsh.so.11.1!lpminitm  +0x212    (0x00007f1cb2bb5455 <libclntsh.so.11.1+0x7dc455>)
~~Dr.M~~ #10 libclntsh.so.11.1!lpminit   +0x13     (0x00007f1cb2bb523c <libclntsh.so.11.1+0x7dc23c>)
~~Dr.M~~ #11 libclntsh.so.11.1!?         +0x0      (0x00007f1cb2b9ae2c <libclntsh.so.11.1+0x7c1e2c>)

**Comment by vrogier** [comment]
Hi,

Sorry for late response.

Oracle OCI  library is known to produce such output in valgrind (check on google for valgrind+oracle+oci).

If some stack traces show ocilib calls OCI_MemAlloc(), it is because OCI allows to provide custom allocation function pointer to replace its own allocation routine. 
That's what ocilib does. 
Even it it didn't, you'll get similar output showing the oracle oci internal routine instead.

There is nothing I can do about it.

Regards,

Vincent
