### ISSUE TITLE
Array binding wide strings does not seem to work

### ISSUE THREAD

**Issue by bangusi** [vrogier/ocilib#99]
I may be misusing the library. Here is what I attempted.
Modified the sample code in the file 'array.c' as follows: Showing only the parts that I changed

```
	int tab_int[ARRAY_SIZE];
	wchar_t tab_str[ARRAY_SIZE][STRING_SIZE];
	int i;
	OCI_Statement* st = OCI_StatementCreate(cn);
	OCI_Prepare(st, L"insert into products values(:i, :s)");
	OCI_BindArraySetSize(st, ARRAY_SIZE);
	OCI_BindArrayOfInts(st, L":i", (int*)tab_int, 0);
	OCI_BindArrayOfStrings(st, L":s", (wchar_t*)tab_str, STRING_SIZE, 0);
	for (i = 0; i<1000; i++)
	{
		swprintf(tab_str[i], 20, L"Name %d", i + 1);
	}
```
My environment: Visual Studio 2017, On Windows 7, x64 bit build. Oracle clinet 12,  Oracle Server 12
When I run the example I get this error:

**ORA-01480: trailing null missing from STR bind value**

**Comment by stevemqeen** [comment]
According to old demo for arrays, your initialized size of string variable is a little bit wrong. It should be STRING_SIZE+1.

**Comment by bangusi** [comment]
That fixes the issue. Thanks. But the demo in my download does not initialize the string this way. Is is a bug?
